doc/WebSiteContents/nlayer-architecture.html
I've made some tweaks in grammar, revised presentation for consistency, and restructured in a few places to clarify intent.
=> Doc changes to NLayer Architecture

src/Abp/Application/Navigation/MenuItemDefinition.cs
i need to implement dynamic menu therefore  Items have to be virtual
=> enable app to create dynamic menu

src/Tests/Abp.AutoMapper.Tests/AutoMapper_Inheritance_Tests.cs
I added inheritance test that fails. It's not about original problem but it fits common case whith EF Entities.
=> Auto mapper inheritance test that fails

src/Abp.Web.Api/Abp.Web.Api.csproj, src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/TypeScript/TypeScriptDefinitionGenerator.cs, src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/TypeScript/TypeScriptProxyGenerator.cs, src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/TypeScriptController.cs
using the TypeScriptController you can get the type script definition.
till moment I'm using gruntfile.js to generate the script and add to the WebUI.
=> Generate Typescript type definition

src/Abp.Web/Abp.Web.csproj, src/Abp.Web/Web/Localization/AbpWebXmlSource/AbpWeb-de-DE.xml, src/Abp/Abp.csproj, src/Abp/Localization/Sources/AbpXmlSource/Abp-de-DE.xml
German xml source localization
=> German Localization

src/Abp.Web/Abp.Web.csproj, src/Abp.Web/Web/Localization/AbpWebXmlSource/AbpWeb-pt-BR.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-pt-BR.xml
Localization for Portuguese - Brazil.
=> Localization pt-BR

src/Abp.Web/Abp.Web.csproj, src/Abp.Web/Web/Localization/AbpWebXmlSource/AbpWeb-lt.xml, src/Abp/Abp.csproj, src/Abp/Localization/Sources/AbpXmlSource/Abp-lt.xml
Added localization for Lithuanian.
P. S.
Thanks for such a great framework!
=> Added localization for Lithuanian (lt).

doc/WebSiteContents/javascript-api.html
Some minor corrections to improve readability.
=> Docs: Correct minor typos in javascript-api docs

src/Abp/Abp.csproj, src/Abp/Localization/Sources/AbpXmlSource/Abp-it.xml
Added localization for Italian.
=> Add Italian Translation

src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/TypeScript/TypeScriptHelper.cs, src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/TypeScriptController.cs
Now using grunt you can have the following:
```javascript
/// <binding AfterBuild='default' ProjectOpened='watch' />
module.exports = function (grunt) {
grunt.initConfig({
http: {
ServicesDefenitionsTypeScript: {
options: {
url: 'http://localhost:12211/api/TypeScript/Get'
},
dest: 'typings/services/apiservices.d.ts'
},
ServicesCompleteTypeScript: {
options: {
url: 'http://localhost:12211/api/TypeScript/Get?isCompleteService=true'
},
dest: 'App/Main/services/angular1Services.ts'
}
}
});
grunt.loadNpmTasks('grunt-http');
};
=> make the DateTime variables appear as Date in TypeScript and modify the generator signature

src/Abp.Web/Abp.Web.csproj, src/Abp.Web/Web/Localization/AbpWebXmlSource/AbpWeb-ca-ES.xml, src/Abp.Web/Web/Localization/AbpWebXmlSource/AbpWeb-es.xml, src/Abp/Abp.csproj, src/Abp/Localization/Sources/AbpXmlSource/Abp-ca-ES.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-es.xml
Web\Localization\AbpWebXmlSource\AbpWeb-es.xml
Web\Localization\AbpWebXmlSource\AbpWeb-ca-ES.xml
Localization\Sources\AbpXmlSource\Abp-es.xml
Localization\Sources\AbpXmlSource\Abp-ca-ES.xml
=> Add the Catalan and Spanish language/culture translation files

src/Abp.Web/Abp.Web.csproj, src/Abp.Web/Web/Localization/AbpWebXmlSource/AbpWeb-fr.xml, src/Abp/Abp.csproj, src/Abp/Localization/Sources/AbpXmlSource/Abp-fr.xml
=> Add French translations

src/Abp.HangFire/Hangfire/HangfireBackgroundJobManager.cs
if has delay value, use HangfireBackgroundJob.Schedule to support delay job
=> hangfire module add delay job support

doc/WebSite/OData-Integration.html
Check out http://www.aspnetboilerplate.com/Pages/Documents/OData-Integration#creating-a-new-entity
=> Fix intendation

README.md
Halil, add this note to your readme.md. It's not clear or obvious that this project format has been migrated to .NET Core. I just saw someone struggling for 30 minutes trying to figure out why the project was not loading in VS2015
=> Suggested change for readme.md

doc/WebSite/Audit-Logging.html, doc/WebSite/Data-Filters.html, doc/WebSite/Data-Transfer-Objects.html, doc/WebSite/EventBus-Domain-Events.html, doc/WebSite/Multi-Tenancy.html, doc/WebSite/NLayer-Architecture.html, doc/WebSite/Unit-Of-Work.html, doc/WebSite/Zero/Language-Management.html, doc/WebSite/Zero/Role-Management.html, doc/WebSite/Zero/Startup-Template.html, src/Abp/Configuration/SettingDefinitionGroup.cs
I've read the documentation and corrected some typos and minor grammar errors.
=> Fixed docs typos

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-lt.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-lt.xml
Just an update to Lithuanian translation.
=> Updated Lithuanian translation files.

src/Abp/Dependency/DisposableScopedDependencyObjectWrapper.cs, src/Abp/Dependency/IDisposableScopedDependencyObjectWrapper.cs, src/Abp/Dependency/IocResolverExtensions.cs, test/Abp.Tests/Dependency/DisposableScopedDependencyObjectWrapper_Tests.cs, test/Abp.Tests/Dependency/SimpleDisposableObject2.cs, test/Abp.Tests/Dependency/SimpleDisposableObject3.cs
If you have a chance to review and find it appropriate, i really appreciate.
Thanks in advance.
=> Implementation of DisposableScopedDependencyObjectWrapper #1519

src/Abp/Modules/AbpModuleCollection.cs, src/Abp/Modules/AbpModuleManager.cs, test/Abp.Tests/Modules/StartupModuleToBeLast_Tests.cs
Hi @hikalkan,
Hopefully I've thought right and I hope it would be able for merge :)
Thanks.
=> Force startup module to be initialized as the last module

doc/WebSite/Dependency-Injection.html
=> Docs Dependency Injection spelling fix

src/Abp.AspNetCore/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs
I have implement Cors
When the exception will be thrown cors the http head of information removed, the client can not read to the mesage
=> Fix UserFriendlyException not return

doc/WebSite/Feature-Management.html
Fix a word error in feature management documentation.
=> fix a word error

Abp.sln, src/Abp.Quartz/Quartz/AbpQuartzModule.cs, src/Abp.Quartz/Quartz/Configuration/AbpQuartzConfigurationExtensions.cs, src/Abp.Quartz/Quartz/QuartzScheduleJobManager.cs, test/Abp.Quartz.Tests/Abp.Quartz.Tests.xproj, test/Abp.Quartz.Tests/AbpQuartzTestModule.cs, test/Abp.Quartz.Tests/Properties/AssemblyInfo.cs, test/Abp.Quartz.Tests/QuartzTests.cs, test/Abp.Quartz.Tests/project.json
I hope, I understood your point correctly ? 
Thanks in advance.
=> Abp.Quartz refactor for #867 & Unit tests

doc/WebSite/Quartz-Integration.html
Hi,
I've added a humble documentation for quartz.
=> Abp.Quartz documentation

appveyor.yml
=> Changed AppVeyor image to VS 2017 RTM

src/Abp.Dapper/Dapper/Filters/Query/MayHaveTenantDapperQueryFilter.cs, src/Abp.Dapper/Dapper/Filters/Query/MustHaveTenantDapperQueryFilter.cs, src/Abp.Dapper/Dapper/Filters/Query/SoftDeleteDapperQueryFilter.cs
* **Refactor**: instead of _InheritsOrImplements_ use _IsAssignableFrom_
* **Fixed**: _IMayHaveTenant_ interface used in _MustHaveTenantDapperQueryFilter_ by mistake.
=> Refactor and Problem Fix for Abp.Dapper

src/Abp/Timing/Timezone/TimezoneHelper.cs, test/Abp.Tests/Timing/TimezoneHelper_Tests.cs
I did a little refactor, if there is problem with it, please let me know :)
=> iana to windows mappings, convert time by iana timezone id

test/Abp.EntityFrameworkCore.Tests/Tests/EntityChangeEvents_Tests.cs
The assertion code for updatedEventTriggered is wrong in ```EntityChangeEvents_Tests.cs```
=> Fixed assertion for updatedEventTriggered

src/Abp.AutoMapper/AutoMapper/AutoMapFromAttribute.cs
Corresponds to the change in `AutoMapToAttribute`: https://github.com/aspnetboilerplate/aspnetboilerplate/commit/4276897202f24cb7c95a67be6dcfea88276cb837#diff-6f85f9ce9b0785970c631fe737b7ee5dL24
=> Fix create map not using MemberList property

doc/WebSite/Hangfire-Integration.html
Fixed wrong hangfire module name for .net core integration.
=> Updated Hangfire integration page.

src/Abp.Web.Common/Web/Models/DefaultErrorInfoConverter.cs, test/Abp.Web.Common.Tests/Web/DefaultErrorInfoConverter.cs, test/Abp.Web.Common.Tests/Web/DefaultErrorInfoConverter_Tests.cs
EntityNotFoundException handling in DefaultErrorInfoConverter
=> resolved #2304 EntityNotFoundException handling in

src/Abp/Application/Navigation/MenuItemDefinition.cs, src/Abp/Application/Navigation/UserNavigationManager.cs, test/Abp.Tests/Application/Navigation/NavigationTestCase.cs
=> Feature IPermissionDependency in MenuItemDefinition

doc/WebSite/Debugging.html, doc/WebSite/Embedded-Resource-Files.html, doc/WebSite/Handling-Exceptions.html, doc/WebSite/Javascript-API/Message.html, doc/WebSite/Javascript-API/Notification.html, doc/WebSite/Javascript-API/UI-Block-Busy.html, doc/WebSite/Localization.html, doc/WebSite/NLayer-Architecture.html, doc/WebSite/Notification-System.html, doc/WebSite/Swagger-UI-Integration.html, doc/WebSite/Zero/Startup-Template-Angular.html, doc/WebSite/Zero/Startup-Template-Core.html, doc/WebSite/Zero/Startup-Template.html
Resolved #2237 Images are not responsive in the documentation after new web site
=> Resolved #2237 Images are not responsive in the documentation after 

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-fr.xml
Add missing texts in AbpWeb-fr.xml.
=> Add missing texts to french translation

src/Abp/Authorization/PermissionDependencyContext.cs
=> Changed PermissionDependencyContext from internal to public

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-de.xml
Add missing texts in AbpWeb-de.xml.
=> Add missing texts to german translation

src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero-zh-CN.xml
Fixes aspnetboilerplate/module-zero#416
Extracted from [src/Abp.Zero/Zero/Localization/SourceExt/AbpZero-zh-CN.xml](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/bc266e3503fcb2825684ec829cc356815f94f397/src/Abp.Zero/Zero/Localization/SourceExt/AbpZero-zh-CN.xml)
Aligned to [src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero.xml](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/bc266e3503fcb2825684ec829cc356815f94f397/src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero.xml)
Renamed (6):
- `Identity.LockoutNotEnabled -> Identity.UserLockoutNotEnabled`
- `Identity.PasswordRequireDigit -> Identity.PasswordRequiresDigit`
- `Identity.PasswordRequireLower -> Identity.PasswordRequiresLower`
- `Identity.PasswordRequireNonLetterOrDigit` -> …
=> Add localization in ZeroCore for AbpZero-zh-CN.xml

src/Abp.AspNetCore.TestBase/AbpAspNetCoreIntegratedTestBase.cs
To fix https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2567
=> Public HttpClient in AbpAspNetCoreIntegratedTestBase

src/Abp.EntityFrameworkCore/EntityFrameworkCore/DefaultDbContextResolver.cs
For issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2506
Although it's not possible to change the parameter name, it's better to throw a friendly exception.
=>  Throw an AggregateException which contains friendly message

src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero-lt.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-lt.xml
Just a simple translation correction.
=> Updated / corrected Lithuanian translations for Abp.ZeroCore and Abp.

src/Abp.Zero.Common/Application/Features/AbpFeatureValueStore.cs, src/Abp.Zero.Common/Application/Features/FeatureSetting.cs, src/Abp.Zero.Common/MultiTenancy/TenantFeatureCacheItemInvalidator.cs, src/Abp.Zero.Common/MultiTenancy/TenantFeatureSetting.cs
=> fixes #2529: move TenantId to FeatureSettings from TenantFeatureSettings

src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs
=> fixes #2609: use expression visitor to combine lambda expressions for data filters

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.sweet-alert.js, test/aspnet-core-demo/AbpAspNetCoreDemo/wwwroot/Abp/Framework/scripts/libs/abp.sweet-alert.js
This release requires applications upgrade to sweetalert 2.x.
=> Fixed #2145 Change to sweetalert v2

src/Abp.MailKit/EmailExtensions.cs
mentioned in https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2715
=> Fixed using public constructor of mime message

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-fa.xml
Fixes #2730 
Now on par with [src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb.xml](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/681f25249e64c57605016af96c2930b1763236ac/src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb.xml)
=> Add localization in Web.Common for AbpWeb-fa.xml

doc/WebSite/About.html
I noticed that English is not your first language.  Let me help you with that.
=> Some grammar and text changes in the docs/website/About.html.

doc/WebSite/AspNet-Core.html
- Package suggested: #2505
- Documentation requested: https://stackoverflow.com/questions/47591705/how-to-use-httpget-in-asp-net-core-dynamic-web-api
=> Add package name for ASP.NET Core HTTP attributes to doc

doc/WebSite/Documents.md, doc/WebSite/SignalR-Integration.md, doc/WebSite/Web-API-Controllers.html
=> Add links for SignalR-AspNetCore-Integration doc

doc/WebSite/Dependency-Injection.md
Please review this carefully.  I had to rewrite some paragraphs.
=> Dependency-Injection.md document changes

doc/WebSite/Dynamic-Web-API.md
=> Dynamic-Web-API.md document changes

doc/WebSite/Background-Jobs-And-Workers.md
- Correct spelling and improve grammar
- Improve formatting
=> Background-Jobs-And-Workers.md document changes

src/Abp.Zero.Common/Authorization/Roles/RoleClaim.cs, src/Abp.Zero.Common/Authorization/Users/UserAccount.cs, src/Abp.Zero.Common/Authorization/Users/UserClaim.cs, src/Abp.ZeroCore/Authorization/Users/AbpUser.cs
This are my proposed fixes to the problems mentioned in the issue #2762
=> Abp.Zero fixes for Abp.ZeroCore.EntityFramework

doc/WebSite/SignalR-AspNetCore-Integration.md
See [MyCommonHub.cs#L22](https://github.com/acjh/module-zero-core-template/blob/60f888eee10677763f57e56d51430d749b721aa2/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/MyCommonHub.cs#L22)
=> Update code in SignalR-AspNetCore-Integration.md

src/Abp/Authorization/Permission.cs
As per https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1943
In order to implement custom permissions, Permission should be inheritable.
=> Add the ability to inherit permission

doc/WebSite/Introduction.md
Lots of changes.  Please review carefully, thanks!
=> Introduction.md document changes

src/Abp/Timing/Timezone/TimezoneHelper.cs, test/Abp.Tests/Timing/TimezoneHelper_Tests.cs
Given a datetime and timezone, these methods will create a DateTimeOffset
=> TimezoneHelper Convert to DateTimeOffset methods

src/Abp/Timing/DateTimeRange.cs, src/Abp/Timing/IDateTimeRange.cs
Used for determining the timespan between StartTime and EndTime.  When set, recalculates the EndTime.
=> DateTimeRange TimeSpan

src/Abp/Timing/IZonedDateTimeRange.cs, src/Abp/Timing/ZonedDateTimeRange.cs
Provides for local times, offset times, and utc times.
=> ZonedDateTimeRange

doc/WebSite/Timing.md, doc/WebSite/Unit-Of-Work.md
Sorry about having 2 docs here... I forgot I already checked something in. 😅
=> Timing.md and Unit-Of-Work.md document changes

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
=> Set null for property if entity created or deleted

src/Abp/Application/Features/Feature.cs
There's a whole other aspect of documentation.  I suppose it's good to start somewhere.
=> Feature.cs documentation changes and light refactoring

doc/WebSite/SignalR-AspNetCore-Integration.md
Related topic: https://forum.aspnetboilerplate.com/viewtopic.php?p=26651
=> Add client-side (Angular) instructions for SignalR

doc/WebSite/EF-Core-PostgreSql-Integration.md
- Improve grammar
- Improve formatting
=> EF-Core-PostgreSql-Integration.md document changes

src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs
=> Change AbpRoleManager accessor properties from private to protected

doc/WebSite/Zero/Tenant-Management.md
=> Tenant-Management.md document changes

doc/README.md
I believe this is the last ABP document that needed a change.
Let me know if I missed any other docs.
Cheers!
=> README.md document changes

src/Abp.AspNetCore/AspNetCore/Mvc/Conventions/AbpAppServiceConvention.cs
=> Check if RemoteService is enabled for ActionMethod

doc/WebSite/Articles/Running-in-Docker-Containers-and-Building-a-Web-Farm-Load-Balancer-Scenario/index.html
=> (doc) Corrected Typo

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
As mentioned in aspnetboilerplate/module-zero-core-template#203, changes should be made in the upstream
=> Remove ES6 Code for signalr-client.js

src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs
Fixes #3246
This reverts commit 5d0cabaef89f469fd51bf38de0a1cb393330ed56.
=> Revert "Switch IsGrantedAsync(user) and IsGrantedAsync(userId)"

test/Abp.Quartz.Tests/Abp.Quartz.Tests.csproj, test/Abp.Quartz.Tests/Abp.Quartz.Tests.xunit.runner.json
The "parallelizeTestCollections" should be setted to false or QuartzTests.cs will fail on Appveyor.
=> Fix test case failing on Appveyor

src/Abp.AspNetCore.SignalR/Abp.AspNetCore.SignalR.csproj, src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
=> Updated Microsoft.AspNetCore.SignalR version

src/Abp/Domain/Repositories/AbpRepositoryBase.cs
This change helps inherit Repository of entity with surrogat Id and composit primary key in DataBase Table
=> Make virtual CreateExpressionForEntityID function

src/Abp.AspNetCore/AspNetCore/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs
Resolves #3124 
See https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3124#issuecomment-389219270.
=> Add workaround for exception from GetDisplayUrl

src/Abp/BackgroundJobs/InMemoryBackgroundJobStore.cs
=> Swap Dictionary with ConcurrentDictionary in InMemoryBackgroundJobStore

src/Abp/Localization/LocalizableStringExtensions.cs
Fixes #3505 
Taking reference from [LocalizableStringToStringJsonConverter](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Localization/LocalizableStringToStringJsonConverter.cs#L22).
Added  the followings:
- `Localize(ILocalizableString, ILocalizationManager)`
- `Localize(ILocalizableString, ILocalizationManager, CultureInfo)`
=> ILocalizableString extensions with LocalizationManager

src/Abp.Castle.Log4Net/Castle/Logging/Log4Net/Log4NetLoggerFactory.cs
#3552 add reloadOnChange for Log4NetLoggerFactory
=> #3552 add reloadOnChange for Log4NetLoggerFactory

src/Abp.Zero.Common/Auditing/AuditLog.cs
Enhancement #3560 Make audit exceptions more explicit.
=> Enhancement #3560 Make audit exceptions more explicit.

doc/WebSite/Articles/Developing-MultiTenant-SaaS-ASP.NET-CORE-Angular/index.html
=> Use single quotes for Angular imports

doc/WebSite/SignalR-AspNetCore-Integration.md, src/Abp.AspNetCore.SignalR/Properties/AssemblyInfo.cs
=>  Change namespace from Abp.Web.SignalR to Abp.AspNetCore.SignalR

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
=> Fix SignalR-Client.js query string concatenation

src/Abp.Web.Api.OData/Abp.Web.Api.OData.csproj, src/Abp/Abp.csproj, test/Abp.EntityFrameworkCore.Tests/Abp.EntityFrameworkCore.Tests.csproj, test/aspnet-mvc-demo/AbpAspNetMvcDemo/AbpAspNetMvcDemo.csproj, test/aspnet-mvc-demo/AbpAspNetMvcDemo/Web.config, test/aspnet-mvc-demo/AbpAspNetMvcDemo/packages.config
Fixes #3609 - Mvc 5x demo abp references
=> Package updates

src/Abp.Zero.Ldap/Ldap/Authentication/LdapAuthenticationSource.cs
=> Abp Zero Ldap UserName might be null

doc/WebSite/Validating-Data-Transfer-Objects.md
@hikalkan @ogix could you check the explanation if there is something missing/wrong or not clear ?
=> Fixes #3659: Added basic Abp.FluentValidation documentation

doc/WebSite/Application-Services.md, doc/WebSite/Articles/Introduction-With-AspNet-Core-And-Entity-Framework-Core-Part-1/index.html, doc/WebSite/Articles/Introduction-With-AspNet-Core-And-Entity-Framework-Core-Part-2/index.html, src/Abp.Zero.Common/Application/Features/FeatureSetting.cs, src/Abp.Zero.Common/Authorization/PermissionSetting.cs, src/Abp.Zero.Common/Authorization/Users/AbpUserBase.cs, src/Abp.Zero.Common/Authorization/Users/UserLogin.cs, src/Abp.Zero.Common/Authorization/Users/UserLoginAttempt.cs, src/Abp.Zero.Common/Configuration/Setting.cs, src/Abp/BackgroundJobs/BackgroundJobInfo.cs, src/Abp/EntityHistory/EntityChange.cs, src/Abp/EntityHistory/EntityChangeSet.cs, src/Abp/EntityHistory/EntityPropertyChange.cs, src/Abp/Notifications/NotificationInfo.cs, src/Abp/Notifications/NotificationSubscriptionInfo.cs, src/Abp/Notifications/TenantNotificationInfo.cs, test/Abp.TestBase.SampleApplication/People/Dto/CreatePersonInput.cs, test/Abp.TestBase.SampleApplication/People/Person.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Application/Dtos/ProductCreateInput.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Domain/Product.cs
=> Addresses #3688

doc/WebSite/Unit-Of-Work.md
Fixed unit of work restriction section dom element id
=> Update unit of work restriction section navigation

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, src/Abp.ZeroCore/Authorization/Users/UserToken.cs, test/Abp.ZeroCore.SampleApp/Core/_Service_Overrides.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_Tokens_Tests.cs
Added following methods to AbpUserManager and AbpUserStore
```c#
public virtual async Task AddTokenValidityKeyAsync(
TUser user,
string tokenValidityKey,
DateTime expireDate,
CancellationToken cancellationToken = default(CancellationToken))
{
await AbpUserStore.AddTokenValidityKeyAsync(user, tokenValidityKey, expireDate, cancellationToken);
}
public virtual async Task<bool> IsTokenValidityKeyValidAsync(
TUser user,
string tokenValidityKey,
CancellationToken cancellationToken = default(CancellationToken))
{
return await AbpUserStore.IsTokenValidityKeyValidAsync(user, tokenValidityKey, cancellationToken);
}
```
=> Validity token

doc/WebSite/Module-System.md, doc/WebSite/Plugin.md
Also:
- Correct spellings
- Improve grammar and formatting in docs
=> Add link to Plugin.md

doc/WebSite/Introduction.md
Just a little typo I found. I'm not even sure if it's worth a pull request, but here it is! 😀
=> fixed typo

src/Abp.ZeroCore.IdentityServer4/IdentityServer4/AbpProfileService.cs
=> AbpProfileService.IsActiveAsync doesn't check if the user is Active

doc/WebSite/Zero/Identity-Server.md
=>  Remove outdated notice about IdentityServer4.AccessTokenValidation package

doc/WebSite/Notification-System.md
Frendship instead of Friendship
=>  spelling mistake

src/Abp.AspNetCore.OData/AspNetCore/OData/Configuration/AbpAspNetCoreODataModuleConfiguration.cs, src/Abp.AspNetCore.OData/AspNetCore/OData/Controllers/AbpODataEntityController.cs
PR merged with mention: #2872
Fix proposed: https://github.com/aspnetboilerplate/sample-odata/issues/9
Also removed workaround that is no longer necessary.
=> Fix model binding for OData Patch, Post, Put

src/Abp.Zero.Common/Authorization/Users/AbpUserBase.cs
We have production issue with Indian name being longer than 32 characters.
=> Increase limits for Name and Surname fields to 64 letters.

src/Abp.AspNetCore/Json/AbpMvcContractResolver.cs
Proposal to solve the issue #3703
=> Resolving issue #3703

src/Abp.NHibernate/NHibernate/AbpNHibernateModule.cs, src/Abp.NHibernate/NHibernate/EntityMappings/EntityMapOfTEntityAndTPrimaryKey.cs, src/Abp.NHibernate/NHibernate/Filters/MayHaveTenantFilter.cs, src/Abp.NHibernate/NHibernate/Filters/MustHaveTenantFilter.cs, src/Abp.NHibernate/NHibernate/Filters/SoftDeleteFilter.cs, src/Abp.NHibernate/NHibernate/Interceptors/AbpNHibernateInterceptor.cs, src/Abp.NHibernate/NHibernate/Repositories/NhRepositoryBaseOfTEntityAndTPrimaryKey.cs, src/Abp.NHibernate/NHibernate/Uow/NhUnitOfWork.cs, src/Abp/Domain/Uow/AbpDataFilters.cs, test/Abp.NHibernate.Tests/Basic_Repository_Tests.cs
Currently failing on `Should_Filter_SoftDelete`
=> Attempt to address #1046

src/Abp.AspNetCore/Abp.AspNetCore.csproj, src/Abp.AspNetCore/AspNetCore/Mvc/Antiforgery/AbpAutoValidateAntiforgeryTokenAuthorizationFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Antiforgery/AbpValidateAntiforgeryTokenAuthorizationFilter.cs, src/Abp.Web.Api/Web/Security/AntiForgery/AbpAntiForgeryManagerWebApiExtensions.cs, src/Abp.Web.Common/Web/Security/AntiForgery/AbpAntiForgeryConfiguration.cs, src/Abp.Web.Common/Web/Security/AntiForgery/IAbpAntiForgeryConfiguration.cs, src/Abp.Web.Mvc/Web/Security/AntiForgery/AbpAntiForgeryManagerMvcExtensions.cs
=> Always perform anti forgery validation when auth cookie exists

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.jtable.js
A minor fix for managing list methods that returns a list of items instead of only IPagedResult or IListResult
=> Improved the list action adapter

src/Abp/Json/JsonExtensions.cs
Base on discussion on https://github.com/aspnetboilerplate/aspnetboilerplate/pull/3848
I would suggest to overload `ToJsonString()` with `JsonSerializerSettings` as there are many ways to customise the settings for serializer.
=> ToJsonString() with serializer settings

src/Abp/Dependency/IocManager.cs
=> Allow IocContainer creation overridable in IocManager

src/Abp/Auditing/AuditingConfiguration.cs, src/Abp/Auditing/AuditingHelper.cs, src/Abp/Auditing/IAuditingConfiguration.cs, test/Abp.AspNetCore.Tests/Tests/AuditLogTests.cs
=> Create an option to save audit logs in background thread

src/Abp/Domain/Repositories/RepositoryExtensions.cs, test/Abp.TestBase.SampleApplication.Tests/People/PersonRepository_SoftDelete_Tests.cs, test/Abp.Zero.SampleApp.Tests/Repository/Repository_Hard_Delete_Test.cs, test/Abp.ZeroCore.Tests/Zero/Repository/Repository_Hard_Delete_Test.cs
=> Added hard delete method for deleting multiple entities and created async versions

src/Abp.NHibernate/Abp.NHibernate.csproj
fixing the correct output folder for this project.
=> fix release output folder for Abp.NHibernate

src/Abp.AspNetCore/AspNetCore/Mvc/Controllers/AbpScriptsController.cs, src/Abp.Web.Common/Web/Configuration/CustomConfigScriptManager.cs, src/Abp.Web.Common/Web/Configuration/ICustomConfigScriptManager.cs, test/Abp.Web.Common.Tests/Configuration/AbpUserConfigurationBuilder_Tests.cs, test/Abp.Web.Common.Tests/Configuration/CustomConfigScriptManager_Tests.cs
=> Return customConfig in AbpScriptsController

doc/WebSite/Logging.md
Provided extra information about how to change log4Net configuration on runtime.
=> Added code sample

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-zh-Hans.xml, src/Abp.Zero.Common/Zero/Localization/Source/AbpZero-zh-Hans.xml, src/Abp.Zero/Zero/Localization/SourceExt/AbpZero-zh-Hans.xml
fixes #4014: Improve Chinese localization resources
=> fixes #4014: Improve Chinese localization resources

src/Abp/AbpKernelModule.cs, src/Abp/Notifications/DefaultNotificationDistributer.cs, src/Abp/Notifications/INotificationConfiguration.cs, src/Abp/Notifications/NotificationConfiguration.cs, src/Abp/Notifications/NotificationDistributionJob.cs, src/Abp/Notifications/NotificationPublisher.cs, test/Abp.Tests/Notifications/NotificationPublisher_Tests.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestModule.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/FakeNotificationDistributer.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/NotificationDistributer_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/NullNotificationDistributer.cs
=> Support multiple notification distributors

src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Extensions/EntityEntryExtensions.cs, test/Abp.ZeroCore.Tests/Zero/EntityChangeTracker/EntityChange_Test.cs
fix #4072 Check if the entity and its associated Owned entity have changed.
=> fix #4072 Check if the entity and its associated Owned entity have changed.

src/Abp/AbpKernelModule.cs, src/Abp/BackgroundJobs/AsyncBackgroundJob.cs, src/Abp/BackgroundJobs/BackgroundJobManagerEventTriggerExtensions.cs, src/Abp/BackgroundJobs/EventTriggerAsyncBackgroundJob.cs, test/Abp.ZeroCore.Tests/Zero/BackgroundJobs/BackgroundJobManagerEventTriggerExtensions_Tests.cs
=> background event job

src/Abp.Zero.Common/Authorization/Users/AbpUserBase.cs, src/Abp.Zero.Common/Authorization/Users/UserAccount.cs, src/Abp.Zero.Common/Authorization/Users/UserAccountSynchronizer.cs, src/Abp.Zero.NHibernate/Zero/NHibernate/EntityMappings/AbpUserMap.cs, src/Abp.Zero/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/AbpLoginManager.cs, test/Abp.Zero.SampleApp.NHibernateTests/NHibernate/Mappings/UserAccountMap.cs, test/Abp.Zero.SampleApp.Tests/Users/UserAccountSynchronizer_Tests.cs, test/Abp.Zero.SampleApp/Users/UserAppService.cs
=> Removed LastLoginTime from AbpUserBase and UserAccount

src/Abp/Configuration/SettingManager.cs, test/Abp.Tests/Configuration/SettingManager_Tests.cs
=> Save app level setting as tenant when multi tenancy is disabled

Abp.sln, src/Abp.AspNetCore/AspNetCore/Mvc/AbpMvcOptionsExtensions.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/AbpAuditPageFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Extensions/PageHandlerExecutingContextExtensions.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Uow/AbpUowPageFilter.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/AbpAspNetCoreDemo.IntegrationTests.csproj, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/CustomWebApplicationFactory.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Properties/launchSettings.json, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorAuditPageFilterTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorUowPageFilterTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/log4net.config, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemo.csproj, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo.cshtml.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo2.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo2.cshtml.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo3.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo3.cshtml.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/UowFilterPageDemo.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/UowFilterPageDemo.cshtml.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/UowFilterPageDemo2.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/UowFilterPageDemo2.cshtml.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Program.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/web.config
UnitOfWork and Audit filters are implemented
Resolves #2464
=> Implemented razor page filters

src/Abp.Zero.Common/Authorization/Users/UserRole.cs, src/Abp.ZeroCore/Authorization/Roles/AbpRole.cs, src/Abp.ZeroCore/Authorization/Users/AbpUser.cs, src/Abp.ZeroCore/Authorization/Users/UserToken.cs, src/Abp/Notifications/UserNotificationInfo.cs
for use Nhibernate ORM,Entity's member(public/protected) must have virtual Access Modifiers
=> add 'virtual' Access Modifiers to Entity's member of public.

src/Abp.Zero.NHibernate/Zero/NHibernate/EntityMappings/AbpUserMap.cs, src/Abp.Zero/Authorization/AbpLoginManager.cs, src/Abp.Zero/Authorization/Roles/AbpRole.cs, src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs, src/Abp.Zero/Authorization/Roles/AbpRoleStore.cs, src/Abp.Zero/Authorization/Users/AbpUser.cs, src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.Zero/Authorization/Users/AbpUserStore.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, test/Abp.Zero.SampleApp.NHibernateTests/NHibernate/TestDatas/InitialUsersBuilder.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialUsersBuilder.cs, test/Abp.Zero.SampleApp.Tests/Users/UserLoginHelper.cs, test/Abp.Zero.SampleApp.Tests/Users/UserLogin_ExternalAuthenticationSources_Test.cs, test/Abp.Zero.SampleApp.Tests/Users/UserRepository_Tests.cs, test/Abp.Zero.SampleApp.Tests/Users/UserRole_Tests.cs, test/Abp.Zero.SampleApp/Users/UserAppService.cs
Fixes #4130 
* Added NormalizedUserName and NormalizedEmailAddress to AbpUser
* Added NormalizedName to AbpRole
=> Abp.Zero Identity key normalization

src/Abp/Auditing/AuditInfo.cs, src/Abp/Auditing/AuditingConfiguration.cs, src/Abp/Auditing/AuditingInterceptor.cs, src/Abp/Auditing/IAuditingConfiguration.cs, src/Abp/Threading/InternalAsyncHelper.cs, test/Abp.TestBase.SampleApplication.Tests/Auditing/SimpleAuditing_Test.cs
AuditInfo add records returnvalue i think will make the audit record more complete
=> AuditInfo add record returnvalue

src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_AddToRole_Tests.cs
About https://github.com/aspnetboilerplate/module-zero-core-template/issues/407
=> UserStore's AddToRoleAsync method ensure to load Roles.

src/Abp.Zero/Authorization/Users/AbpUserStore.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs
Query userRoles and userOrganizationUnitRoles in advance in the GetRolesAsync method of AbpUserStore.
=> fix #4284 Query userRoles and userOrganizationUnitRoles in advance in the GetRolesAsync method of AbpUserStore.

doc/WebSite/Value-Objects.md, src/Abp/Domain/Values/ValueObject.cs, test/Abp.Tests/Domain/Values/Address.cs, test/Abp.Tests/Domain/Values/ValueObject_Simple_Tests.cs
=> ValueObject alternative implementation

Abp.sln, doc/WebSite/Entity-Framework-Core.md, nupkg/pack.ps1, src/Abp.EntityFrameworkCore.EFPlus/Abp.EntityFrameworkCore.EFPlus.csproj, src/Abp.EntityFrameworkCore.EFPlus/EntityFrameworkCore/EFPlus/AbpEntityFrameworkCoreEFPlusExtensions.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs, src/Abp/Linq/Expressions/ExpressionCombiner.cs, src/Abp/Properties/AssemblyInfo.cs, test/Abp.EntityFrameworkCore.EFPlus.Tests/Abp.EntityFrameworkCore.EFPlus.Tests.csproj, test/Abp.ZeroCore.Tests/Abp.ZeroCore.Tests.csproj, test/Abp.ZeroCore.Tests/Zero/EFPlus/AbpEntityFrameworkCoreEfPlusExtensions_Tests.cs
=> EFPlus integration for EF Core

doc/WebSite/Data-Filters.md
We should include link to ef core custom data filter article in the main document for data filter.
=> Add EF core custom into data filter doc

doc/WebSite/Zero/Identity-Server.md
SORRY
This page does not exist yet. 
http://docs.identityserver.io/en/release/topics/apis.html?highlight=UseIdentityServerAuthentication#the-identityserver-authentication-middleware
=> Fix URL about the documentation of Middleware

src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs, src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs, test/Abp.Zero.SampleApp.Tests/Roles/OrganizationUnitRole_Tests.cs, test/Abp.Zero.SampleApp.Tests/Roles/RoleOrganizationUnit_Tests.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialOrganizationUnitRolesBuilder.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialRolesBuilder.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestDataBuilder.cs, test/Abp.Zero.SampleApp/Roles/RoleManager.cs, test/Abp.ZeroCore.SampleApp/Core/_Service_Overrides.cs
=> Organization unit operations

doc/WebSite/SignalR-Integration.md
Resolves [https://stackoverflow.com/questions/54942564/unable-to-send-real-time-notifications-saved-in-database](https://stackoverflow.com/q/54942564/8601760)
Code was fixed in [aspnetboilerplate/module-zero-template@`0f02631`](https://github.com/aspnetboilerplate/module-zero-template/commit/0f0263162aed9869d5bb0dcb4e2843ab09180d2d#diff-4fcbcf513d2ccd11ab19be777a3d00ae) on Feb 17, 2016.
=> Move app.MapSignalR to end of Configuration method

src/Abp.Web.Common/Web/Authorization/AuthorizationScriptManager.cs, src/Abp.Web.Common/Web/Features/FeaturesScriptManager.cs, src/Abp.Web.Common/Web/Localization/LocalizationScriptManager.cs, src/Abp.Web.Common/Web/Navigation/NavigationScriptManager.cs, src/Abp.Web.Common/Web/Settings/SettingScriptManager.cs
I added the escaping that can be added. Maybe some are redundant.
=> fix #4340 Escaped generated JavaScript.

src/Abp/Application/Features/FeatureChecker.cs, src/Abp/Application/Features/FeatureCheckerExtensions.cs, src/Abp/Localization/Sources/AbpXmlSource/Abp-ar.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-ca-ES.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-de.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-es.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-fa.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-fr.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-it.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-lt.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-lv.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-pt-BR.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-ru.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-tr.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-uk.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-zh-Hans.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp.xml
=> fix #4365 FeatureCheckerExtensions localization exception message.

src/Abp.AspNetCore.OData/AspNetCore/OData/Controllers/AbpODataController.cs, src/Abp.AspNetCore.OData/AspNetCore/OData/Controllers/AbpODataEntityController.cs, src/Abp.Web.Api.OData/WebApi/OData/Controllers/AbpODataController.cs, src/Abp.Web.Api.OData/WebApi/OData/Controllers/AbpODataEntityController.cs, src/Abp/Application/Services/CrudAppService.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Domain/Product.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/AbpAspNetCoreDemo.IntegrationTests.csproj, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/AbpODataEntityControllerTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemo.csproj, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemoModule.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Controllers/ProductsController.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Db/MyDbContext.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Db/MyDbContextFactory.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
=> AbpODataEntityController and Permission

src/Abp.Zero.EntityFramework/EntityHistory/Extensions/DbPropertyEntryExtensions.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestBlogBuilder.cs, test/Abp.Zero.SampleApp/EntityHistory/Blog.cs
=> Fix Ef6 entity history property change for null values

src/Abp.Web.Common/Web/Localization/LocalizationScriptManager.cs
for https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4345#issuecomment-483566174
`ToJsonString` method will handle special characters within json.
=> Remove the encoding of localized content.

src/Abp/Abp.csproj, src/Abp/Timing/Timezone/Mapping/WindowsZones.xml, test/Abp.Tests/Abp.Tests.csproj, test/Abp.Tests/Timing/TimezoneHelper_Tests.cs, test/Abp.Web.Common.Tests/Abp.Web.Common.Tests.csproj
https://github.com/mj1856/TimeZoneConverter/issues/45
=> Add timezone mapping for Qyzylorda Standard Time

doc/WebSite/Notification-System.md, doc/WebSite/SignalR-AspNetCore-Integration.md
Resolves #4432 
Also removed preview notice for SignalR AspNetCore Integration, since it's no longer in preview.
=> Add documentation for multiple notification notifiers

src/Abp.Zero.Common/Authorization/Roles/AbpRolePermissionCacheItemInvalidator.cs, src/Abp.Zero.Common/Authorization/Users/AbpUserPermissionCacheItemInvalidator.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_AddToRole_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_Permission_Tests.cs
=> Fix user role permission cache

src/Abp/UserIdentifier.cs, test/Abp.Tests/UserIdentifier_Tests.cs
=> Prevent UserIdentifier's GetHashCode method from colliding:

src/Abp.Castle.Log4Net/Castle/Logging/Log4Net/Log4NetLogger.cs, src/Abp.Web.Common/Abp.Web.Common.csproj, src/Abp.Web/Abp.Web.csproj, src/Abp/Abp.csproj, src/Abp/Dependency/IocManager.cs, test/aspnet-mvc-demo/AbpAspNetMvcDemo/AbpAspNetMvcDemo.csproj, test/aspnet-mvc-demo/AbpAspNetMvcDemo/packages.config
- `ILogger `interface added trace log level in version 4.4. https://github.com/castleproject/Core/commit/32e788c6a1d15dad22b83970ca1baf6552dac2f6#diff-d39fdd8cc7683334a1296f614c93a17cR33
- Built-in System.Web support has been moved to the new` Castle.Facilities.AspNet.SystemWeb` facility 
- `IWindsorContainer `removed `Resolve<T>(object argumentsAsAnonymousType)`related methods.https://github.com/castleproject/Windsor/pull/444/files#diff-12a11f3cb4d39de62dfa673296a24343L386
=> Upgrade Castle related packages.

src/Abp.Zero.Common/MultiTenancy/TenantCache.cs
determining current tenant from top domain.
need to override HandleEvent to delete cache, so you need to change TenantCache.HandleEvent to virtual method
```
public class CustomTopDomainTenantResolveContributor : ITenantResolveContributor, ITransientDependency
{
private readonly IHttpContextAccessor _httpContextAccessor;
private readonly ITenantStore _tenantStore;
public StalkerDomainTenantResolveContributor(
IHttpContextAccessor httpContextAccessor,
ITenantStore tenantStore)
{
_httpContextAccessor = httpContextAccessor;
_tenantStore = tenantStore;
}
public int? ResolveTenantId()
{
var httpContext = _httpContextAccessor.HttpContext;
if (httpContext == null)
{
return null;
}
var domain = httpContext.Request.Host.Host.RemovePreFix("http://", "https://").RemovePostFix("/").Split(":")[0];
var …
```
=> change TenantCache.HandleEvent to virtual method

src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs
=> Remove ef core query filter workaround

src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_RemoveFromRole_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_SetRoles_Tests.cs
At the same time solve the issue of https://github.com/aspnetzero/aspnet-zero-core/issues/2418
https://github.com/aspnetboilerplate/aspnetboilerplate/compare/maliming/issue4556?expand=1#diff-c33505115cf7622ed00b553304e3c516R417
=> fix #4556 Exclude soft deleted roles when removing user roles.

src/Abp.EntityFrameworkCore/EntityFrameworkCore/EfCoreDbContextEntityFinder.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Repositories/EfCoreRepositoryBaseOfTEntityAndTPrimaryKey.cs, test/Abp.EntityFrameworkCore.Tests/Domain/BlogView.cs, test/Abp.EntityFrameworkCore.Tests/Ef/BloggingDbContext.cs, test/Abp.EntityFrameworkCore.Tests/EntityFrameworkCoreTestModule.cs, test/Abp.EntityFrameworkCore.Tests/Tests/DbQuery_Tests.cs
=> EF Core Repository Support for DbQuery.

src/Abp.Web/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs, test/Abp.Web.Tests/EntityHistory/EntityHistory_Reason_Tests.cs
=> Abp web entity history reason

doc/WebSite/Caching.md, src/Abp/Domain/Entities/Caching/EntityCache.cs, src/Abp/Domain/Entities/Caching/EntityCacheBase.cs, src/Abp/Domain/Entities/Caching/IEntityCache.cs, src/Abp/Domain/Entities/Caching/IEntityCacheBase.cs, src/Abp/Domain/Entities/Caching/IMultiTenancyEntityCache.cs, src/Abp/Domain/Entities/Caching/MayHaveTenantEntityCache.cs, src/Abp/Domain/Entities/Caching/MultiTenancyEntityCache.cs, src/Abp/Domain/Entities/Caching/MustHaveTenantEntityCache.cs, test/Abp.TestBase.SampleApplication.Tests/ContactLists/ContactList_EfExplicitLoad.cs, test/Abp.TestBase.SampleApplication.Tests/ContactLists/ContactList_MultiTenancy_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/Domain/Entities/Caching/MultiTenancyEntityCache_Invalidation_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/EntityFramework/GraphDiff/GraphDiffExtensions_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/Features/FeatureSystem_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/People/PersonAppService_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/Reflection/ProxyHelper_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/SampleApplicationTestBase.cs, test/Abp.TestBase.SampleApplication/ContactLists/ContactList.cs, test/Abp.TestBase.SampleApplication/ContactLists/ContactListAppService.cs, test/Abp.TestBase.SampleApplication/ContactLists/ContactListDto.cs, test/Abp.TestBase.SampleApplication/ContactLists/IContactListAppService.cs, test/Abp.TestBase.SampleApplication/ContactLists/SampleFeatureProvider.cs, test/Abp.TestBase.SampleApplication/EntityFramework/SampleApplicationDbContext.cs, test/Abp.TestBase.SampleApplication/People/Person.cs, test/Abp.TestBase.SampleApplication/SampleApplicationModule.cs
Resolves #4416 
Using similar concept in https://github.com/aspnetboilerplate/aspnetboilerplate/blob/0ee3e0b46fdfc21ea338e1dd88bed35e1d54a90e/src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs#L612-L613
QA: Code should be self-explanatory if going through commit by commit
=> Multi tenancy entity cache

src/Abp/Runtime/Caching/AbpCacheData.cs
=> AbpCacheData "Could not load file or assembly" error resolved

src/Abp.Zero/Authorization/Users/AbpUserManager.cs, test/Abp.Zero.SampleApp.Tests/Users/UserOrganizationUnit_Tests.cs
=> resolves #4660 

src/Abp.Zero.Common/Application/Features/AbpFeatureValueStore.cs, test/Abp.Zero.SampleApp.Tests/MultiTenancy/TenantManager_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Tenants/TenantManagerTests.cs
=> The AbpFeatureValueStore should handle the EntityChangingEvent to invalidate the cache in time.

test/Abp.RedisCache.Tests/DefaultRedisCacheSerializer_Tests.cs, test/Abp.Tests/Runtime/Caching/AbpCacheData_Tests.cs
resolves https://github.com/aspnetboilerplate/aspnetboilerplate/commit/fc212bde0b7a1803e9ec32c7b0de6704ac8d4cf4#commitcomment-34149402 error.
=> redis cache serialize test cases multiple dll error fix

src/Abp/Authorization/IPermissionDefinitionContext.cs, src/Abp/Authorization/Permission.cs, src/Abp/Authorization/PermissionDefinitionContextBase.cs, test/Abp.Tests/Authorization/PermissionDefinitionTests.cs
=> Custom properties added to Permission.cs

src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheManager.cs, src/Abp/Runtime/Caching/CacheManagerBase.cs, src/Abp/Runtime/Caching/Memory/AbpMemoryCacheManager.cs, test/Abp.Tests/Configuration/SettingManager_Tests.cs
IIocManager dependency moved to the derived classes.
Resolves #3699
=> CacheManagerBase IIocManager dependency moved to the derived classes.

src/Abp.AutoMapper/AutoMapper/AutoMapExtensions.cs
=> use normal grammar

src/Abp/AbpKernelModule.cs, src/Abp/BackgroundJobs/BackgroundJobManagerEventTriggerExtensions.cs, src/Abp/BackgroundJobs/EventTriggerAsyncBackgroundJob.cs
- Remove unnecessary `EventTriggerAsyncBackgroundJob` registration in `AbpKernelModule`
- Renamed `TEvent` with `TEventData`
=> Refactor event trigger async background job

doc/WebSite/Zero/Startup-Template-Core.md
Fixed a typo: from "Context-Type" to "Content-Type":
Content-Type="application/json"
=> Minor fix (typos) to Startup-Template-Core.md

src/Abp/Domain/Repositories/AbpRepositoryBase.cs
Choose calling asynchronous operations instead of synchronous ones
From PR #4765
=> Refactor AbpRepositoryBase async operations

src/Abp.AutoMapper/AutoMapper/AutoMapperObjectMapper.cs, src/Abp/ObjectMapping/IObjectMapper.cs, src/Abp/ObjectMapping/NullObjectMapper.cs
=> IObjectMapper adding ProjectTo function.

src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/AbpAuditActionFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/AbpAuditPageFilter.cs, src/Abp.Web.Api/WebApi/Auditing/AbpApiAuditFilter.cs, src/Abp.Web.Mvc/Web/Mvc/Auditing/AbpMvcAuditFilter.cs, test/Abp.AspNetCore.Tests/App/Controllers/SimpleTestController.cs, test/Abp.AspNetCore.Tests/Tests/AuditLogTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorAuditPageFilterTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemoModule.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo5.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/AuditFilterPageDemo5.cshtml.cs
=> Set the return value in the web audit filter

test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/EntityHistory/Blog.cs, test/Abp.Zero.SampleApp/EntityHistory/Category.cs, test/Abp.Zero.SampleApp/EntityHistory/Post.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Category.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Post.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
=> fix entity history invalid entity test

test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestBlogBuilder.cs, test/Abp.Zero.SampleApp/EntityHistory/Advertisment.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Advertisment.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Fix tests after changes in #4843 #4870
=> fix entity history property without audited attribute test

src/Abp.Web/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs, src/Abp.Web/Web/MultiTenancy/HttpCookieTenantResolveContributor.cs
=> Handles exceptions that may occur with HttpContext.Current?.Request.

src/Abp/Domain/Entities/Entity.cs, src/Abp/Domain/Values/ValueObject.cs, test/Abp.Tests/Domain/Entities/Test_Entities.cs, test/Abp.Tests/Domain/Values/ValueObject_Simple_Tests.cs
=> remove overrided equality methods

src/Abp.Web/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs, src/Abp.Web/Web/MultiTenancy/HttpCookieTenantResolveContributor.cs
Follow up https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4930#issuecomment-543432646
- removed exception handling in tenant resolver
- catch `HttpException` explicitly.
=> Refactor HttpContext.Request exception handling

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
Resolve #4934
should include in 4.x and 5.x releases
=> entity history logging

test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Increase test coverage for entity history feature
=> entity history selectors and ignored types tests

src/Abp.AspNetCore/AspNetCore/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs
=> Use the aspnet core built-in GetDisplayUrl method.

src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroDbModelBuilderExtensions.cs
=> Cancel the table name for the derived type.

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
=> Fix entity history selectors configuration

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/TPH/Person.cs, test/Abp.Zero.SampleApp/TPH/Student.cs, test/Abp.Zero.SampleApp/TPH/Teacher.cs
=> EntityHistoryHelper is compatible with TPH entities

src/Abp.ZeroCore/Authorization/Users/UserTokenExpirationWorker.cs, src/Abp.ZeroCore/Zero/AbpZeroCoreModule.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserTokenExpirationWorker_Tests.cs
=> Disable the tenant filter when deleting expired tokens.

src/Abp.ZeroCore/Authorization/Users/UserTokenExpirationWorker.cs, src/Abp.ZeroCore/Zero/AbpZeroCoreModule.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserTokenExpirationWorker_Tests.cs
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4958 for 4.x
=> Disable tenant filter for User token expiration

src/Abp.AspNetCore/AspNetCore/Mvc/ModelBinding/AbpDateTimeModelBinderProvider.cs, test/Abp.AspNetCore.Tests/App/Controllers/SimpleTestController.cs, test/Abp.AspNetCore.Tests/Tests/DateTimeModelBinder_Tests.cs
=> Normalize simple types of DateTime(asp net core 2.x)

test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/TPH/CitizenshipInformation.cs, test/Abp.Zero.SampleApp/TPH/Student.cs, test/Abp.Zero.SampleApp/TPH/StudentLectureNote.cs
Unit test for relational item changes.
Tests for one to one, one to many relationships.
resolve #5010
=> EntityHistoryHelper relational changes unit tests

src/Abp.EntityFrameworkCore.EFPlus/Abp.EntityFrameworkCore.EFPlus.csproj
=> Upgrade the Z.EntityFramework.Plus.EFCore package(EF Core 3.x)

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
=> Remove debug logging in entity change creation

src/Abp.Quartz/Quartz/IQuartzScheduleJobManager.cs, src/Abp.Quartz/Quartz/QuartzScheduleJobManager.cs, test/Abp.Quartz.Tests/QuartzTests.cs
=> Add reschedule/unschedule to Quartz Schedule Job Manager

src/Abp.Zero.Common/Configuration/Setting.cs
resolves https://github.com/aspnetzero/aspnet-zero-core/issues/2774
=> Remove limitation on AppSettings table value column

src/Abp.Zero.Common/Authorization/Users/UserLoginAttempt.cs
Resolve #5000
Also need to update the migration of the template.
=> Update the length of the UserNameOrEmailAddress property of UserLoginAttempt.

src/Abp/Domain/Entities/EntityExtensions.cs, src/Abp/Extensions/StringExtensions.cs
=> Add [ContractAnnotation] for null check.

test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/TPH/CitizenshipInformation.cs, test/Abp.Zero.SampleApp/TPH/Student.cs, test/Abp.Zero.SampleApp/TPH/StudentLectureNote.cs
Just cherry-pick of pr https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5020 for 5.x
=> EntityHistoryHelper relational changes unit tests for 5.1

src/Abp.Web/Web/Localization/CurrentCultureSetter.cs
Remade the PR to the 4x branch
Untested, but should work. Simple logic switch.
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5117
=> Swap the logic between getting app default and browser setting

doc/WebSite/Localization.md
=> Introducing AbpLocalizationController.

src/Abp.EntityFrameworkCore.EFPlus/Abp.EntityFrameworkCore.EFPlus.csproj, src/Abp.EntityFrameworkCore.EFPlus/EntityFrameworkCore/EFPlus/AbpEntityFrameworkCoreEFPlusExtensions.cs
=> Enhance EFPlus' extension methods to support BatchDelete & BatchUpdate.

src/Abp/Extensions/ObjectExtensions.cs, test/Abp.Tests/Extensions/ObjectExtension_Test.cs
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.timespanconverter?view=netstandard-2.0
=> feat: ObjectExtentions class add Timespan support

src/Abp.Zero.Common/Zero/Configuration/StaticRoleDefinition.cs, src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs, src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs
=> Added RoleDisplayName property to StaticRoleDefinition class.

src/Abp.EntityFrameworkCore/Abp.EntityFrameworkCore.csproj
=> Change Abp.EntityFrameworkCore Package Target to .NETStandard2.0

src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs, src/Abp/Linq/IAsyncQueryableExecuter.cs, src/Abp/Linq/NullAsyncQueryableExecuter.cs
=> extend IAsyncQueryableExecuter with AnyAsync

src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
Follows https://github.com/aspnetboilerplate/aspnetboilerplate/commit/7cfde1c198026f2e102405f12a16401bc412040e
Follows https://github.com/aspnetboilerplate/bower-abp-resources/pull/21
From https://github.com/aspnetboilerplate/bower-abp-resources/pull/22#discussion_r363131920:
> Need to restore this (added directly by https://github.com/aspnetboilerplate/bower-abp-resources/pull/21) and add to ABP repo.
=> Add TypeScript declarations for refresh token

src/Abp/Authorization/PermissionManager.cs, test/Abp.Tests/Authorization/PermissionDefinitionTests.cs
cherry pick 981034dc53e52e77f809ccb7eefb722fcaad8f51
Duplicate of  https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5186 for v4.x
=> use current tenant Id in PermissionManager GetAllPermission

src/Abp/Authorization/PermissionManager.cs, test/Abp.Tests/Authorization/PermissionDefinitionTests.cs
=> use current tenant Id in PermissionManager.cs/GetAllPermission

src/Abp.AspNetCore.OData/Abp.AspNetCore.OData.csproj
=> Upgrade the Microsoft.AspNetCore.OData package to support net core 3.1.

src/Abp.ZeroCore/Authorization/Users/UserTokenExpirationWorker.cs, src/Abp/BackgroundJobs/BackgroundJobConfiguration.cs, src/Abp/BackgroundJobs/IBackgroundJobConfiguration.cs
Use `TimeSpan` to indicate the frequency for `UserTokenExpirationWorker`
=> Use TimeSpan for user token expiration frequency

doc/WebSite/Background-Jobs-And-Workers.md
Update documentation for user expiration worker after refactoring done in https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5168
=> Update user expiration worker documentation

src/Abp.Dapper/Dapper/Repositories/DapperEfRepositoryBaseOfTDbContextAndTEntity.cs, src/Abp.Dapper/Dapper/Repositories/DapperEfRepositoryBaseOfTDbContextAndTEntityAndTPrimaryKey.cs, src/Abp.Dapper/Dapper/Repositories/DapperRepositoryBaseOfTEntityAndTPrimaryKey.cs
=> Add Timeout property to dapper repository.

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-ja.xml
It needs adding to the project as an Embedded file, I think?
=> Created an AbpWeb-ja translation

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/EntityHistory/Country.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Country.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
resolves #5149 
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5149#issuecomment-567915088
=> Entity History will not always create history record for shadow property

src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs, src/Abp.Zero/Authorization/Users/AbpUserStore.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, src/Abp/Linq/IAsyncQueryableExecuter.cs
Resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5178
=> Remove sync methods usage of Async queryable executer

src/Abp.Web.Resources/Abp/Framework/scripts/abp.js
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5283
=> Related to #5283

doc/WebSite/SignalR-AspNetCore-Integration.md, doc/WebSite/SignalR-Integration.md
=> Update SignalR-Integration.md 

src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs, src/Abp.Zero/Authorization/Users/AbpUserStore.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, src/Abp/Linq/IAsyncQueryableExecuter.cs
=> Remove sync methods usage of Async queryable executer For 4.x

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Advertisement.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
=> 4.x Fix Entity History Retrieve the correct owner

src/Abp.Zero.Common/Organizations/OrganizationUnitManager.cs
Prevent get the whole children list from database, just the last one is enough.
=> Improve GetLastChild of OrganizationUnitManager

src/Abp/Runtime/Caching/AbpCacheBase.cs
=> AbpCacheBase: Use the value generated by the factory method to return items.

src/Abp.Web/Auditing/WebClientInfoProvider.cs, test/Abp.Web.Tests/Auditing/Client_Info_Provider_Tests.cs
Resolve #5365 
Using similar handling code from #4933
=> Web client info provider http exception

src/Abp/Application/Services/CrudAppServiceBase.cs, src/Abp/Authorization/PermissionCheckerExtensions.cs, src/Abp/Authorization/PermissionFinder.cs, src/Abp/BackgroundJobs/IBackgroundJob.cs, src/Abp/Configuration/SettingManagerExtensions.cs, src/Abp/Configuration/Startup/IAbpStartupConfiguration.cs, src/Abp/Dependency/IIocRegistrar.cs, src/Abp/Dependency/IocManager.cs, src/Abp/Dependency/IocRegistrarExtensions.cs, src/Abp/Dependency/IocResolverExtensions.cs, src/Abp/Events/Bus/IEventBus.cs, src/Abp/Extensions/StringExtensions.cs, src/Abp/Notifications/INotificationDefinitionManager.cs, src/Abp/Notifications/INotificationPublisher.cs, src/Abp/Notifications/INotificationStore.cs, src/Abp/Notifications/IUserNotificationManager.cs, src/Abp/Notifications/NotificationPublisher.cs, src/Abp/ObjectMapping/IObjectMapper.cs, src/Abp/RealTime/IOnlineClientStore.cs, src/Abp/Text/FormattedStringValueExtracter.cs, src/Abp/Timing/ZonedDateTimeRange.cs, src/Abp/WebHooks/DefaultWebHookPublisher.cs, src/Abp/WebHooks/NullWebhookSendAttemptStore.cs, test/Abp.Tests/Dependency/Unicode_Naming_Tests.cs, test/Abp.Tests/Domain/Entities/ExtendableObject_Tests.cs, test/Abp.Tests/Experimental/GenericMethodCallTests.cs, test/Abp.Tests/Localization/ResourceFileLocalizationSource_Tests.cs
- Remove NullRealTimeNotifiers (See https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4330)
- Remove `DefaultWebhookPublisher ` unnecessary `AbpSession` property
- Fix `NullWebhookSendAttempStore` to properly wrap return type in task
- Fix invalid xml comments
- Other code styles fix
=> Clean up intellisense warnings

src/Abp.AspNetCore/AspNetCore/Threading/HttpContextCancellationTokenProvider.cs, src/Abp.Web.Mvc/Web/Mvc/Threading/HttpContextCancellationTokenProvider.cs, src/Abp/Threading/CancellationTokenOverride.cs, src/Abp/Threading/CancellationTokenProviderBase.cs, src/Abp/Threading/ICancellationTokenProvider.cs, src/Abp/Threading/NullCancellationTokenProvider.cs, test/Abp.TestBase.SampleApplication.Tests/CancellationTokenProvider/CancellationToken_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/SampleApplicationTestBase.cs
=> Allowed to override CancellationToken for a specific call

src/Abp.EntityFramework.Common/AbpEfCoreDbContextInitializationContext.cs, src/Abp.EntityFramework.Common/IShouldInitializeDcontext.cs, src/Abp.EntityFramework/EntityFramework/AbpDbContext.cs, src/Abp.EntityFramework/EntityFramework/Uow/EfUnitOfWork.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Uow/EfCoreUnitOfWork.cs
=> Add Initialize method for the AbpDbContext(EF 3.x+)

src/Abp.Web.Mvc/Web/Mvc/Threading/HttpContextCancellationTokenProvider.cs, src/Abp/Threading/CancellationTokenProviderBase.cs
Resolve #5407
Similar code handling in #5381 and #4933
=> Mvc cancellation token provider http exception

doc/WebSite/Document-Index.md, doc/WebSite/Documents.md, doc/WebSite/ObjectComparators.md
=> Adds a document about Object Comparators

src/Abp/Webhooks/DefaultWebhookPublisher.cs, src/Abp/Webhooks/DefaultWebhookSender.cs, src/Abp/Webhooks/IWebhookPublisher.cs, src/Abp/Webhooks/WebhookSenderArgs.cs, test/Abp.Zero.SampleApp.Tests/Webhooks/DefaultWebhookSender_Tests.cs
=> Adds send exact same data option to Webhook System

src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs, test/Abp.EntityFrameworkCore.Tests/Tests/Repository_Filtering_Tests.cs
Resolve #5510
https://github.com/abpframework/abp/pull/3665
=> Restore DeleteOrphansTiming value of ChangeTracker.

src/Abp.HangFire.AspNetCore/Abp.HangFire.AspNetCore.csproj, src/Abp.HangFire/Abp.HangFire.csproj
=> Upgrade Hangfire to 1.7.11

doc/WebSite/Entities.md
Added sentence explaining how to Undelete a soft-deleted record.
=> Update Entities.md - How to undelete soft-deleted record

src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs, src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs
Prevent multiple read caches, especially when using redis.
https://support.aspnetzero.com/QA/Questions/8948
=> Enhance the performance of GetGrantedPermissionsAsync.

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-pl.xml, src/Abp.Zero.Common/Zero/Localization/Source/AbpZero-pl.xml, src/Abp.Zero.Ldap/Ldap/Localization/Source/AbpZero-pl.xml, src/Abp.Zero/Zero/Localization/SourceExt/AbpZero-pl.xml, src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero-pl.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-pl.xml
I translate messages. I hope that they will be merged.
=> add polish translations

doc/WebSite/Setting-Management.md, src/Abp/Configuration/ISettingEncryptionService.cs, src/Abp/Configuration/SettingDefinition.cs, src/Abp/Configuration/SettingEncryptionService.cs, src/Abp/Configuration/SettingManager.cs, src/Abp/Configuration/Startup/ISettingsConfiguration.cs, src/Abp/Configuration/Startup/SettingEncryptionConfiguration.cs, src/Abp/Configuration/Startup/SettingsConfiguration.cs, src/Abp/Runtime/Security/SimpleStringCipher_NetStandard.cs, test/Abp.Tests/Configuration/SettingManager_Tests.cs
=> Encrypted settings feature

src/Abp.AspNetCore/AspNetCore/Mvc/Controllers/AbpLocalizationController.cs, src/Abp.Web.Mvc/Web/Mvc/Controllers/Localization/AbpLocalizationController.cs, test/Abp.AspNetCore.Tests/Tests/AbpLocalizationController_Tests.cs
Resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5602
=> Ensure redirect local url in AbpLocalizationController

src/Abp/Configuration/SettingManager.cs, test/Abp.Tests/Configuration/SettingManager_Tests.cs
=> Filter undefined settings in the ConvertSettingInfosToDictionary method.

src/Abp/Domain/Repositories/RepositoryExtensions.cs, test/Abp.Zero.SampleApp.Tests/Repository/Repository_Hard_Delete_Test.cs, test/Abp.ZeroCore.Tests/Zero/Repository/Repository_Hard_Delete_Test.cs
https://support.aspnetzero.com/QA/Questions/9166#answer-ea7d68e0-1647-ae28-164d-39f5afd73c3f
=> Refactor the HardDelete function to ensure that there is a unit of work in the current context.

src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Notifications/SignalRRealTimeNotifier.cs, src/Abp.Web.SignalR/Web/SignalR/Notifications/SignalRRealTimeNotifier.cs
=> Use await in the SendNotificationsAsync method.

src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/AbpCommonHub.cs, src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/OnlineClientHubBase.cs, src/Abp.AspNetCore.SignalR/RealTime/IOnlineClientInfoProvider.cs, src/Abp.AspNetCore.SignalR/RealTime/OnlineClientInfoProvider.cs, src/Abp.Web.SignalR/RealTime/IOnlineClientInfoProvider.cs, src/Abp.Web.SignalR/RealTime/OnlineClientInfoProvider.cs, src/Abp.Web.SignalR/Web/SignalR/Hubs/AbpCommonHub.cs
=> Populate OnlineClient.Properties from HttpContext.Query

src/Abp/Domain/Uow/UnitOfWorkManager.cs, test/Abp.TestBase.SampleApplication.Tests/People/PersonRepository_Tests_For_EntityChangeEvents.cs
=> Create a new unit of work for TransactionScopeOption.Suppress.

src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/AbpCommonHub.cs, src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/HubCallerContextExtensions.cs, src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/OnlineClientHubBase.cs, src/Abp.AspNetCore.SignalR/RealTime/IOnlineClientInfoProvider.cs, src/Abp.AspNetCore.SignalR/RealTime/OnlineClientInfoProvider.cs, src/Abp.Web.SignalR/RealTime/IOnlineClientInfoProvider.cs, src/Abp.Web.SignalR/RealTime/OnlineClientInfoProvider.cs, src/Abp.Web.SignalR/Web/SignalR/Hubs/AbpCommonHub.cs
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5613
=> Implements IOnlineClientInfoProvider for 4.x.

src/Abp.AspNetCore/AspNetCore/Threading/HttpContextCancellationTokenProvider.cs, src/Abp.Web.Mvc/Web/Mvc/Threading/HttpContextCancellationTokenProvider.cs, src/Abp/Threading/CancellationTokenOverride.cs, src/Abp/Threading/CancellationTokenProviderBase.cs, src/Abp/Threading/ICancellationTokenProvider.cs, src/Abp/Threading/NullCancellationTokenProvider.cs, test/Abp.TestBase.SampleApplication.Tests/CancellationTokenProvider/CancellationToken_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/SampleApplicationTestBase.cs
Resolve #5724
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5396
=> Allowed to override CancellationToken for a specific call(for 4.x)

src/Abp.AutoMapper/Abp.AutoMapper.csproj
=> Upgrade AutoMapper to v10.0

src/Abp.AutoMapper/Abp.AutoMapper.csproj
=> Upgrade AutoMapper to v10.0.

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs, src/Abp/Domain/Uow/InnerSuppressUnitOfWorkCompleteHandle.cs, src/Abp/Domain/Uow/InnerUnitOfWorkCompleteHandle.cs, src/Abp/Domain/Uow/UnitOfWorkManager.cs, src/Abp/Domain/Uow/UnitOfWorkOptions.cs, src/Abp/Events/Bus/Entities/EntityChangeEventHelper.cs, test/Abp.TestBase.SampleApplication.Tests/People/PersonRepository_Tests_For_EntityChangeEvents.cs
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5710
=> Create a new unit of work for TransactionScopeOption.Suppress. 4.x

src/Abp.AspNetCore/Abp.AspNetCore.csproj, test/Abp.EntityFrameworkCore.Dapper.Tests/Abp.EntityFrameworkCore.Dapper.Tests.csproj, test/Abp.EntityFrameworkCore.Tests/Abp.EntityFrameworkCore.Tests.csproj, test/Abp.Zero.SampleApp.EntityFrameworkCore.ConsoleAppTest/Abp.Zero.SampleApp.EntityFrameworkCore.ConsoleAppTest.csproj, test/Abp.Zero.SampleApp.EntityFrameworkCore.Tests/Abp.Zero.SampleApp.EntityFrameworkCore.Tests.csproj, test/Abp.ZeroCore.IdentityServer4.Tests/Abp.ZeroCore.IdentityServer4.Tests.csproj, test/Abp.ZeroCore.SampleApp/Abp.ZeroCore.SampleApp.csproj
https://github.com/volosoft/castle-windsor-ms-adapter/releases/tag/v3.4.0
=> Upgrade Castle.Windsor.MsDependencyInjection pakcage to 3.4.0

Abp.sln, README.md, doc/WebSite/Document-Index.md, doc/WebSite/Documents.md, doc/WebSite/Zero/Identity-Server-vNext.md, doc/WebSite/Zero/Nuget-Packages.md, doc/api/AbpApiDoc.shfbproj, nupkg/pack.ps1, src/Abp.ZeroCore.IdentityServer4.vNext.EntityFrameworkCore/Abp.ZeroCore.IdentityServer4.vNext.EntityFrameworkCore.csproj, src/Abp.ZeroCore.IdentityServer4.vNext.EntityFrameworkCore/IdentityServer4vNext/AbpZeroCoreIdentityServerEntityFrameworkCoreConfigurationExtensions.cs, src/Abp.ZeroCore.IdentityServer4.vNext.EntityFrameworkCore/IdentityServer4vNext/AbpZeroCoreIdentityServerEntityFrameworkCoreModule.cs, src/Abp.ZeroCore.IdentityServer4.vNext.EntityFrameworkCore/IdentityServer4vNext/AbpZeroIdentityServerBuilderEntityFrameworkCoreExtensions.cs, src/Abp.ZeroCore.IdentityServer4.vNext.EntityFrameworkCore/IdentityServer4vNext/IAbpPersistedGrantDbContext.cs, src/Abp.ZeroCore.IdentityServer4.vNext/Abp.ZeroCore.IdentityServer4.vNext.csproj, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpClaimsService.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpIdentityServerOptions.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpPersistedGrantStore.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpProfileService.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpResourceOwnerPasswordValidator.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpZeroCoreIdentityServerModule.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpZeroIdentityServerBuilderExtensions.cs, src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/PersistedGrantEntity.cs
Resolve #5748  resolve #5694
The 4.x version of Identity Server 4 brought breaking changes. It may be troublesome for developers who use 3.x to upgrade.
I created a separate package that used 4.x.
=> Add IdentityServer4 vNext packages.

src/Abp.HangFire.AspNetCore/Abp.HangFire.AspNetCore.csproj, src/Abp.HangFire/Abp.HangFire.csproj
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5802
=> Update Hangfire to 1.7.13

src/Abp/Webhooks/WebhookSubscriptionInfo.cs, test/Abp.Zero.SampleApp.Tests/WebHooks/WebhookSubscriptionManager_Tests.cs
close #5810  
close https://github.com/aspnetzero/aspnet-zero-core/issues/3484
=> WebhookSubscriptionInfo inherit IMayHaveTenant

src/Abp.HangFire.AspNetCore/Abp.HangFire.AspNetCore.csproj, src/Abp.HangFire/Abp.HangFire.csproj
=> Upgrade Hangfire to 1.7.15. [4.x]

src/Abp.HangFire.AspNetCore/Abp.HangFire.AspNetCore.csproj, src/Abp.HangFire/Abp.HangFire.csproj
=> Upgrade Hangfire to 1.7.15.

src/Abp.AspNetCore.OData/Abp.AspNetCore.OData.csproj
=> Upgrade Microsoft.AspNetCore.OData to 7.5.0

src/Abp.ZeroCore.IdentityServer4.vNext/Abp.ZeroCore.IdentityServer4.vNext.csproj
https://github.com/IdentityServer/IdentityServer4/releases/tag/4.1.1
=> Upgrade IdentityServer4 to 4.1.1

src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
add missing field (isRightToLeft) to ILanguageInfo
=> add missing field to ILanguageInfo

src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs, src/Abp/Linq/IAsyncQueryableExecuter.cs, src/Abp/Linq/NullAsyncQueryableExecuter.cs
Remove synchronous methods from AsyncQueryableExecuter
=> Remove obsoleted methods in async queryable executer

src/Abp/Runtime/Validation/Interception/MethodInvocationValidator.cs
Related: 
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5875
https://github.com/abpframework/abp/pull/5923
=> Do not recursively validate for primitive objects.

appveyor.yml, build/Build.cs, build/Configuration.cs, build/_build.csproj, global.json, test/Abp.NHibernate.Tests/AbpNHibernateInterceptor_Tests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
=> Update Nuke.Common package for .NET 5

src/Abp/Resources/Embedded/EmbeddedResourcePathHelper.cs, test/Abp.Tests/Abp.Tests.csproj, test/Abp.Tests/Resources/Embedded/EmbeddedResourceTests.cs, test/Abp.Tests/Resources/Embedded/MyResources/0.9/MyScriptFile.0.9.js
=> (4.x) Handle directory starting with a digit.

src/Abp/Resources/Embedded/EmbeddedResourcePathHelper.cs, test/Abp.Tests/Abp.Tests.csproj, test/Abp.Tests/Resources/Embedded/EmbeddedResourceTests.cs, test/Abp.Tests/Resources/Embedded/MyResources/0.9/MyScriptFile.0.9.js
=> (5.x) Handle directory starting with a digit.  

src/Abp/Webhooks/IWebhookSubscriptionManager.cs, src/Abp/Webhooks/WebhookSubscriptionManager.cs, test/Abp.Zero.SampleApp.Tests/WebHooks/WebhookSubscriptionManager_Tests.cs
=> Add WebhookSubscription delete method

src/Abp.Zero.Common/DynamicEntityProperties/DynamicEntityPropertyValueStore.cs, src/Abp.Zero.Common/DynamicEntityProperties/DynamicPropertyValueStore.cs, src/Abp/DynamicEntityProperties/DynamicEntityPropertyValue.cs, src/Abp/DynamicEntityProperties/DynamicEntityPropertyValueManager.cs, src/Abp/DynamicEntityProperties/DynamicPropertyValue.cs, src/Abp/DynamicEntityProperties/DynamicPropertyValueManager.cs, src/Abp/DynamicEntityProperties/IDynamicEntityPropertyValueManager.cs, src/Abp/DynamicEntityProperties/IDynamicEntityPropertyValueStore.cs, src/Abp/DynamicEntityProperties/IDynamicPropertyValueManager.cs, src/Abp/DynamicEntityProperties/IDynamicPropertyValueStore.cs, src/Abp/DynamicEntityProperties/NullDynamicEntityPropertyValueStore.cs, src/Abp/DynamicEntityProperties/NullDynamicPropertyValueStore.cs
=> replace DynamicPropertyValue and DynamicEntityPropertyValue's ids with long

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5667
=> adds ondisconnected and reconnected events to signalr

src/Abp.HangFire.AspNetCore/Hangfire/HangfireBackgroundJobManager.cs, src/Abp.HangFire/Hangfire/HangfireBackgroundJobManager.cs
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5939
=> Change HangfireBackgroundJobManager public methods to virtual

src/Abp.Zero.Common/Auditing/AuditLog.cs, src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroDbContext.cs, src/Abp.Zero.NHibernate/Zero/NHibernate/EntityMappings/AuditLogMap.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroDbContext.cs, src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroDbContext.cs, test/Abp.Zero.SampleApp.Tests/Users/UserAppService_Tests.cs
Error info and stack info in the audit log separately.
=> Add the ExceptionMessage field for AuditLog.

src/Abp/DynamicEntityProperties/DynamicPropertyManager.cs, src/Abp/DynamicEntityProperties/IDynamicPropertyManager.cs, test/Abp.Zero.SampleApp.Tests/DynamicEntityProperties/DynamicPropertyManager_Tests.cs
=> Add return values to the Add and Update methods of DynamicPropertyManager.

src/Abp.Zero.Common/Notifications/NotificationSubscriptionSynchronizer.cs, test/Abp.Zero.SampleApp.Tests/Notifications/NotificationSubscriptionSynchronizer_Tests.cs, test/Abp.Zero.SampleApp/Users/Dto/CreateUserInput.cs, test/Abp.Zero.SampleApp/Users/UserAppService.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemo.csproj
=> remove subscription when user deleted

src/Abp/DynamicEntityProperties/DynamicEntityProperty.cs, src/Abp/DynamicEntityProperties/DynamicProperty.cs
=> Add StringLength to DynamicEntityProperty.EntityFullName and DynamicProperty.PropertyName

test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6055
=> AddRazorRuntimeCompilation for AbpAspNetCoreDemo.

src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/AbpHubBase.cs, src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/AbpHubBaseOfClientType.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Controllers/AbpController.cs, src/Abp.AspNetCore/AspNetCore/Mvc/RazorPages/AbpPageModel.cs, src/Abp.AspNetCore/AspNetCore/Mvc/ViewComponents/AbpViewComponent.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Views/AbpRazorPage.cs, src/Abp.Quartz/Quartz/JobBase.cs, src/Abp.Web.Api/WebApi/Controllers/AbpApiController.cs, src/Abp.Web.Mvc/Web/Mvc/Controllers/AbpController.cs, src/Abp.Web.Mvc/Web/Mvc/Views/AbpWebViewPageOfTModel.cs, src/Abp.Web.SignalR/Web/SignalR/Hubs/AbpHubBase.cs, src/Abp/AbpServiceBase.cs, src/Abp/BackgroundJobs/BackgroundJobBase.cs, src/Abp/Threading/BackgroundWorkers/BackgroundWorkerBase.cs
=> Make L method virtual in several base classes

src/Abp.HangFire.AspNetCore/Hangfire/HangfireBackgroundJobManager.cs, src/Abp.HangFire/Hangfire/HangfireBackgroundJobManager.cs
=> Use TJob instead of TArgs to check job type.

src/Abp.EntityFramework/EntityFramework/EfActiveTransactionProvider.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/EfCoreActiveTransactionProvider.cs
Related: https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6085
=> Use ReflectionHelper.InvokeAsync call async method.

doc/WebSite/Dependency-Injection.md, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestModule.cs, test/Abp.ZeroCore.Tests/Zero/DependencyInjection_Tests.cs
=> Add Lazy<T> to dependency injection document and also added a test

src/Abp.AspNetCore/AspNetCore/Mvc/Caching/AspNetCoreGetScriptsResponsePerUserCacheInvalidator.cs, src/Abp.Zero.Common/Caching/GetScriptsResponsePerUserCacheInvalidator.cs, src/Abp/CachedUniqueKeys/CachedUniqueKeyPerUser.cs, src/Abp/CachedUniqueKeys/ICachedUniqueKeyPerUser.cs, test/Abp.Zero.SampleApp.Tests/CachedUniqueKeys/CachedUniqueKeyPerUser_Tests.cs
fixes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6095
=> fix CachedUniqueKeyPerUser bugs

src/Abp.AspNetCore/AspNetCore/AbpAspNetCoreModule.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Caching/AspNetCoreGetScriptsResponsePerUserCacheInvalidator.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Caching/GetScriptsResponsePerUserCacheMiddleware.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Caching/GetScriptsResponsePerUserCacheMiddlewareExtensions.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Caching/GetScriptsResponsePerUserConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Caching/IGetScriptsResponsePerUserConfiguration.cs, src/Abp.Zero.Common/Caching/GetScriptsResponsePerUserCacheInvalidator.cs, src/Abp/CachedUniqueKeys/CachedUniqueKeyPerUser.cs, src/Abp/CachedUniqueKeys/ICachedUniqueKeyPerUser.cs, test/Abp.Zero.SampleApp.Tests/CachedUniqueKeys/CachedUniqueKeyPerUser_Tests.cs
closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6072
=> add IGetScriptsResponsePerUserConfiguration

src/Abp.AspNetCore/AspNetCore/Mvc/Conventions/AbpAppServiceConvention.cs
Related: https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6114
=> Try to add httpMethod in NormalizeSelectorRoutes method..

src/Abp/Authorization/AbpAuthorizationException.cs, src/Abp/Runtime/Validation/AbpValidationException.cs, src/Abp/UI/UserFriendlyException.cs, test/Abp.Tests/Logging/LogSeverity_Tests.cs
=> Allow changing default log severity for ABP exceptions

src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs, src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs, src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroCommonDbContext.cs
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6159
=> add index for UserLogin

src/Abp/EntityHistory/EntitySnapshotManagerBase.cs
fix forgetten part of https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6210 thanks to https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6210#pullrequestreview-717639852
=> Fix forgetten part of #6210 in EntitySnapshotManagerBase.cs

src/Abp.ZeroCore.IdentityServer4.vNext/IdentityServer4vNext/AbpResourceOwnerPasswordValidator.cs, src/Abp.ZeroCore.IdentityServer4/IdentityServer4/AbpResourceOwnerPasswordValidator.cs
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6218
=> Fix IdentityServer Error

doc/WebSite/OData-AspNetCore-Integration.md
=> added note about ODataQueryOptions to OData documentation

src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs
=> Make all AbpUserStore methods virtual

src/Abp.Web.Mvc/Web/Mvc/Resources/Embedded/ComponentsEmbeddedResourceVirtualDirectory.cs, src/Abp.Web.Mvc/Web/Mvc/Resources/Embedded/EmbeddedResourceItemCacheDependency.cs, src/Abp.Web.Mvc/Web/Mvc/Resources/Embedded/EmbeddedResourceVirtualFile.cs, src/Abp.Web.Mvc/Web/Mvc/Resources/Embedded/EmbeddedResourceVirtualPathProvider.cs
Resolves #5995
Can be tested with https://github.com/easyest/TestEmbeddedResources/commits/master
=> fix EmbeddedResourceVirtualPathProvider GetCacheDependency error

doc/WebSite/Zero/User-Management.md, src/Abp.Zero.Ldap/Ldap/Authentication/LdapAuthenticationSource.cs, src/Abp.Zero.Ldap/Ldap/Configuration/AbpZeroLdapModuleConfig.cs, src/Abp.Zero.Ldap/Ldap/Configuration/IAbpZeroLdapModuleConfig.cs
=> add option to use UserPrincipalName in LDAP

src/Abp/DynamicEntityProperties/DynamicEntityPropertyManager.cs, src/Abp/DynamicEntityProperties/DynamicPropertyManager.cs, test/Abp.Zero.SampleApp.Tests/DynamicEntityProperties/DynamicEntityPropertyManager_Tests.cs, test/Abp.Zero.SampleApp.Tests/DynamicEntityProperties/DynamicPropertyManager_Tests.cs
=> Use multi tenancy in dynamic property caches

src/Abp.Zero.Common/Auditing/AuditLog.cs
close https://github.com/aspnetzero/aspnet-zero-core/issues/4053
=> truncate audit log's exception message by max length

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCacheExtensions.cs, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCacheManager.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheReplacementModule.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheReplacement_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheTestModule.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCache_Test.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/PerRequestRedisCacheTestsBase.cs
closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6283
copy of https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6276 for v6.x
=> Implement replacement of AbpPerRequestRedisCache for ICacheManager for v6.x

doc/WebSite/Caching.md, doc/WebSite/PerRequestRedisCache.md
closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6275
=> Per request redis cache documentation

common.props, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpAspNetCorePerRequestRedisCacheModule.cs, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheManager.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCache_Test.cs
=> Use transient AbpPerRequestRedisCache

src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-pt-BR.xml
=> Added missing items to AbpWeb-pt-BR.xml

doc/WebSite/Feature-Management.md
=> Add input types to feature management document

src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
reated related https://github.com/aspnetzero/aspnet-zero-core/issues/4139#
=> allow to return more info in confirm

src/Abp/Localization/Sources/AbpXmlSource/Abp-da.xml
Fix the issue "Can not find 'MainMenu' in localization source 'Abp'!" for danish localization
=> Danish Localization for Abp.xml

src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs, test/Abp.Zero.SampleApp.Tests/Users/UserManager_DeleteUser_Tests.cs, test/Abp.Zero.SampleApp/Users/UserManager.cs, test/Abp.ZeroCore.SampleApp/Core/_Service_Overrides.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_DeleteUser_Tests.cs
closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6379
=> Delete user login when user deleted

doc/WebSite/Multi-Tenancy.md, src/Abp.AspNetCore/AspNetCore/MultiTenancy/DomainTenantResolveContributor.cs, test/Abp.AspNetCore.Tests/Tests/MultiTenancy_Tests.cs
=> added supporting for multiple domains

doc/WebSite/Zero/User-Management.md, src/Abp.Zero.Ldap/Ldap/Authentication/LdapAuthenticationSource.cs, src/Abp.Zero.Ldap/Ldap/Configuration/IAbpZeroLdapModuleConfig.cs
=> Use SamAccountName and  UserPrincipalName respectively while retrieving LDAP user principal

doc/WebSite/Entities.md
Updated documentation for #6405
=> Update "Disable Auditing Fields" documentation

doc/WebSite/OData-AspNetCore-Integration.md, src/Abp.AspNetCore.OData/AspNetCore/OData/Controllers/AbpODataDtoController.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Application/Dtos/ProductCreateInput.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/AbpODataDtoControllerPermissionTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/AbpODataDtoControllerTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Controllers/ProductsDtoController.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
Created based on https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6346/files
=> Added AbpODataDtoController for odata Dto support

doc/WebSite/Dependency-Injection.md, doc/WebSite/Entities.md, doc/WebSite/Logging.md
closes https://github.com/volosoft/volo/issues/9649
=> fix broken links in aspnetboilerplate.com

src/Abp.Zero.Common/Localization/ApplicationLanguageTextManager.cs, src/Abp.Zero.Common/Localization/IApplicationLanguageTextManager.cs
=> Add ApplicationLanguageTextManager support to delete entry

common.props, src/Abp.AspNetCore/AspNetCore/MultiTenancy/DomainTenantResolveContributor.cs, src/Abp.Web/Web/MultiTenancy/DomainTenantResolveContributor.cs, test/Abp.AspNetCore.Tests/Tests/MultiTenancy_Tests.cs
It should control it with and not or.
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/6445/files#diff-149098198d8caf4257cde14c7cd965814fc455290e17379e77388a1b9625dff8R79
Also added same enhancement to the Abp.Web project.
=> Fix domain tenant resolver

src/Abp.Zero.Common/Zero/Configuration/AbpZeroSettingProvider.cs
=> Update default required password length

src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Notifications/SignalRRealTimeNotifier.cs, src/Abp.Web.SignalR/Web/SignalR/Notifications/SignalRRealTimeNotifier.cs, src/Abp.Zero.Common/Notifications/NotificationStore.cs, src/Abp/Notifications/DefaultNotificationDistributer.cs, src/Abp/Notifications/GetNotificationsCreatedByUserOutput.cs, src/Abp/Notifications/INotificationPublisher.cs, src/Abp/Notifications/INotificationStore.cs, src/Abp/Notifications/IRealTimeNotifier.cs, src/Abp/Notifications/NotificationInfo.cs, src/Abp/Notifications/NotificationPublisher.cs, src/Abp/Notifications/NullNotificationStore.cs, src/Abp/Notifications/UserNotification.cs, src/Abp/Notifications/UserNotificationInfo.cs, src/Abp/Notifications/UserNotificationInfoExtensions.cs, test/Abp.Tests/Notifications/NotificationPublisher_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/RealtimeNotification_TargetNotification_Tests.cs
closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6465
=> Allow users to select target notifier when publishing notification 

doc/WebSite/Notification-System.md
=> update nofitication system document according to pr 6466

src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCache.cs, src/Abp/Runtime/Caching/AbpCacheBase.cs, src/Abp/Runtime/Caching/IAbpCache.cs, src/Abp/Runtime/Caching/ICacheOptions.cs, src/Abp/Runtime/Caching/Memory/AbpMemoryCache.cs, src/Abp/Runtime/Caching/TypedCacheWrapper.cs, test/Abp.Tests/Runtime/Caching/Memory/MemoryCacheManager_Tests.cs
=> Introduce DefaultAbsoluteExpireTimeFactory.

doc/WebSite/Multi-Lingual-Entities.md, src/Abp.AutoMapper/AutoMapper/AutoMapExtensions.cs, test/Abp.ZeroCore.SampleApp/AbpZeroCoreSampleAppModule.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/IOfficeAppService.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/OfficeCreateDto.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/OfficeListDto.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/OfficeTranslationDto.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/OfficeUpdateDto.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/OrderListDto.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/ProductListDto.cs, test/Abp.ZeroCore.SampleApp/Application/Shop/ProductUpdateDto.cs, test/Abp.ZeroCore.SampleApp/Core/Shop/Office.cs, test/Abp.ZeroCore.SampleApp/Core/Shop/OfficeTranslation.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs, test/Abp.ZeroCore.Tests/Zero/MultiLingual/MultiLingual_Mapping_Tests.cs
=> Allow defining key for translation entity while using CreateMultiLingualMap

src/Abp.NHibernate/NHibernate/AbpNHibernateModule.cs, src/Abp.NHibernate/NHibernate/EntityMappings/EntityMapOfTEntityAndTPrimaryKey.cs, src/Abp.NHibernate/NHibernate/EventListeners/AbpDeleteEventListener.cs, src/Abp.NHibernate/NHibernate/EventListeners/AbpNHibernateDeleteEventListener.cs, src/Abp.NHibernate/NHibernate/EventListeners/AbpNHibernateLoadEventListener.cs, src/Abp.NHibernate/NHibernate/Interceptors/AbpNHibernateInterceptor.cs, src/Abp.NHibernate/NHibernate/Repositories/NhRepositoryBaseOfTEntityAndTPrimaryKey.cs, src/Abp.NHibernate/NHibernate/Uow/NhUnitOfWork.cs
=> Soft delete fixes for NHibernate provider

src/Abp/Runtime/Caching/AbpCacheData.cs
=> expose withAssemblyName on AbpCacheData Serialize method

src/Abp/Runtime/Caching/Memory/AbpMemoryCache.cs
=> set AbsoluteExpiration and SlidingExpiration correctly in AbpMemoryCache

src/Abp.EntityFrameworkCore/EntityFrameworkCore/Repositories/EfCoreRepositoryExtensions.cs, test/Abp.EntityFrameworkCore.Tests/Tests/Repository_Extension_Tests.cs
=> Add efcore range methods

src/Abp.EntityFrameworkCore/EntityFrameworkCore/Repositories/EfCoreRepositoryBaseOfTEntityAndTPrimaryKey.cs
=> Update InsertAsync method

src/Abp/RealTime/OnlineClientManager.cs
=> remove usage of lock in OnlineClientManager

src/Abp.Zero.Common/Webhooks/WebhookSendAttemptStore.cs, src/Abp/Webhooks/IWebhookSendAttemptStore.cs, src/Abp/Webhooks/NullWebhookSendAttemptStore.cs, test/Abp.Zero.SampleApp.Tests/Webhooks/WebhookSendAttemptStore_Tests.cs
=> Added Delete methods to WebhookSendAttemptStore

doc/WebSite/AspNet-Core.md, src/Abp.AspNetCore/Json/CultureInvariantDecimalConverter.cs, src/Abp.AspNetCore/Json/CultureInvariantDoubleConverter.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/AbpAspNetCoreDemoCoreModule.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Application/ModelBindingAppService.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/ModelBindingAppServiceTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
=> Introduce double and decimal JSON converters

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/EntityHistory/Employee.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
=> save enum types for entity history in EF6

doc/WebSite/Abp-Session.md, test/Abp.Dapper.Tests/DapperRepository_Tests.cs, test/Abp.ZeroCore.SampleApp/Core/Restaurant.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/Sessions/Session_Override_Tests.cs
=> Added unit test for session override and updated documentation

doc/WebSite/AspNet-Core.md
=> Add HtmlSanitizer document

src/Abp.HangFire.AspNetCore/Abp.HangFire.AspNetCore.csproj, src/Abp.HangFire/Abp.HangFire.csproj
=> Upgrade Hangfire to 1.8 final

src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs
=> make RemoveToken, GetToken and GetUserNameFromDatabase virtual in AbpUserStore

doc/WebSite/Data-Filters.md
source: https://aspnetboilerplate.com/Pages/Documents/Data-Filters#entity-framework-core
=> Fix query typo on data filters page

doc/WebSite/AspNet-Core.md
Removed duplicate word (`provides`) in AspNet-Core.md
=> typo: in AspNet-Core.md

doc/WebSite/SignalR-AspNetCore-Integration.md
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1891
=> Added note about signalr events to SignalR-AspNetCore-Integration.md

src/Abp.MailKit/Abp.MailKit.csproj
=> Update MailKit to 4.2.0

doc/WebSite/Background-Jobs-And-Workers.md, src/Abp/Application/Features/SimpleFeatureDependency.cs, src/Abp/Authorization/SimplePermissionDependency.cs, src/Abp/BackgroundJobs/BackgroundJobConfiguration.cs, src/Abp/BackgroundJobs/BackgroundJobManager.cs, src/Abp/BackgroundJobs/IBackgroundJobConfiguration.cs, test/Abp.Tests/BackgroundJobs/InMemoryBackgroundJobStore_Tests.cs
=> Create MaxWaitingJobToProcessPerPeriod for background job configuration 

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs
=> Use TryGetValue in AbpPerRequestRedisCache instead of ContainsKey to prevent errors

src/Abp/Abp.csproj
=> Downgrade System.ComponentModel.Annotations to 5.0

src/Abp/DynamicEntityProperties/DynamicPropertyManager.cs
resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6845
=> fixes Updating DynamicProperty validation issue #6845

doc/WebSite/Articles/Aspect-Oriented-Programming-using-Interceptors/index.html
Resolves #6798 
The Aspect Oriented Programming using Interceptors documentation has been updated. Codes have been corrected according to the base class.
=> Update Aspect Oriented Programming using Interceptors document.

src/Abp.AspNetCore/AspNetCore/Localization/AbpUserRequestCultureProvider.cs
=> Validate culture before changing the default language setting

doc/api/docfx/create-docs.ps1, doc/api/docfx/overrides/docfx.json
=> Fix docfx document generation

src/Abp.Zero.Common/Authorization/Users/UserLoginAttempt.cs, src/Abp.Zero/Authorization/AbpLoginManager.cs, src/Abp.Zero/Authorization/Users/AbpLoginResult.cs, src/Abp.ZeroCore/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpLoginResult.cs, test/Abp.ZeroCore.SampleApp/Authorization/AppLogInManager.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserLoginHelper.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserLogin_Tests.cs
=> Add FailReason to UserLoginAttempt

src/Abp/Json/JsonExtensions.cs, src/Abp/Json/SystemTextJson/AbpCustomJsonConverterForType.cs, src/Abp/Reflection/TypeHelper.cs, src/Abp/Runtime/Caching/AbpCacheData.cs, test/Abp.Tests/Runtime/Caching/AbpCacheData_Tests.cs
=> Created AbpJsonConverterForType to serialize System.Type for System.Text.Json

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Closes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6894
=> Fix entity history problem

src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheOptions.cs, src/Abp.RedisCache/Runtime/Caching/Redis/RealTime/RedisOnlineClientStore.cs, src/Abp.RedisCache/Runtime/Caching/Redis/RedisCacheConfigurationExtensions.cs, src/Abp/AbpKernelModule.cs, src/Abp/RealTime/IOnlineClientStore.cs, src/Abp/RealTime/InMemoryOnlineClientStore.cs, src/Abp/RealTime/OnlineClientManager.cs, test/Abp.Tests/RealTime/InMemoryOnlineClientStore_Tests.cs
resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6915
Removed generic versions of `IOnlineClientManager` and `IOnlineClientStore`. You should use their non-generic version.
=> Remove generic IOnlineClientManager and its implementation

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs
=> Refactor `AbpLoginManager`

src/Abp/Authorization/IPermissionManager.cs, src/Abp/Authorization/PermissionManager.cs
Implements the changes suggested in #6932.
=> Implemented async alternatives to the IPermissionManager's GetAllPermissions methods.

src/Abp/Authorization/PermissionManager.cs, test/Abp.Tests/Authorization/PermissionDefinitionTests.cs, test/Abp.Zero.SampleApp.Tests/Roles/RoleManager_Tests.cs, test/Abp.Zero.SampleApp.Tests/Users/UserManager_Permission_Tests.cs, test/Abp.Zero.SampleApp/Authorization/AppAuthorizationProvider.cs, test/Abp.Zero.SampleApp/Features/AppFeatureProvider.cs
=> Fix filter problem in PermissionManager's GetAllPermissionsAsync

src/Abp.Zero.Common/BackgroundJobs/BackgroundJobStore.cs
=> Revert changes for `BackgroundJobStore` for mysql problems

doc/WebSite/BLOB-Storing-File-System.md, doc/WebSite/BLOB-Storing.md, doc/WebSite/Blob-Storing-Azure.md, doc/WebSite/Documents.md
=> Added BLOB storage documentation

src/Abp.AspNetCore/AspNetCore/Mvc/Authorization/AbpAuthorizationFilter.cs
=> Return forbidden result if authenticated user not granted

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs
Resolves #7049
This requirement was removed because logging in with External Login was not compatible with the user Lockout setting structure.
=> Removed Lockout control from ExternalLogin

src/Abp.Zero.Common/Auditing/AuditLog.cs
Updated MaxParametersLength to 2000
=> Updated MaxParametersLength to 2000

src/Abp.Dapper/Abp.Dapper.csproj
=> Add System.Net.Http to Abp.Dapper.csproj

README.md
The links in the announcement section have been edited to include tracking urls.
=> Added referral tracking to links in README.md

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCacheExtensions.cs
=> register RedisOnlineClientStore when using AbpPerRequestRedisCache

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
=> correctly use maxTries and re-implement increaseReconnectTime in abp-signalr-client.js

src/Abp.Zero.Common/Auditing/AuditLog.cs
=> increase MaxParametersLength for AuditLog Parameters field

src/Abp.RedisCache/Runtime/Caching/Redis/RealTime/RedisOnlineClientStore.cs
=> Change implementation of RedisOnlineClientStore to increase performance
