aspnetboilerplate/aspnetboilerplate

src/Abp.Web/Web/WebAssemblyFinder.cs
The search option used to find assemblies in bin folder was hardcoded and now can be set by all web applications inheriting AbpWebApplication. We can now find assemblies in the the bin folder and all subfolders (my application has modules in subfolders like portable areas).
Thank you.
=> SearchOption

src/Abp.RedisCache/AbpRedisCacheConfig.cs, src/Abp.RedisCache/RedisCache/AbpRedisCache.cs, src/Abp.RedisCache/RedisCache/Configuration/IRedisConnectionProvider.cs, src/Abp.RedisCache/RedisCache/Configuration/RedisConnectionProvider.cs, src/Tests/Abp.RedisCache.Tests/Abp.RedisCache.Tests.csproj, src/Tests/Abp.RedisCache.Tests/App.config, src/Tests/Abp.RedisCache.Tests/RedisCacheManager_Test.cs
By default the stackexchange.redis uses the first database (DatabaseId  = 0) for the default connection string. the AbpRedisCache didn't make it configurable and this pull request makes it support to set Abp.Redis.Cache.DatabaseId in app settings.
=> Add DatabaseId configuration support for AbpRedisCache

src/Abp.EntityFramework/EntityFramework/Extensions/DbContextExtensions.cs, src/Tests/Abp.EntityFramework.Tests/Repositories/EntityFrameworkGenericRepositoryRegistrar_Tests.cs
Hi @hikalkan, 
I made the change in DbContextExtensions as you've suggested.
=> Resolved #866: Non-entity DbSets ignored by EF repository registrar.

src/Abp.Web.Api.OData/WebApi/OData/Controllers/AbpODataEntityController.cs
Using only InsertAndGetIdAsync() method doesn't fixes the bug when the retured entity has { Id: 0, TenantId: 0} and so on.
=> Updating AbpODataEntityController.Post() to return the created entity.

src/Abp/BackgroundJobs/BackgroundJobInfo.cs
DefaultTimeout unit is seconds
I think nextTryDate.Subtract(CreationTime) should use TotalSeconds instead of TotalDays
=> calculate next retry time unit should be seconds

src/Abp/Localization/Sources/AbpXmlSource/Abp-zh-CN.xml
because there is warning "- Can not find 'CurrentUserDidNotLoginToTheApplication' in localization source 'Abp'!" when user is not login.
=> update localization sources "zh-CN"

src/Abp.AspNetCore/AspNetCore/AbpAspNetCoreModule.cs, src/Abp.AspNetCore/AspNetCore/Runtime/Session/AspNetCoreClaimsAbpSession.cs
Because asp .net core do not relay ClaimsPrincipal by Thread.CurrentPrincipal anymore, we need to inject HttpContextAccessor.
For unit test friendly, I made HttpContextAccessor as property injection.
=> add a new AbpSession class to get userid from asp. net core

Abp.sln, src/Abp.Log4Net/Abp.Log4Net.xproj, src/Abp.Log4Net/Log4NetBootstrapper.cs, src/Abp.Log4Net/Log4NetFactory.cs, src/Abp.Log4Net/Log4NetModule.cs, src/Abp.Log4Net/Log4netLogger.cs, src/Abp.Log4Net/Properties/AssemblyInfo.cs, src/Abp.Log4Net/log4net.config, src/Abp.Log4Net/project.json
Abp  is  use  log4net with  1.2.10 .  if  the  version  is  1.2.13 or   the  lasted  like 2.0.5 ,  abp  don't  support.  So  I  google  one  solution,  the  detail code  in   the  abp.log4net .
Thanks!
=> add  abp.log4net   project  to  support  log4net 2.0.5

src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/TypeScript/TypeScriptHelper.cs
Hi,
TypescriptHelper does not manage decimal types, so when i have a .NET decimal type property in a dto , it doesn't have been converted to typescript number type
=> Managed decimal CLR type in typescript helper

src/Abp/Localization/Sources/AbpXmlSource/Abp-tr.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp-zh-CN.xml, src/Abp/Localization/Sources/AbpXmlSource/Abp.xml
TimeZoneAllOfThesePermissionsMustBeGranted changed to AllOfThesePermissionsMustBeGranted. There must have been some kind of spelling mistake.
=> Fixed AbpXmlSource translation files: TimeZoneAllOfThesePermissionsMustBeGranted

src/Abp/Runtime/Security/SimpleStringCipher.cs
if cipherText is empty, is exception
=> SimpleStringCipher Decrypt method Exception

src/Abp.Web.Api/WebApi/Controllers/Dynamic/Scripting/jQuery/JQueryProxyGenerator.cs
#1741  ReferenceError: define is not defined
[jquery judgment define the way](https://github.com/jquery/jquery/blob/ee2e377494a882f043e6d8abc67ac6370ee83d9c/dist/jquery.js#L10179)
```
if (typeof define === "function" && define.amd) {
define("jquery", [], function(){
return jQuery;
});
}
```
=> fix define is not defined

src/Abp.Web.Api/WebApi/Controllers/ResultWrapperHandler.cs
This fixes an issue in `ResultWrapperHandler` that prevents aborted requests from being completed.
To reproduce this issue you can add this code to an API controller ( and use the old `ResultWrapperHandler` with `ContinueWith`):
```
private static int s_counter;    
public async Task<IHttpActionResult> Submit()
{
Interlocked.Increment(ref s_counter);
await Task.Delay(30 * 1000);
Interlocked.Decrement(ref s_counter);
Debug.WriteLine($"Counter {s_counter}");
return Ok(_counter);
}
```
and call it from browser. If you close the tab during the 30 seconds delay the request is aborted and `Interlocked.Decrement(ref s_counter);` will never be called.
This is problematic when you manually call `SaveChangesAsync` and the request is aborted before `uow.CompleteAsync` is called by `AbpApiUowFilter`. …
=> Replaced ContinueWith with async/await in ResultWrapperHandler

src/Abp.EntityFramework/EntityFramework/Extensions/QueryableExtensions.cs, src/Abp.EntityFramework/EntityFramework/Interceptors/WithNolockInterceptor.cs, src/Abp.TestBase/TestBase/AbpIntegratedTestBase.cs, test/Abp.TestBase.SampleApplication.Tests/People/PersonRepository_General_Nolocking_Tests.cs, test/Abp.TestBase.SampleApplication.Tests/SampleApplicationTestBase.cs
I implemented With Nolock interception for select queries on Repository level. I wrote test, but Effort does not generate Sql statements while interception time, so i tested local sql server on my computer and it works.
If you have a chance to review would be great!
Thanks in advance.
=> Nolocking mechanism implemented for #1637

src/Abp.AspNetCore/Abp.AspNetCore.csproj, test/Abp.EntityFrameworkCore.Tests/Abp.EntityFrameworkCore.Tests.csproj
Required because of this component [issue](https://github.com/volosoft/castle-windsor-ms-adapter/issues/8).
I'm using Abp along with [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) and it registers IEnumerable of T.
=> Update Castle.Windsor.MsDependencyInjection to latest.

src/Abp.Dapper/Dapper/Expressions/DapperExpressionVisitor.cs
Fixed the bug when used '&&' and '||' together in Lamba Expression,just like this, 'x => x.CarId == 1 && x.IsActive|| x.PersonId == 1'.
=> Modify DapperExpressionVisitor.cs

src/Abp.Dapper/Abp.Dapper.csproj, test/Abp.Dapper.NHibernate.Tests/Abp.Dapper.NHibernate.Tests.csproj
DapperExtensions 1.5.0 referenced for .net targeted projects, others are DapperExtensions.DotnetCore.
Fix for #2209
=> DapperExtensions 1.5.0 referenced for .net targeted projects

src/Abp/Authorization/SimplePermissionDependency.cs
Fixed incorrect parameter name ```features``` in SimplePermissionDependency.cs
=> Fixed incorrect parameter name

src/Abp/Extensions/ObjectExtensions.cs, test/Abp.Tests/Extensions/ObjectExtension_Test.cs
The following exception is thrown when the extension method is called like 
`var x = value.To<Guid>();`
> Invalid cast from 'System.String' to 'System.Guid'
This PR uses a different method to convert to a Guid. An example has been added to an existing unit test to cover the changes.
=> .To<Guid>() object extension method throws Invalid cast from 'System.String' to 'System.Guid' exception.

src/Abp.AspNetCore/Abp.AspNetCore.csproj, src/Abp.AspNetCore/AspNetCore/Configuration/AbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Configuration/IAbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/AbpResultFilter.cs, src/Abp/Web/Models/CacheResultAttribute.cs
I introduced a CacheResult attribute to allow control of the response cache headers
=> feat(app-services): Introduced CacheResultAttribute to allow response cache control

src/Abp.NHibernate/Abp.NHibernate.csproj, src/Abp.NHibernate/NHibernate/Uow/NhUnitOfWork.cs, test/Abp.Dapper.NHibernate.Tests/AbpDapperNhBasedTestModule.cs, test/Abp.Dapper.NHibernate.Tests/DapperNhBasedApplicationTestBase.cs, test/Abp.NHibernate.Tests/AbpNHibernateInterceptor_Tests.cs, test/Abp.NHibernate.Tests/NHibernateTestBase.cs, test/Abp.NHibernate.Tests/NHibernateTestModule.cs, test/Abp.Zero.SampleApp.NHibernateTests/NHibernate/NHibernateTestBase.cs, test/Abp.Zero.SampleApp.NHibernateTests/NHibernate/SampleAppNHibernateModule.cs
Project is building with no error. And all tests are passed. Only following breaking change is occured and it is fixed.
> All members exposing some System.Data types have been changed for the corresponding System.Data.Common types. (IDbCommand => DbCommand, ...)
=> Resolved #2594 - Move to NHibernate 5.0

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.jquery.js
Replaces 
https://github.com/aspnetboilerplate/bower-abp-resources/pull/5
as changes to abp.jquery.js should be made here and not in https://github.com/aspnetboilerplate/bower-abp-resources
=> Prevent IE11 caching GET call in Angular 2

src/Abp.ZeroCore.EntityFramework/Abp.ZeroCore.EntityFramework.csproj, src/Abp.ZeroCore.EntityFramework/Data/ConnectionStringHelper.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCoreEntityFrameworkModule.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroDbMigrator.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroDbModelBuilderExtensions.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroHostDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroTenantDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/DbPerTenantConnectionStringResolver.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/IMultiTenantSeed.cs
As mention in #2600, i created `Abp.ZeroCore.EntityFramework`
=> Added Abp.ZeroCore.EntityFramework

src/Abp.MailKit/EmailExtensions.cs, src/Abp.MailKit/EmailExtensitons.cs
Hi @hikalkan , as seen in #2442, I referred to the conversion method in https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MimeMessage.cs#L2965 and modified the `EmailExtensions.cs` in `Abp.MailKit` package.
The current release of `MimeKit 1.18.1` only supports up to Net Standard 1.3. and i think that the support for Net Standard 2.0 won't be coming so soon.
=> Fix MailMessage to MimeMessage conversion

src/Abp.Zero/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/AbpLoginManager.cs
I am developing an enterprise application. All my user login solely from LDAP.
And I have an admin portal to manage all application users.
Admin user can set a user's LockoutEndDateUtc column to temporarily prevent the user from login.
However, the LoginManager doesn't check lockout status if the user is logged in from LDAP.
I have added the logic to check lockout status in this PR.
=> Check user lockout for user log in from LDAP

src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs, src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs
Fixes #2748
Follows https://github.com/aspnetboilerplate/aspnetboilerplate/commit/5110b86dcc7ff4c48085da596664ddfebb084a75
`GrantAllPermissionsAsync` should set `FeatureDependencyContext.TenantId` based on the `role` that the permissions are being granted to. This makes the logic more obvious in:
```c#
public async Task GrantAllPermissionsAsync(TRole role)
{
FeatureDependencyContext = role.TenantId;
// ...
// permission.FeatureDependency.IsSatisfied(FeatureDependencyContext)
// ...
}
```
This would also be consistent with how it's being done when `FeatureDependencyContext` is used in [`NotificationDefinitionManager`](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/7852b028eb0499a802d3cb31d5790353e2ece0f7/src/Abp/Notifications/NotificationDefinitionManager.cs#L87) and …
=> Set FeatureDependencyContext.TenantId before using it

src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate/pull/2625#issuecomment-346883183:
> System.InvalidOperationException: The index with name 'IX_UserId_State_CreationTime' on table 'dbo.AbpUserNotifications' has the same column order of '1' specified for columns 'TenantId' and 'UserId'. Make sure a different order value is used for the IndexAttribute on each column of a multi-column index.
The index with name 'IX_UserId_State_CreationTime'  is created twice for the same entity. The second one wrongly sets an index on `e.TenantId`, and the same column on `e.State` and `e.CreationTime`.
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/f2df33b0e8070e16e5b1634e7f59f54e35df64ca/src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs#L334-L344 …
=> Remove faulty/duplicate CreateIndex

doc/WebSite/Zero/User-Management.md
Fixes #2781
- Social logins documentation was removed in bcc339d
- If you are using an earlier version like ABP v2.3.0, you may refer to the documentation here: https://aspnetboilerplate.com/Pages/Documents/v2.3.0/Zero/Startup-Template#social-logins
=> Change link for Social Logins in doc

src/Abp.Web.SignalR.AspNetCore/Abp.Web.SignalR.AspNetCore.csproj
Follows #2790 
Let's update from `2.1.0-preview1-`**`27815`** to `1.0.0-preview1-`**`27891`** before ABP v3.3.0 is published.
This makes it less confusing when updating to `1.0.0-preview1` once it's officially released on NuGet.
=> Update Microsoft.AspNetCore.SignalR package

doc/WebSite/Entity-History.md, src/Abp.AspNetCore/AspNetCore/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, src/Abp/AbpBootstrapper.cs, src/Abp/EntityHistory/EntityChangeSet.cs, src/Abp/EntityHistory/EntityChangeSetReasonProviderBase.cs, src/Abp/EntityHistory/EntityHistoryInterceptor.cs, src/Abp/EntityHistory/EntityHistoryInterceptorRegistrar.cs, src/Abp/EntityHistory/IEntityChangeSetReasonProvider.cs, src/Abp/EntityHistory/NullEntityChangeSetReasonProvider.cs, src/Abp/EntityHistory/ReasonOverride.cs, src/Abp/EntityHistory/UseCaseAttribute.cs, test/Abp.AspNetCore.Tests/Tests/EntityHistory_Reason_Tests.cs
=> Support a Reason property in EntityChangeSet

doc/WebSite/EventBus-Domain-Events.md
Reflect the changes from #1695
Mentioned in https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2301#issuecomment-314275760
```diff
-'ing' events (ex: EntityUpdating) are triggered before saving changes.
+'ing' events (e.g. EntityUpdating) are triggered before committing a transaction.
This way, you can rollback the [unit of work](/Pages/Documents/Unit-Of-Work)
-and prevent an operation by throwing exceptions. 'ed'
-events (ex: EntityUpdated) are triggered after saving changes, for which 
+and prevent an operation by throwing an exception. 'ed'
+events (e.g. EntityUpdated) are triggered after committing a transaction, for which
```
=>  Update descriptions in EventBus-Domain-Events.md

src/Abp/EntityHistory/EntityChange.cs, src/Abp/EntityHistory/EntityPropertyChange.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Follows [`7c9da13`](https://github.com/aspnetboilerplate/aspnetboilerplate/commit/7c9da13e12fbe4ee46cd049ccfd999becc866c1b#diff-bbc0190d25035d0627fe4d1dd507f974L136)
This went unnoticed as AppVeyor fails [expectedly](https://github.com/aspnetboilerplate/aspnetboilerplate/pull/2852#issuecomment-355879832) on an earlier test case ([496](https://ci.appveyor.com/project/hikalkan/aspnetboilerplate/build/1.0.1746/tests)) due to #2855.
This causes AppVeyor to not complete the full test suite ([835](https://ci.appveyor.com/project/hikalkan/aspnetboilerplate/build/1.0.1731-fqwqwfad/tests)+).
I wonder if the known cause can be [resolved](https://forum.aspnetboilerplate.com/viewtopic.php?p=25550#p25551) on AppVeyor.
Or should the `[Fact]` attribute of [that test …
=> Fix test case for Entity History

src/Abp.Zero.Ldap/Abp.Zero.Ldap.csproj
move package Abp.Zero.Ldap to build on top of  netstandard2.0 
System.DirectoryServices.AccountManagement Versin 4.5.0-preview1-25914-04 and
System.DirectoryServices.AccountManagement Version=4.5.0-preview1-25914-04
=> feat: migrate Abp.Zero.Ldap to netstandard2.0

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs
This avoids confusion and protects from calling `AbpStore`'s methods directly. #3055
=> Set access to AbpStore property as protected in AbpUserManager

src/Abp/Events/Bus/EventBus.cs, src/Abp/Events/Bus/Factories/Internals/TransientEventHandlerFactory.cs, src/Abp/Events/Bus/Handlers/IAsyncEventHandlerOfTEventData.cs, src/Abp/Events/Bus/Handlers/IEventHandlerOfTEventData.cs, src/Abp/Events/Bus/Handlers/Internals/ActionAsyncEventHandler.cs, src/Abp/Events/Bus/IEventBus.cs, src/Abp/Events/Bus/NullEventBus.cs, test/Abp.Tests/Castle/Castle_Interception_Test.cs, test/Abp.Tests/Events/Bus/ActionBasedEventHandlerTest.cs, test/Abp.Tests/Events/Bus/EventBus_MultipleHandle_Test.cs, test/Abp.Tests/Events/Bus/MySimpleTransientAsyncEventHandler.cs, test/Abp.Tests/Events/Bus/TransientDisposableEventHandlerTest.cs
Resolved #2691 
- Added `IAsyncEventHandler` as suggested in the issue.
- Added `AsyncRegister` & `AsyncUnregister` methods in `IEventBus`.
- Added another `ConcurrentDictionary<Type, List<IEventHandlerFactory>>` in `EventBus` to maintain synchronous & asynchronous handlers independently
- `TriggerAsync` will run asynchronous handlers first then synchronous handlers, and `await` all asynchronous handlers after execution of all synchronous handlers.
Initially, I thought of using `Async` suffix, however, it becomes confusing with `TriggerAsync`, which the former is registering/un-registering async handler, and the later is triggering the event asynchronously.
Also, I did try to keep the method signature as `Register(...)` for both synchronous & asynchronous event handlers by using the …
=> IAsyncEventHandler Implementation

doc/WebSite/SignalR-AspNetCore-Integration.md, src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js, src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr.d.ts
Better support for multiple SignalR hubs ([module-zero-core-template#190](https://github.com/aspnetboilerplate/module-zero-core-template/issues/190), [SO question 48897720](https://stackoverflow.com/questions/48897720/multiple-signalr-connections-in-abp))
- Expose `startConnection` in abp.signalr.d.ts
- Expose `remoteServiceBaseUrl` in abp.signalr.d.ts
- Add `remoteServiceBaseUrl` and `qs` in `startConnection` — abp.signalr-client.js
- Update instructions for multiple SignalR hubs — SignalR-AspNetCore-Integration.md
Fix reconnect code
- Replace `$.connection` in abp.signalr-client.js
- Fix whitespace and indentation — abp.signalr-client.js
Update method call in documentation ([SO question 48875859](https://stackoverflow.com/questions/48875859/aspnetcore-signalr-iclientproxy-does-not-contai …
=> Better support for multiple SignalR hubs

src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs
Fixes #3152 
The current fix assumes that `TenantId` is correctly set in `CurrentUnitOfWork` or `AbpSession`.
Actually, we should use `user.TenantId`, similar to #2751. Should I push [`370f0ef`](https://github.com/acjh/aspnetboilerplate/commit/370f0ef64f953565a4fa29070e12c6f19c054e4e) to this PR?
=> Set FeatureDependencyContext.TenantId before using

src/Abp.AspNetCore/AspNetCore/EmbeddedResources/EmbeddedResourceFileProvider.cs, src/Abp.AspNetCore/AspNetCore/EmbeddedResources/EmbeddedResourceItemDirectoryContents.cs, src/Abp.AspNetCore/AspNetCore/EmbeddedResources/EmbeddedResourceItemFileInfo.cs, src/Abp/Resources/Embedded/EmbeddedFilePathHelper.cs, src/Abp/Resources/Embedded/EmbeddedResourceManager.cs, src/Abp/Resources/Embedded/EmbeddedResourceSet.cs, src/Abp/Resources/Embedded/IEmbeddedResourceManager.cs, test/Abp.Tests/Abp.Tests.csproj, test/Abp.Tests/Resources/Embedded/EmbeddedResourceTests.cs, test/Abp.Tests/Resources/Embedded/MyResources/js-dash/MyScriptFile.js, test/Abp.Tests/Resources/Embedded/MyResources/js/MyScriptFile3.min.js, test/Abp.Tests/Resources/Embedded/MyResources/js/MyScriptFile_4.js, test/Abp.Tests/Resources/Embedded/MyResources/js_underscore/MyScriptFile.js
- fix for double dots in filenames
- fix for dashes in foldernames
- new tests 
- implamentation of GetDirectoryContents of EmbeddedResourceFileProvider
Inpired by https://github.com/aspnet/FileSystem/issues/184
Background 
Actually in Abp the embeded resources are available thru the EmbeddedResourceFileProvider witch call the EmbeddedResourceManager. The EmbeddedResourceManager contain a dictionarry of EmbeddedResourceItem (key = filepath, value = Resource (name, content, assembly, LastModifiedUtc) ) witch is constructed based on EmbeddedResourceSet stored as sources in the  EmbeddedResourcesConfiguration.
The EmbeddedResourceManager try to find the file content based on the key witch is normally the filepath requested by the EmbeddedResourceFileProvider.
The issue is that the …
=> Embeded resources

src/Abp.Web.Common/Web/Api/ProxyScripting/Generators/ProxyScriptingHelper.cs
This allows custom script generators to be created by the user.
=> ProxyScriptingHelper should be public

src/Abp.Web.Common/Web/Api/ProxyScripting/Generators/ProxyScriptingJsFuncHelper.cs
This allows users to create their own script generators and use the existing helper functionality
=> ProxyJsScriptingFuncHelper should be public

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs
From the documentation on [Multi-Tenancy](https://aspnetboilerplate.com/Pages/Documents/Multi-Tenancy#additional-notes):
> When you define an entity type as IMustHaveTenant or IMayHaveTenant, **always set the TenantId** when you create a new entity (While ASP.NET Boilerplate tries to set it from current TenantId, it may not be possible in some cases, especially for IMayHaveTenant entities).
=> Set TenantId for IMayHaveTenant entities (Entity History)

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
- Don't save property history for `EntityChange.EntityId`
- Rename `EntityChangeInfo` to `EntityChange`
=> Don't save property history for EntityChange.EntityId

build.cake, test/Abp.Castle.Log4Net.Tests/Abp.Castle.Log4Net.Tests.csproj, test/Abp.MailKit.Tests/Abp.MailKit.Tests.csproj, test/Abp.Quartz.Tests/Abp.Quartz.Tests.csproj, test/Abp.Quartz.Tests/Abp.Quartz.Tests.xunit.runner.json, test/Abp.Quartz.Tests/QuartzTests.cs
- Cake: Add vswhere to run cake in a development machine 
- Add missing packages for Test Project
- Fix Quartz Test broken 
- Remove the build() calling to schedule 
- Change the Thread.Sleep to Task.Delay in QuartzTests.cs 
- Temporary fix test broken in AppVeyor 
(The commit 47777b150b5a4519c331364708cb1a7dafa039e9 actually fixed it)
After #3282 , I managed to [access AppVeyor's windows build worker via remote desktop](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) and ran the test case in it, so that I could reproduce the test broken constantly.
I find that the test will pass when there is only one test case (`Fact`) in the `Abp.Quartz.Tests`. When I remove the test case `QuartzScheduler_Jobs_ShouldBeRegistered`, test case …
=> Fixes to Abp.Quartz.Tests, Test projects and Cake

build.cake
Previously, if one test case fails, the rest test case wouldn't be executed. It can be fixed by isolating each task.
=> Continue testing when failing one test case

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Comment.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Fixes #3214 
> As the [documentation](https://github.com/aspnet/EntityFrameworkCore/blob/c8bc1783f44cae6b9c0182b734d9bfc3761e75e5/src/EFCore/Metadata/IPropertyBase.cs#L33) says `PropertyInfo` can be null for shadow properties or properties mapped directly to fields.
=> Handle property history for shadow properties

src/Abp.EntityFrameworkCore/EntityFrameworkCore/Extensions/QueryableExtensions.cs
One extension is for adding navigation properties using string expression.
The other is when you want to include multiple navigation properties using `Include` and `IncludeThen` operators.
Example: `query.IncludeIf(true, q => q.Include(blog => blog.Posts).ThenInclude(post => post.Tags))`
=> Add more IncludeIf extensions for EF Core

src/Abp.Zero.Common/MultiTenancy/AbpTenantManager.cs, src/Abp.Zero.Ldap/Ldap/Configuration/LdapSettingProvider.cs, src/Abp.Zero/Authorization/Roles/AbpRoleManager.cs, src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.Zero/IdentityFramework/IdentityResultExtensions.cs, src/Abp.ZeroCore/Authorization/Roles/AbpRoleManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/IdentityFramework/IdentityResultExtensions.cs
Fixes #3452 
As mentioned, `LocalizationSourceName` is added to the following classes
- `AbpUserManager`
- `AbpRoleManager`
- `AbpTenantManager`
- `LdapSettingProvider`
Added new `LocalizeErrors()` overload to accept `LocalizationSourceName`
```c#
public static string LocalizeErrors(this IdentityResult identityResult, ILocalizationManager localizationManager, string localizationSourceName){
// more code ...
}
```
=> Abp.Zero, Abp.ZeroCore configurable LocalizationSourceName

src/Abp.Web.Common/Web/Validation/ActionInvocationValidatorBase.cs
fix #3251
When the method has multiple parameters [AccountController](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Mvc/Controllers/AccountController.cs#L94), the error of ModelState is added multiple times because ModelState contains errors of all parameters, so ModelState only needs to be added once.
=> Make SetDataAnnotationAttributeErrors only called once.

src/Abp.AspNetCore/AspNetCore/AbpServiceCollectionExtensions.cs, src/Abp.AspNetCore/Json/AbpMvcContractResolver.cs
Fixes #3373 
Created `AbpMvcContractResolver` which takes in `IIocResolver` to resolve `IOptions<MvcJsonOptions>` when creating `new AbpDateTimeConverter()` for `DateTime` or `DateTime?`
Tried creating a test for this, but the Test project doesn't seems to runnable at the moment.
Will try setting up using a new template with the changes. Probably will take some time.
=> DateTimeConverter with MvcJsonOptions

src/Abp.AspNetCore/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs
fix #3643 
Make the HandleAndWrapException method under AbpExceptionFilter can be overridden.
=> fix #3643 Make the HandleAndWrapException method under AbpExceptionFilter can be overridden.

src/Abp.EntityFramework/EntityFramework/AbpDbContext.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/AbpDbContext.cs
Unable to get correct results when using Fluent API.
```cs
// EF 6
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
modelBuilder.Entity<TestEnity>().Property(e=>e.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
}
// EF Core
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
modelBuilder.Entity<Category>().Property(e => e.Id).ValueGeneratedNever();
}
```
=> Get the primary key generation method through the EF metadata.

src/Abp.AspNetCore/AspNetCore/Configuration/AbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Configuration/IAbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/Json/AbpMvcContractResolver.cs
Fixes #3675
In PR #3506 , Mvc's `DateTimeFormat` was assume to be empty string if not set.
However, the default value for `DateTimeFormat` in [JsonSerializerSettings](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializerSettings.cs#L316) is not an empty string.
Therefore, changes in this PR aim to switch Mvc's `DateTimeFormat` to be used for app services only if it is being enabled in `IAbpAspNetCoreConfiguration`
=> Mvc DateTime Format should not be default

src/Abp.Castle.Log4Net/Castle/Logging/Log4Net/Log4NetLoggerFactory.cs
fix #3678 Add a constructor in the Log4NetLoggerFactory to implement the reloadOnChange feature.
=> fix #3678 Add a constructor in the Log4NetLoggerFactory to implement the reloadOnChange feature.

src/Abp.AutoMapper/Abp.AutoMapper.csproj, test/Abp.AutoMapper.Tests/Abp.AutoMapper.Tests.csproj, test/Abp.AutoMapper.Tests/AutoMapper_Inheritance_Tests.cs, test/Abp.AutoMapper.Tests/AutoMapping_Tests.cs
There was a bug with AutoMapper.Collections that prevent the mapping to work with AutoMapKey and inheritance. I added a couple of tests and update AutoMapper.Collections.
There is a strange thing if i run AutoMapping_Tests.cs and AutoMapper_Inheritance_Tests.cs one after another they will fail. But if i run them individually or i run all the test they pass.
Would be nice if it could be integrated to the next release!
=> BugFix AutoMapKey inheritance

src/Abp.Web.Api.OData/WebApi/OData/Controllers/AbpODataEntityController.cs
Latest Abp.AspNetCore.OData and Microsoft.AspNetCore.OData packages arent working atm. Missing this attribute makes the Post never deserialize the input object correctly (basically it will always has the default object of TEntity class). Explicit usage of `FromBodyAttribute` is required for correct work.
Temporary fix can be made by overriding the method by hand in a controller, which implements `AbpODataEntityController`:
```csharp
public override Task<IActionResult> Post([FromBody]TEntity entity)
{
return base.Post(entity);
}
```
=> Fix AbpODataEntityController.Post(TEntity entty)

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Fixes #3861
Includes a new test case: `Should_Not_Write_History_If_Property_Has_No_Audited_Attribute`
=> Fix AuditedAttribute on property creating history for every property

src/Abp/Dependency/IocManager.cs
Currently there is a memoryleak in Abp unit tests, which can be detected by using dotMemory (or other similar tool).
Castle.DynamicProxy.ProxyGenerator is a class, which is responsible for creating dynamic proxies, creating dynamic assemblies and saving results in internal cache. As follows from Castle.Core documentation (see link https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md) for web application it is highly recommended to use single instance of ProxyGenerator to avoid issues with memory and performance.
The issue is that while creating IocManager, it creates WindsorContainer with default constructor, which internally creates new ProxyGenerator each time. IocManager is creating in constructor of each AbpIntegratedTestBase, so it creates new instance of …
=> Bugfix: Add using singleton Castle ProxyGenerator to avoid memoryleak in unit tests

test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemo.csproj
- Switch to `Microsoft.AspNetCore.App` from `Microsoft.AspNetCore.All`
- Added `Microsoft.VisualStudio.Web.BrowserLink` since it is not included in `Microsoft.AspNetCore.App`
=> Fixes #3805 - Switch to Microsoft.AspNetCore.App 

src/Abp.ZeroCore/Authorization/Roles/AbpRoleStore.cs
`AbpRoleStore.FindByIdAsync()` should not throw exception when no role with the given id is found.
=> Fix AbpRoleStore.FindById() exception when no role found

src/Abp/Runtime/Caching/CacheBase.cs
The `CacheBase ` class `SetAsync ` method loses `absoluteExpireTime` parameter.
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp/Runtime/Caching/CacheBase.cs#L147-L151
=> The CacheBase class SetAsync method loses absoluteExpireTime parameter.

src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCache.cs, src/Abp/Runtime/Caching/CacheBase.cs, src/Abp/Runtime/Caching/CacheExtensions.cs, src/Abp/Runtime/Caching/ICache.cs, src/Abp/Runtime/Caching/ITypedCache.cs, src/Abp/Runtime/Caching/TypedCacheWrapper.cs, test/Abp.Tests/Runtime/Caching/Memory/MemoryCacheManager_Tests.cs
Close #3884 
Implemented Multi-keys actions for `ICache` as well as `CacheBase` and `AbpRedisCache`
However, there isn't any redis command available for bulk insert of key/value pair along with **expiry time**.
See [StackExchange.Redis#IDatabase](https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/Interfaces/IDatabase.cs#L1924)
Not sure if keeping the interface consistent across other multi-keys actions (e.g Get/Set/Remove with multi-keys) is better, ~~or design the interface around redis will be sufficient~~.
Included testing for default cache implementaion. Redis test is currently skipped as we should not be testing against redis integration (instead we test for abp memory cache)
=> Introduce Multi-keys actions for ICache

src/Abp.AspNetCore/AspNetCore/Mvc/Antiforgery/AbpAutoValidateAntiforgeryTokenAuthorizationFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Antiforgery/AbpValidateAntiforgeryTokenAuthorizationFilter.cs
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate-samples/issues/61
`_cookieAuthenticationOptions.Cookie.Name` is `null` if [cookie authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x#configuration) (or [Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)) is not used.
=> Fix ContainsKey called with null if cookie auth not used

doc/WebSite/Entity-History.md, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Resolves #3913
Adds support for [Owned Entity Types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities), new in EF Core 2.0. Works for plain classes and [`ValueObject<T>`](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/58ec369bca1965771113d6e1b058693cac97f401/src/Abp/Domain/Values/ValueObject.cs).
Also:
- Updates test cases in 7a0a993
- `Should_Write_History_For_Tracked_Entities_Create`
- `Should_Write_History_For_Tracked_Entities_Create_To_Database`
- Includes a new test case in 97e6911
- `Should_Write_History_For_Tracked_Entities_Update_Owned` uses a different format that allows stepping through for easier debugging of test cases.
- Removes hardcoded "Id" for primary key in 4990ec1
=> Handle entity history for owned entities

src/Abp.AutoMapper/Abp.AutoMapper.csproj, src/Abp.AutoMapper/AutoMapper/AbpAutoMapperModule.cs, test/Abp.AutoMapper.Tests/Abp.AutoMapper.Tests.csproj, test/Abp.AutoMapper.Tests/AutoMapper_Inheritance_Tests.cs, test/Abp.AutoMapper.Tests/AutoMapping_Tests.cs
Referred to [**AutoMapper**/docs/8.0-Upgrade-Guide.md](https://github.com/AutoMapper/AutoMapper/blob/1ae2032dda6485e916c2b62c8234ee86690e26a9/docs/8.0-Upgrade-Guide.md).
- [AutoMapper](https://www.nuget.org/packages/AutoMapper) 8.0.0 was released 4 days ago.
- [AutoMapper.Collection](https://www.nuget.org/packages/AutoMapper.Collection) 5.0.0 was released 1 day ago.
- Required for new package [AutoMapper.Collection.EntityFrameworkCore](https://www.nuget.org/packages/AutoMapper.Collection.EntityFrameworkCore/) 0.1.0, released 2 hours ago.
With **AutoMapper.Collection.EntityFrameworkCore**, `AutoMapKeyAttribute` is unnecessary for entities.
`AutoMapKeyAttribute` can be useful for classes that are not in `DbContext`, like in [Abp.AutoMapper.Tests](https://github.com/aspnetboilerplate/aspnetbo …
=> Update AutoMapper and AutoMapper.Collection packages

src/Abp.Zero.Common/Authorization/Users/AbpUserBase.cs, src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs, test/Abp.Zero.SampleApp.Tests/Users/UserManager_Lockout_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_Lockout_Tests.cs
Resolves #4029 (ASP.NET Core)
Resolves #4032 (ASP.NET MVC 5)
Reverts https://github.com/aspnetboilerplate/module-zero-forsaken/commit/919e8f0b3f13109a722e9e750850189e2cca7519
Reverts  fe4ef91 (ASP.NET Core)
Partially reverts #3410 (ASP.NET MVC 5)
Updates test case:
- `Test_IsLockoutEnabled_On_User_Creation` → `Test_IsLockoutEnabled_On_User_Creation_Should_Use_Stricter_Value_If_Set` ⚠️
Includes a new test case:
- `Test_IsLockoutEnabled_On_User_Creation_Should_Use_Setting_By_Default`
The main change is calling `InitializeLockoutSettings` (ASP.NET MVC 5) and `InitializeOptionsAsync` (ASP.NET Core) in `CreateAsync` to configure the settings that will be used by ASP.NET (Core) Identity.
⚠️ Setting `IsLockoutEnabled` to `false` when the setting is `true` will result in `true`, which is …
=> Use setting for IsLockoutEnabled by default and stricter value if set

src/Abp.AspNetCore/AspNetCore/Configuration/ControllerAssemblySettingList.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Conventions/AbpAppServiceConvention.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Providers/AbpAppServiceControllerFeatureProvider.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Proxying/AspNetCoreApiDescriptionModelProvider.cs
fix #4166 Allow an assembly to create multiple dynamic API modules based on type.
If `TypePredicate `gets multiple `AbpControllerAssemblySetting`, The first one is used by default.
The same applies to generating proxy scripts.
=> fix #4166 Allow an assembly to create multiple dynamic API modules based on type

src/Abp.AutoMapper/AutoMapper/AutoMapperConfigurationExtensions.cs, test/Abp.Zero.SampleApp.EntityFrameworkCore/Abp.Zero.SampleApp.EntityFrameworkCore.csproj, test/Abp.ZeroCore.SampleApp/Abp.ZeroCore.SampleApp.csproj, test/aspnet-mvc-demo/AbpAspNetMvcDemo/AbpAspNetMvcDemo.csproj
- Fixes failing AutoMapper tests
- Removed DotNetCliToolReference from csproj files since it is included in the .Net Core SDK, See https://aka.ms/dotnetclitools-in-box
=> Fixed failing AutoMapper tests

src/Abp/EntityHistory/EntityHistoryInterceptor.cs, src/Abp/Threading/InternalAsyncHelper.cs, test/Abp.AspNetCore.Tests/Tests/EntityHistory_Reason_Tests.cs
Using `ReasonProvider.Use` with an asynchronous method in an interceptor may not work.
The asynchronous method may not have been executed yet, and the scope is over.
```c#
Using (ReasonProvider.Use(useCaseAttribute.Description))
{
//...
}
```
So I made the asynchronous method execute in the `ReasonProvider.Use` scope with some workarounds.
=> fix #4174 EntityHistoryInterceptor handle async methods.

src/Abp/Authorization/AuthorizationHelper.cs, src/Abp/Configuration/Startup/IMultiTenancyConfig.cs, src/Abp/Configuration/Startup/MultiTenancyConfig.cs, test/Abp.Tests/Authorization/AuthorizationHelper_Tests.cs, test/Abp.Tests/Authorization/AuthorizationInterceptor_Tests.cs
=> Add IgnoreFeatureCheckForHostUsers option for multitenancy

src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroTenantDbContext.cs, src/Abp.Zero.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroTenantDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroTenantDbContext.cs, src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroTenantDbContext.cs
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4237
It will be a breaking change for application which extended their application DbContext from `AbpZeroTenantDbContext`
=> Fix incorrect multi-tenancy side for AbpZeroTenantDbContext

doc/WebSite/Zero/Identity-Server.md
SORRY
This page does not exist yet. https://identityserver4.readthedocs.io/en/release/quickstarts/1_client_credentials.html
=> Fix URL about the documentation of IdentityServerConfig Class

src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpActionResultWrapperFactory.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpObjectActionResultWrapper.cs, test/Abp.AspNetCore.Tests/Abp.AspNetCore.Tests.csproj, test/Abp.AspNetCore.Tests/App/Controllers/WrapResultTestController.cs, test/Abp.AspNetCore.Tests/App/Startup.cs, test/Abp.AspNetCore.Tests/Tests/WrapResultTestController_Tests.cs
fix #4343 
Remove the JsonOutputFormatter from the AbpObjectActionResult wrapper class.
=> Remove the JsonOutputFormatter from the AbpObjectActionResult wrapper class.

src/Abp/AbpKernelModule.cs, src/Abp/Data/ConditionalValue.cs, src/Abp/RealTime/IOnlineClientManager.cs, src/Abp/RealTime/IOnlineClientStore.cs, src/Abp/RealTime/InMemoryOnlineClientStore.cs, src/Abp/RealTime/OnlineClientManager.cs, test/Abp.Tests/RealTime/InMemoryOnlineClientManager_Tests.cs, test/Abp.Tests/RealTime/InMemoryOnlineClientStore_Tests.cs
Hi,
This is a PR proposing to extend OnlineClientManager to use store like it was done in BackgroundJob
default inmemory store can be replace by any other implementation, like redis, sql etc... for user to decided or create it's own.
this was done because of signalr scaleout
Issues
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4385
https://support.aspnetzero.com/QA/Questions/6425
https://support.aspnetzero.com/QA/Questions/4337
=> Added OnlineClientStore for OnlineClientManager

doc/WebSite/Entity-History.md, src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, src/Abp.Zero.EntityFramework/EntityHistory/IEntityHistoryHelper.cs, src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs, src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroDbModelBuilderExtensions.cs, test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestBlogBuilder.cs, test/Abp.Zero.SampleApp.Tests/TestDatas/InitialTestDataBuilder.cs, test/Abp.Zero.SampleApp/EntityHistory/Blog.cs, test/Abp.Zero.SampleApp/EntityHistory/Comment.cs, test/Abp.Zero.SampleApp/EntityHistory/Post.cs
Resolve #3022 
1. **Qns: Navigation property without foreign key**
EF6 conventionally generating relationship with name `[EntityTypeOfProperty]_[EntityTypeOfNavigationProperty]`
Should `[EntityTypeOfProperty]_[EntityTypeOfNavigationProperty]` be the property name? 
**Ans**: 
Will be saving the property name as declared in the entity `[PropertyName]`.
For example, changing navigation property of entity `Post`
```csharp
_post1.Blog = _blog2;
```
Will result in the following EntityChangeSet
```csharp 
EntityName = "Post"
PropertyName = "Blog";
NewValue = { "Id": "2"};
OldValue = { "Id": "1"};
```
2. **Qns: Complex Type Property**
How will complex type property be saved in entity change set?
**Ans**:
Complex type property will be saved as a property change in the parent entity.
For example, …
=> Entity History Support for EF6

src/Abp.AspNetCore/AspNetCore/Mvc/AbpMvcOptionsExtensions.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/AbpAuditPageFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/ExceptionHandling/AbpExceptionPageFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/AbpResultPageFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpActionResultWrapperFactory.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpEmptyActionResultWrapper.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpJsonActionResultWrapper.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/AbpObjectActionResultWrapper.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/IAbpActionResultWrapper.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/IAbpActionResultWrapperFactory.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Wrapping/NullAbpActionResultWrapper.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Uow/AbpUowPageFilter.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorExceptionPageFilterTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/RazorResultPageFilterTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ExceptionFilterPageDemo.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ExceptionFilterPageDemo.cshtml.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ResultFilterPageDemo.cshtml, test/aspnet-core-demo/AbpAspNetCoreDemo/Pages/ResultFilterPageDemo.cshtml.cs
fix #4448,  related: #2464
Authorize is temporarily unable to be implemented like MVC. https://github.com/aspnet/AspNetCore/issues/8737
**It may cause a Break change of the user's existing Razor Page code.**
=> Add AbpExceptionPageFilter and AbpResultPageFilter for Razor Page.

src/Abp.Web.Common/Abp.Web.Common.csproj, src/Abp.Web.Common/Web/Localization/AbpWebXmlSource/AbpWeb-nl.xml, src/Abp.Zero/Abp.Zero.csproj, src/Abp.Zero/Zero/Localization/SourceExt/AbpZero-nl.xml, src/Abp.ZeroCore/Abp.ZeroCore.csproj, src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero-nl.xml, src/Abp/Abp.csproj, src/Abp/Localization/Sources/AbpXmlSource/Abp-nl.xml
ASP.NET Zero comes with dutch translations.
When using the confirm message from the MessageService in ABP the buttons won't be translated cause the dutch translations are not implemented in the ABP module.
In this pull request I've added the duch translations to ABP.
=> Add dutch localization

doc/WebSite/Background-Jobs-And-Workers.md, src/Abp.ZeroCore/Authorization/Users/AbpUserStore.cs, src/Abp.ZeroCore/Authorization/Users/UserTokenExpirationWorker.cs, src/Abp.ZeroCore/Zero/AbpZeroCoreModule.cs, src/Abp/BackgroundJobs/BackgroundJobConfiguration.cs, src/Abp/BackgroundJobs/IBackgroundJobConfiguration.cs, src/Abp/Threading/BackgroundWorkers/PeriodicBackgroundWorkerBase.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserManager_Tokens_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Users/UserTokenExpirationWorker_Tests.cs
Fixes #4367
- Make `RemoveTokenValidityKeyAsync` delete **ALL** keys from the same TokenValidityKeyProvider
- Remove auto clean up when calling `IsTokenValidityKeyValidAsync`
- Introduce `UserTokenExpirationWorker` periodic job (1 hour) that start in `PostInitialize` of `AbpZeroCoreModlue`
- ~Introduce clean up method `RemoveTokenValidityKeysAsync` that delete **ALL** keys that are older than the given `expireDateTime`~
- ~Expired `User.Tokens` will no longer be removed automatically when calling `IsTokenValidityKeyValidAsync`~
- ~Expired `User.Tokens` can be removed by calling `RemoveTokenValidityKeysAsync(user)`~
=> Remove expired user tokens in AbpUserStore 

src/Abp.Zero.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs, src/Abp.Zero.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroCommonDbContext.cs, src/Abp.ZeroCore.EntityFramework/Zero/EntityFramework/AbpZeroCommonDbContext.cs, src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroCommonDbContext.cs
The default filter for EF Core is `[TenantId] IS NOT NULL AND [UserId] IS NOT NULL`.  So need to set the filter parameters.
=> fix #4481 Add unique index to Setting(TenantID, Name, UserId)

src/Abp.Zero.Common/Localization/ApplicationLanguage.cs
>  Custom Culture Names  
The preferred format of the `cultureName` parameter for a new, custom culture is "[`prefix`-]`language`[-`region`][-`suffix`[`…`]]", where the `language` component is required and the `prefix`, `region`, and `suffix` components are optional. The maximum length of each component is 8 characters and the maximum length of the entire `cultureName` parameter is 84 characters.  
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureandregioninfobuilder.-ctor?redirectedfrom=MSDN&view=netframework-4.8#custom-culture-names
=> Update ApplicationLanguage MaxNameLength to 128.

src/Abp.Zero.Common/Organizations/OrganizationUnitRole.cs
Adding `ISoftDelete` interface to `OrganizationUnitRole` so that it can be correctly soft deleted.
=> Ensure OrganizationUnitRole has ISoftDelete interface

src/Abp.Zero.Common/Authorization/Roles/AbpRolePermissionCacheItemInvalidator.cs, src/Abp.Zero.Common/Authorization/Users/AbpUserPermissionCacheItemInvalidator.cs
The OrganizationUnitRole change event handler must also clear the user's permission cache. It causes a cache error.
=> OrganizationUnitRole change event handler is updated.

src/Abp.Zero.Common/Localization/ApplicationLanguageTextManager.cs
Simple fix for #4729 
Retrieves all `ApplicationText` entities with given source, culture and key, then filters in memory to get the actual entity with matching text case.
=> Fix #4729 Filter ApplicationText entities in memory

src/Abp/AbpKernelModule.cs
Generic interface should be registered explicitly.
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/5a96c66d5ec7cbfdaebe16429832b7a457872c3a/src/Abp/Dependency/BasicConventionalRegistrar.cs#L14-L23
Regression from #4702
=> fix async background job ioc registration

doc/WebSite/Localization.md, src/Abp.AspNetCore/AspNetCore/AbpApplicationBuilderExtensions.cs
Order of `RequestCultureProviders` has been changed. 
From now on, `AcceptLanguageHeaderRequestCultureProvider` will take precedence over `AbpDefaultRequestCultureProvider`.
Resolves #4714
=> order of culture provider has been changed

src/Abp.Zero.Common/Authorization/Users/UserAccountSynchronizer.cs, test/Abp.Zero.SampleApp.Tests/Users/UserAccountSynchronizer_Tests.cs
User creation events should check for duplicates.
=> Resolve #4779 UserAccountSynchronizer handles events where tenants are deleted.

src/Abp.Zero.EntityFramework/EntityHistory/Extensions/DbComplexPropertyEntryExtensions.cs, src/Abp.Zero.EntityFramework/EntityHistory/Extensions/DbPropertyEntryExtensions.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
fixes #4812 
- fix incorrect `isModified` check
- fix `ComplexProperty.HasChanged()` by changing
- `DbProperty.GetNewValue()` return `null` if `State.Deleted`
- `DbProperty.GetOriginalValue()` return `null` if `State.Added`
=> Entity History EF6 Complex Type property null value

src/Abp.AspNetCore/AspNetCore/Localization/AbpDefaultRequestCultureProvider.cs, src/Abp.AspNetCore/AspNetCore/Localization/AbpLocalizationHeaderRequestCultureProvider.cs, src/Abp.AspNetCore/AspNetCore/Localization/AbpUserRequestCultureProvider.cs
Fixes #4801
- add more logging in
- `AbpLocalizationHeaderRequestCultureProvider`
- `AbpDefaultRequestCultureProvider`
- `AbpUserRequestCultureProvider`
- check culture before saving into user setting
=> Prevent null being saved into user's DefaultLanguage

src/Abp.Zero/Authorization/Users/AbpUserManager.cs, src/Abp.ZeroCore/Authorization/Users/AbpUserManager.cs, test/Abp.Zero.SampleApp.Tests/Users/UserAppService_Tests.cs, test/Abp.Zero.SampleApp.Tests/Users/UserManager_SecurityStamp_Tests.cs
User.SecurityStamp will be changed when:
- `(AbpUserManager).ChangePasswordAsync` called
- ~~`(AbpUserManager).UpdateAsync` called and if IsUserCredentialsSameWithStored returns false
(It controls If UserName , Email and Password are changed)~~ removed
resolves #4775
=> Changes security stamp when password change via using ChangePasswordAsync function

src/Abp/Localization/Dictionaries/Json/JsonEmbeddedFileLocalizationDictionaryProvider.cs, src/Abp/Localization/Dictionaries/Json/JsonFileLocalizationDictionaryProvider.cs, src/Abp/Localization/Dictionaries/LocalizationDictionaryProviderBase.cs, src/Abp/Localization/Dictionaries/Xml/XmlEmbeddedFileLocalizationDictionaryProvider.cs, src/Abp/Localization/Dictionaries/Xml/XmlFileLocalizationDictionaryProvider.cs
Follows up #2995
- [BREAKING] 
- Replace overriable `Initialize(string sourceName)` with `InitializeDictionaries()`.
- Reason being that we configure `SourceName` during `Initialize()` and `SourceName` was not and may not be set when overridden.
- [BREAKING] 
- Move `LocalizationDictionaryProviderBase` from `Abp.Localization.Dictionaries.Xml` namespace into `Abp.Localization.Dictionaries`
- Move dictionary initialization code into `LocalizationDictionaryProviderBase`
=> fix localization dictionary providers

doc/WebSite/Caching.md, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheManager.cs, src/Abp/Runtime/Caching/CacheManagerBase.cs, src/Abp/Runtime/Caching/Configuration/CacheConfigurator.cs, src/Abp/Runtime/Caching/Configuration/CachingConfiguration.cs, src/Abp/Runtime/Caching/Configuration/ICacheConfigurator.cs, src/Abp/Runtime/Caching/Configuration/ICachingConfiguration.cs, src/Abp/Runtime/Caching/ICache.cs, src/Abp/Runtime/Caching/ICacheManager.cs, src/Abp/Runtime/Caching/ICacheOptions.cs, src/Abp/Runtime/Caching/ITypedCache.cs, src/Abp/Runtime/Caching/Memory/AbpMemoryCacheManager.cs
- caching configuration action will be passing `ICacheOptions` instead `ICache`.
*This is allow different caching implementations to be configured without implementing `ICache`*
```csharp
Configuration.Caching.ConfigureAll(cache =>
{
cache.DefaultSlidingExpireTime = TimeSpan.FromHours(2);
// The followings will NO LONGER BE SUPPORTED within configure action
var name = cache.Name;
cache.Clear();
cache.Remove("My Key");
});
Configuration.Caching.Configure("MyCache", cache =>
{
cache.DefaultSlidingExpireTime = TimeSpan.FromHours(8);
// The followings will NO LONGER BE SUPPORTED within configure action
var name = cache.Name;
cache.Clear();
cache.Remove("My Key");
});
```
- Add `ICacheOptions` which extracts configurable fields from `ICache`
(previously, `ITypeCache` implementation supports …
=> Generic CacheManagerBase

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, src/Abp/EntityHistory/EntityHistoryHelperBase.cs
As discussed in https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4815#issuecomment-525988321
We should extract ef6/ef core agonistic checks/logics out of `EntityHistoryHelper` as part of the discussion outcome.
This refactoring would help us in fixing these issues:
- Shifting `HasChanged()` check from pre-saving to post-saving ~#4815~ #4843 
- Invalid Entity class but with AuditedAttribute will get saved into Entity History #4516
However, this PR will not change any behaviors in both EntityHistoryHelper for ef6 and efcore
=> Introduce Entity history helper base

src/Abp.AspNetCore/AspNetCore/EntityHistory/HttpRequestEntityChangeSetReasonProvider.cs, src/Abp/EntityHistory/EntityChangeSetReasonProviderBase.cs
Following the conversation in https://github.com/aspnet/AspNetCore/issues/2718#issuecomment-482347489
The issue has been fixed in net core 3.x. However, chance of the fix being backported back to net core 2.x is unknown.
For now, we should cherry pick the [fixes](https://github.com/aspnet/AspNetCore/commit/187e89f6f0ee67728a50f987d63234c1900130fd) from net core team.
=> Update entity history reason provider's workaround 

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs
Since https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4813, we are returning `null` for
- new value when in deleted state
- original value when in added state
We should ensure `GetEntityId` always read from new value then original value (since Entity Id is needed in-regardless of entity state)
=> Fix EF6 Entity History Helper GetEntityId

src/Abp.AutoMapper/AutoMapper/AutoMapperObjectMapper.cs
In order to simply the extension of the AutoMapperObjectMapper, this proposal want to promote the IMapper attribute to protected.
This allows to extend the IObjectMapper without realizing a new version of Abp.
See #4882 and #4885
=> Change IMapper visibility from private to protected

test/Abp.Zero.SampleApp.EntityFramework/EntityFramework/AppDbContext.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.Zero.SampleApp/EntityHistory/Category.cs, test/Abp.Zero.SampleApp/EntityHistory/Post.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Category.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Post.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Entity History should not be capturing entity changes that does not comply with the conditions stated in https://github.com/aspnetboilerplate/aspnetboilerplate/blob/213f6f2b0e99087c6874bd52afe808b28fe36afe/doc/WebSite/Entity-History.md#entity-changes
> ### Entity Changes
> 
> -   An entity must not be one of the **IgnoredTypes**.
> -   An entity must be **public** in order to be saved in the change logs.
>     **private**, **protected**, **internal** entities are ignored.
> -   **DisableAuditing** takes priority over the **Audited** attribute when saving entity changes.
> -   An entity must satisfy one of the predicates from **Selectors**.
At the moment, when an entity fails at the validation for entity history, `HasAuditProperties` will invalidate the failed validation and proceed with …
=> Entity History handle invalid entity with audited property

src/Abp.AspNetCore/AspNetCore/Localization/AbpLocalizationHeaderRequestCultureProvider.cs
Fixes #https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4862
When a request is sent with header: `.AspNetCore.Culture: c=null|uic=null`.
`AbpLocalizationHeaderRequestCultureProvider` will return `ProviderCultureResult` with `null`,`null`.
Since the implementation of `AbpLocalizationHeaderRequestCultureProvider` was originated from [CookieRequestCultureProvider ](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Localization/src/CookieRequestCultureProvider.cs), we should patch the updates from AspNetCore code base.
=> Update ParseHeaderValue method

src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/HttpContextClientInfoProvider.cs
We don't need to explicitly read ip from the header
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/4988#issuecomment-549320792
=> Remove read ip from header

src/Abp.AspNetCore/AspNetCore/Mvc/ModelBinding/AbpDateTimeModelBinderProvider.cs, test/Abp.AspNetCore.Tests/App/Controllers/SimpleTestController.cs, test/Abp.AspNetCore.Tests/Tests/DateTimeModelBinder_Tests.cs
For the following services
````
[HttpGet]
public string GetSimpleTypeDateTimeKind(DateTime date)
{
return date.Date.Kind.ToString().ToLower();
}
[HttpGet]
public string GetNotNormalizedSimpleTypeKind([DisableDateTimeNormalization]DateTime date)
{
return date.Date.Kind.ToString().ToLower();
}
[HttpGet]
public string GetNullableSimpleTypeDateTimeKind(DateTime? date)
{
return date.Value.Kind.ToString().ToLower();
}
[HttpGet]
public string GetNotNormalizedNullableSimpleTypeDateTimeKind([DisableDateTimeNormalization]DateTime? date)
{
return date.Value.Date.Kind.ToString().ToLower();
}
```
=> Normalize simple types of DateTime(asp net core 3.x)

src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/HttpContextClientInfoProvider.cs
Resolve #5098
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field
=> Do not store IHttpContextAccessor.HttpContext in a field.

src/Abp.AspNetCore/AspNetCore/AbpApplicationBuilderExtensions.cs, src/Abp.FluentValidation/FluentValidation/AbpFluentValidationLanguageManager.cs, src/Abp.Web.Common/Web/Configuration/AbpUserConfigurationBuilder.cs, src/Abp.Web.Common/Web/Localization/LocalizationScriptManager.cs, src/Abp.Zero.Common/Localization/ApplicationLanguageManager.cs, src/Abp.Zero.Common/Localization/ApplicationLanguageProvider.cs, src/Abp.Zero.Common/Localization/IApplicationLanguageManager.cs, src/Abp.Zero.Common/Localization/MultiTenantLocalizationDictionaryProvider.cs, src/Abp/Localization/DefaultLanguageProvider.cs, src/Abp/Localization/ILanguageManager.cs, src/Abp/Localization/ILanguageProvider.cs, src/Abp/Localization/LanguageManager.cs, test/Abp.Tests/Localization/DefaultLanguageProvider_Test.cs, test/Abp.Zero.SampleApp.Tests/Localization/ApplicationLanguageManager_Tests.cs
Application will only use active languages. 
Note: Since we can not change `app.UseRequestLocalization(options);` localization options at runtime, you should restart your website after you disable language not to support disabled language.
closes #4886
=> Application will not use disabled languages by default

src/Abp.Zero.EntityFramework/EntityHistory/EntityHistoryHelper.cs, src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Resolve #4948 
- Record All Properties for Audited/Created/Deleted Entity
- Record only Audited Properties for Tracked/Untracked Entity
- Record All Properties for Audited/Tracked Entity
- Record only Audited Properties for Untracked Entity
=> Fix entity history selectors configuration

src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
to allow for localized string args
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5143
=> Fix localization getSource TypeScript function to allow multiple format args

appveyor.yml, build.cake, build.ps1, test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs
This should fix AppVeyor checks.
e.g. failed check: https://ci.appveyor.com/project/hikalkan/aspnetboilerplate/builds/29676556
=> Update image for AppVeyor to allow .NET Core 3.1

test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Update entity history test cases that was missed out in #5151
`test/Abp.Zero.SampleApp.Tests/EntityHistory/SimpleEntityHistory_Test.cs` should have the same tests as 
`test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs`
=> Update entity history test

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Advertisement.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs, test/Abp.ZeroCore.Tests/Zero/EntityHistory/SimpleEntityHistory_Test.cs
Resolves #5234
When owned type being configured with multiple foreign keys, we need to make sure Entity History read `Audited` attribute from owner entity via the correct foreign key.
=> Fix Entity History Retrieve the correct owner

src/Abp.RedisCache.ProtoBuf/Runtime/Caching/Redis/ProtoBufRedisCacheSerializer.cs, src/Abp.RedisCache/Runtime/Caching/Redis/DefaultRedisCacheSerializer.cs, src/Abp.RedisCache/Runtime/Caching/Redis/IRedisCacheSerializer.cs, test/Abp.RedisCache.Tests/DefaultRedisCacheSerializer_Tests.cs, test/Abp.RedisCache.Tests/RedisCacheManager_Test.cs
Since the `Deserialize()` accepts a `RedisValue` type, `Serialize()` should be consistently returning `RedisValue` type as well
Reference https://stackexchange.github.io/StackExchange.Redis/KeysValues.html
Also, this PR will try to re-enable redis test
=> Update Redis serializer Serialize() return type

src/Abp.Web/Auditing/IPEndPointHelper.cs, src/Abp.Web/Auditing/WebClientInfoProvider.cs, test/Abp.Web.Tests/Auditing/Client_Info_Provider_Tests.cs, test/Abp.Web.Tests/EntityHistory/EntityHistory_Reason_Tests.cs
Resolve #5282 
- Backport `IPEndPoint.Parse` from dotnet repository https://github.com/dotnet/corefx/pull/33119 into `IPEndPointHelper`
- `IPEndpoint` supports IP Address with port number where `IPAddress` only supports ip address.
- `IPEndpoint.Parse` only released on net core 3.0 not .net 4.8
- Use `HttpContextWrapper` to wrap around `HttpContext.Current`
=> add ipv6 support to web client info provider 

src/Abp.Web/Auditing/WebClientInfoProvider.cs
Regression from #5289 
We should handle HttpContext being null since HttpContextWrapper does not handle it
=> Handle HttpContext being null

src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroCommonDbContext.cs
There are some sense to make duplicated OrganizationUnit.Code:
1. Multiple creating organization unit requests at the same time.
2. Call `OrganizationUnitManager.Create` method multiple times to create multiple organization unit without `DbContext.SaveChange` each time.
The duplicated codes will cause some critical result if my entities belongs to an organization unit (filter by code or permission control by code). So I think it should be prevented completely.
=> Ensure OrganizationUnit.Code is unique.

src/Abp.AspNetCore/AspNetCore/AbpServiceCollectionExtensions.cs, src/Abp.AspNetCore/AspNetCore/Dependency/AbpCastleWindsorHostBuilderExtensions.cs
Resolves #4976 
Created `UseCastleWindsor ` and `AddAbpWithoutRegisteringServices ` extension methods.
**New Program.cs:**
```csharp
public class Program
{
public static void Main(string[] args)
{
CreateHostBuilder(args).Build().Run();
}
internal static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
.ConfigureWebHostDefaults(webBuilder =>
{
webBuilder.UseStartup<Startup>();
})
.UseCastleWindsor(IocManager.Instance.IocContainer);
}
```
**New Startup.cs:**
```csharp
public class Startup
{
// Other code blocks...
public void ConfigureServices(IServiceCollection services)
{
// Other code blocks...
// Configure Abp and Dependency Injection
services.AddAbpWithoutRegisteringServices<YourWebModule>(
// Configure Log4Net logging
options => …
```
=> Add ASP.NET Core Generic Host support

doc/WebSite/Webhook-System.md
In the IsSignatureCompatible method, first if statement is wrong.
=> Documentation correction

src/Abp/Runtime/Caching/CacheExtensions.cs, src/Abp/Runtime/Caching/CacheManagerBase.cs, src/Abp/Runtime/Caching/TypedCacheWrapper.cs, test/Abp.Tests/Runtime/Caching/Memory/MemoryCacheManager_Tests.cs
Making sure that cache type casting only happens within `TypedCacheWrapper`
=> Move cache type casting from cache extensions into TypedCacheWrapper

src/Abp.Web/Threading/HttpContextCancellationTokenProvider.cs
Resolve #5408
Move `HttpContextCancellationTokenProvider` from `Abp.Web.Mvc.Threading` namespace into `Abp.Web.Threading` so that `Abp.Web.Api` can use the provider as well.
=> HttpContextCancellationTokenProvider into Abp.Web namespace

build/Build.cs
Caused by https://github.com/nuke-build/nuke/pull/424
and upgraded in https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5414
=> Fix Nuke Build

src/Abp.AspNetCore/AspNetCore/Configuration/AbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Configuration/IAbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Caching/AllowClientCacheAttribute.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Caching/ClientCacheScope.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Caching/IClientCacheAttribute.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/Caching/NoClientCacheAttribute.cs
Since a396051e74b7da646be8133ca0b40b0c2b0b0f90, we no longer support `ClientCacheAttribute`,  CacheControl can now be achieved with #5418
=> Obsolete client cache attribute

src/Abp.Zero.Common/Webhooks/WebhookSendAttemptStore.cs, test/Abp.Zero.SampleApp.Tests/Webhooks/WebhookSendAttemptStore_Tests.cs, test/Abp.Zero.SampleApp/Linq/FakeAsyncQueryableExecuter.cs
Follows #5211 
Also implements `FakeAsyncQueryableExecuter`:
> `FakeAsyncQueryableExecuter` `await`s an asynchronous `Task` before executing an operation synchronously. This differs from `NullAsyncQueryableExecuter` a.k.a. `SyncQueryableExecuter`<sup>1</sup>, which actually only executes an operation synchronously. This can be used with tests to catch code that does not properly `await` a `Task` in a `using` block.
<sup>1</sup> `SyncQueryableExecuter` was mentioned in https://github.com/aspnetboilerplate/aspnetboilerplate/pull/5356#issuecomment-595806215.
=> Await ToListAsync in GetAllSendAttemptsByWebhookEventIdAsync

src/Abp/Domain/Entities/Caching/MayHaveTenantEntityCache.cs
There is no string interpolation symbol "$" in MayHaveTenantEntityCache. I add this.
=> Lack of string interpolation

azure-pipelines.yml, build/Build.cs, build/_build.csproj
Reverts aspnetboilerplate/aspnetboilerplate#5420
See https://github.com/nuke-build/nuke/pull/424#discussion_r401945417
We should consider reverting the previous fix when upgrading to 0.24.8 
https://github.com/nuke-build/nuke/pull/456
=> Update Nuke Build to version 0.24.8, fix AzurePipelines suffix breaking change

src/Abp.Zero.Common/Application/Features/AbpFeatureValueStore.cs, src/Abp.Zero.Common/MultiTenancy/AbpTenantManager.cs, test/Abp.ZeroCore.Tests/Zero/Tenants/FeatureValueStoreTests.cs
Otherwise, if the caller disabled filter `MayHaveTenant`, then `SetTenantId` is ineffective.
Fixes #5588 
Related: #3555, #4542
=> Enable filter MayHaveTenant for querying tenant and edition features

doc/WebSite/Value-Objects.md
Since ValueObject<T> has been removed, It's a good idea to remove it from the documentation.
=> Remove ValueObject<T> from documentation

src/Abp.AspNetCore/AspNetCore/AbpUrlHelper.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Controllers/AbpLocalizationController.cs, src/Abp.Web.Mvc/Web/Mvc/Controllers/Localization/AbpLocalizationController.cs, src/Abp.Web/Web/AbpUrlHelper.cs, src/Abp/Web/Http/AbpUrlHelper.cs, src/Abp/Web/Http/IUrlHelper.cs, test/Abp.AspNetCore.Tests/Tests/AbpLocalizationController_Tests.cs, test/Abp.Tests/Web/Http/UrlHelper_Tests.cs
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5563
- Added new `UrlHelper` at `Abp.Web.Http` in core Abp package
- Uses a combination of [System.Uri](https://docs.microsoft.com/en-us/dotnet/api/system.uri.trycreate?view=netcore-3.1) and  [System.UriBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.-ctor?view=netcore-3.1#System_UriBuilder__ctor_System_String_) to parse the given url and perform comparison on the Uri parts to determine local url/ relative url
- Deprecated old `AbpUrlHelper` in both `Abp.AspNetCore` and `Abp.Web` packages
- In `AbpLocalizationController`
- Replace `AbpUrlHelper.IsLocalUrl()` with `Abp.Web.Http.UrlHelper.LocalPathAndQuery()`
- Use `HttpUtility.UrlDecode()` on return url
=> Support encoded return url in Abp Localization controller

src/Abp/Notifications/NotificationPublisher.cs, test/Abp.Tests/Notifications/NotificationPublisher_Tests.cs
Fixes #5562 
The existing behavior has been the case since the Notification Infrastructure was introduced in #799, which was released in ABP v0.8.0.0 (Feb 2016).
However, a few other parts of the code, especially `DefaultNotificationDistribution.GetTenantIds`, appear to expect `"null"` string for host. `"0"` is already used for `NotificationInfo.AllTenantIds`.
From https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netcore-3.1:
> # String.Join Method
>
> #### Return Value
> ...
> [Empty](https://docs.microsoft.com/en-us/dotnet/api/system.string.empty?view=netcore-3.1) if `values` has zero elements or all the elements of `values` are `null`.
=> Handle null for Publish to host in NotificationPublisher

src/Abp/Runtime/Caching/AbpCacheBase.cs
Resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5391
=> use the same async lock for both sync and async Get()

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs, src/Abp/Domain/Uow/InnerSuppressUnitOfWorkCompleteHandle.cs, src/Abp/Domain/Uow/InnerUnitOfWorkCompleteHandle.cs, src/Abp/Domain/Uow/UnitOfWorkManager.cs, src/Abp/Domain/Uow/UnitOfWorkOptions.cs, src/Abp/Events/Bus/Entities/EntityChangeEventHelper.cs, test/Abp.TestBase.SampleApplication.Tests/People/PersonRepository_Tests_For_EntityChangeEvents.cs
Use `InnerSuppressUnitOfWorkCompleteHandle `for `Suppress` option.
```cs
internal class InnerSuppressUnitOfWorkCompleteHandle : InnerUnitOfWorkCompleteHandle
{
private readonly IUnitOfWork _parentUnitOfWork;
public InnerSuppressUnitOfWorkCompleteHandle(IUnitOfWork parentUnitOfWork)
{
_parentUnitOfWork = parentUnitOfWork;
}
public override void Complete()
{
_parentUnitOfWork.SaveChanges();
base.Complete();
}
public override async Task CompleteAsync()
{
await _parentUnitOfWork.SaveChangesAsync();
await base.CompleteAsync();
}
}
```
If we start a new unit of work for `Suppress`, this is unreasonable. it is no different from **RequiresNew**. consider the following code.
```
using (var uow = UnitOfWorkManager.Begin(TransactionScopeOption.Suppress))
{
_personRepository.Insert(new Person { …
```
=> Create a new unit of work for TransactionScopeOption.Suppress.

test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/AbpAspNetCoreDemo.IntegrationTests.csproj
Caused by https://github.com/aspnetboilerplate/aspnetboilerplate/commit/cc0e5f6c635ca541c56f23f5a7986d48fbb8f120#diff-0a1a13c0a13aec84a68abcb3314930f296bcb0392ba6edbbc048644ba0534fb5L10-R11:
```diff
- <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
+ <PackageReference Include="xunit.runner.visualstudio" Version="2.4.2" />
```
https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.1 depended on Microsoft.NET.Test.Sdk (>= 15.0.0).
https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.2 has no dependencies, so we need to add explicitly.
=> Add Microsoft.NET.Test.Sdk to fix missing test DLL

src/Abp.AspNetCore/AspNetCore/Localization/AbpLocalizationHeaderRequestCultureProvider.cs
Resolves #2531 
Introduce `AbpLocalizationHeaderRequestCultureProvider.HeaderName`, similar to [`CookieRequestCultureProvider.CookieName`](https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Middleware/Localization/src/CookieRequestCultureProvider.cs#L28).
In [Startup.cs#L132](https://github.com/aspnetboilerplate/module-zero-core-template/blob/1be7ee114725359002ea4b70377b331a7529cc52/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/Startup/Startup.cs#L132):
```diff
- app.UseAbpRequestLocalization();
+ app.UseAbpRequestLocalization(options =>
+ {
+     var headerProvider = options.RequestCultureProviders.OfType<AbpLocalizationHeaderRequestCultureProvider>().First();
+     headerProvider.HeaderName = "AspNetCore-Culture";
+ });
```
In …
=> Support setting header name of culture information

src/Abp.AspNetCore/AspNetCore/Localization/AbpUserRequestCultureProvider.cs
Fixes #5835 
Caused by #4823.
When we stopped saving `'null'` string (as we shouldn't), we started to get culture from cookie and header and try to save it.
`ChangeSettingForUserAsync` calls `InsertOrUpdateOrDeleteSettingValueAsync`, which tries to get the setting (to be updated or deleted) from `SettingStore` (database) instead of the setting value from the cache.
Since we [don't *store on database if the value is the default value*](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/1a9e2a88c0cc7294cd171c8dcc38d2a96851e27b/src/Abp/Configuration/SettingManager.cs#L607), we repeat this (get from database + don't store) every time.
`AbpUserRequestCultureProvider` should check that it is not the default value before calling `ChangeSettingForUserAsync`.
1. Copy …
=> Save only non-default culture to user setting

src/Abp/Resources/Embedded/EmbeddedResourcePathHelper.cs, test/Abp.Tests/Abp.Tests.csproj, test/Abp.Tests/Resources/Embedded/EmbeddedResourceTests.cs, test/Abp.Tests/Resources/Embedded/MyResources/0.9/MyScriptFile.0.9.js
Resolve #5889
The rules for names are complicated, and we can only cover the common ones.
https://github.com/dotnet/msbuild/blob/master/src/Tasks/CreateCSharpManifestResourceName.cs
=> Handle directory starting with a digit.

src/Abp.ZeroCore.EntityFrameworkCore/Zero/EntityFrameworkCore/AbpZeroDbModelBuilderExtensions.cs
After update to .Net 5 Migration is failing
Both 'TenantFeatureSetting' and 'EditionFeatureSetting' are mapped to the table 'AbpFeatures'. All the entity types in a hierarchy that don't have a discriminator must be mapped to different tables
This is happening when we are using the custom table names.
Upon checking the code for "ChangeAbpTablePrefix" found that only the base table name is changing there that's why this error is occurring.
So these changes need to be done to that function
SetTableName(modelBuilder, prefix + "Features", schemaName);
SetTableName(modelBuilder, prefix + "Features", schemaName);
Same for the PermissionSetting
SetTableName(modelBuilder, prefix + "Permissions", schemaName);
SetTableName(modelBuilder, prefix + "Permissions", schemaName);
=> Issue #5876 Migration failing

Abp.sln, nupkg/pack.ps1, src/Abp.AspNetCore.PerRequestRedisCache/Abp.AspNetCore.PerRequestRedisCache.csproj, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpAspNetCorePerRequestRedisCacheModule.cs, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCacheManager.cs, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/IAbpPerRequestRedisCache.cs, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/IAbpPerRequestRedisCacheManager.cs, test/Abp.ZeroCore.Tests/Abp.ZeroCore.Tests.csproj, test/Abp.ZeroCore.Tests/Zero/AbpZeroTestModule.cs, test/Abp.ZeroCore.Tests/Zero/Redis/AbpPerRequestRedisCacheTestModule.cs, test/Abp.ZeroCore.Tests/Zero/Redis/AbpPerRequestRedisCache_Test.cs
It implements `IAbpPerRequestRedisCache` which stores redis caches per request. It is recomended to use it in cases that you know cache will never be changed until current context is done or it is not an important value. (for example some ui view settings etc.)
Let me give an example. Your application runs on 5 instances. You pulled the data from the redis at the beginning of a request. Then, at the end of the request, you pulled the same data from the redis. Since the active httpcontext does not changed, `IAbpPerRequestRedisCache` will bring you the data it already has without pulling it from redis. Since your application runs on 5 instances, your cache value might be changed in other instances. It increases the performance because it reduces the number of redis request, but it may cause …
=> AbpPerRequestRedisCache implementation

nupkg/create-push.ps1
`push.bat` : `dotnet nuget push Abp.6.1.0.nupkg --source https://api.nuget.org/v3/index.json --api-key API_KEY`
We can also consider `*.nupkg`.
> Push all .nupkg files in the current directory to the default push source:
> dotnet nuget push "*.nupkg"
=> Use dotnet nuget options name.

common.props
Resolve #5949
Because dotnet/sdk#1458 we need to install https://www.nuget.org/packages/SourceLink.Copy.PdbFiles when we use the source link
We can test in night build.
=>  Include symbol files (*.pdb) in the built .nupkg.

src/Abp.AspNetCore/AspNetCore/Mvc/Caching/GetScriptsResponsePerUserCacheMiddleware.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Caching/GetScriptsResponsePerUserCacheMiddlewareExtensions.cs, src/Abp.Zero.Common/Caching/GetScriptsResponsePerUserCache.cs, src/Abp.Zero.Common/Caching/GetScriptsResponsePerUserCacheInvalidator.cs, src/Abp.Zero.Common/Caching/IGetScriptsResponsePerUserCache.cs
Related #3673 
It implements caching mechanism for GetScripts endpoint.
Example usage:
_Startup.cs_
```csharp
//...
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
{
app.UseGetScriptsResponsePerUserCache();
//...
```
__Layout.cshtml_
```csharp
@using Abp.Caching
@inject IGetScriptsResponsePerUserCache GetScriptsResponsePerUserCache
<script src="@(ApplicationPath)AbpScripts/GetScripts?v=@(await GetScriptsResponsePerUserCache.GetKey())" type="text/javascript"></script>
```
Then it will be cached on user's browser and cache will be expire when it is necessary
=> Implement caching mechanism for GetScripts

src/Abp.Zero.Common/Webhooks/WebhookSendAttemptStore.cs, src/Abp.Zero.Common/Webhooks/WebhookSubscriptionsStore.cs, src/Abp/Webhooks/DefaultWebhookPublisher.cs, src/Abp/Webhooks/IWebhookPublisher.cs, src/Abp/Webhooks/IWebhookSubscriptionManager.cs, src/Abp/Webhooks/IWebhookSubscriptionsStore.cs, src/Abp/Webhooks/NullWebhookSubscriptionsStore.cs, src/Abp/Webhooks/WebhookSubscriptionInfo.cs, src/Abp/Webhooks/WebhookSubscriptionManager.cs, test/Abp.Zero.SampleApp.Tests/WebHooks/WebhookSubscriptionManager_Tests.cs, test/Abp.Zero.SampleApp.Tests/Webhooks/WebhookPublisher_Tests.cs
close https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6013
Now you can publish webhook to multiple tenants
```csharp
IWebhookPublisher _webhookPublisher;
//...
var data = new {text= "text"};
_webhookPublisher.Publish(new[]
{
tenant1Id,
tenant2Id
}, "WebhookName", data);
```
=> Allow to send webhook to multiple tenant

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, src/Abp/Reflection/ProxyHelper.cs
Resolves #5996 
Tested locally by adding `builder.UseLazyLoadingProxies();` in `TestServiceCollectionRegistrar.RegisterSqliteInMemoryDb`:
- affects all tests in `Abp.ZeroCore.Tests` so I didn't push; also we want non-`UseLazyLoadingProxies` to test for regression.
- results in multiple occurrences of fixable error `System.InvalidOperationException : Property 'Blog.Posts' is not virtual. 'UseChangeTrackingProxies' requires all entity types to be public, unsealed, have virtual properties, and have a public or protected constructor. 'UseLazyLoadingProxies' requires only the navigation properties be virtual.`
- `Blog.Posts`
- `Comment.Post`
- `Post.Blog`
- `Order.Translations`, `Order.Products`
=> Handle lazy loading proxies for Entity History

src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts
`AbpUserLocalizationConfigDto.Values`' type is `Dictionary<string, Dictionary<string, string>>`, not `Dictionary<string, string>`.
Resolves #6021
=> Fix abp.localization.values typing

src/Abp/BackgroundJobs/BackgroundJobManager.cs
When I use the asynchronous background job, there is an exception that does not reflect the object type. I guess it is caused by the bug here.
=> Update BackgroundJobManager.cs for async Job.

src/Abp.Dapper/Dapper/Repositories/AbpDapperRepositoryBase.cs, src/Abp.Dapper/Dapper/Repositories/DapperRepositoryBaseOfTEntityAndTPrimaryKey.cs, src/Abp.Dapper/Dapper/Repositories/IDapperRepositoryOfTEntityAndTPrimaryKey.cs, test/Abp.EntityFrameworkCore.Dapper.Tests/Tests/Repository_Tests.cs
So, stored procedures can be used with Dapper as well. I couldn't test `CommandType.StoredProcedure` becasue we are using SQLite in unit tests and it doesn't support stored procedures.
Resolves #5992
=> Add commandType parameter to Dapper's Execute methods

src/Abp/Authorization/PermissionManager.cs, test/Abp.Tests/Authorization/PermissionDefinitionTests.cs
Fixes https://github.com/aspnetzero/aspnet-zero-core/issues/3638
More recently discussed here:
https://support.aspnetzero.com/QA/Questions/10259
_I am receiving reports from my super users (those who have access to impersonate tenant accounts) that sometimes they lose their access to administrative menu pages, such as the "Tenants" and "Maintenance" menus.
The menus disappears from the navigation tree, and even if the user types the administrative page address directly into the address bar, they are bounced as if they do not have permissions.
I have traced this back to, when the user is impersonating a tenant account, the server application has been recycled. The user then "returns to my account", and they are still logged in, but they have lost their claims to administrative permissions. …
=> Fix loss of permissions when Application Pool is recycled

doc/WebSite/AspNet-Core.md, doc/WebSite/Dynamic-Web-API.md, doc/WebSite/MVC-Controllers.md, src/Abp.AspNetCore/AspNetCore/Configuration/AbpAspNetCoreConfiguration.cs, src/Abp.AspNetCore/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/ExceptionHandling/AbpExceptionPageFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/AbpResultFilter.cs, src/Abp.AspNetCore/AspNetCore/Mvc/Results/AbpResultPageFilter.cs, src/Abp.Web.Api/WebApi/Authorization/AbpApiAuthorizeFilter.cs, src/Abp.Web.Api/WebApi/Controllers/ResultWrapperHandler.cs, src/Abp.Web.Api/WebApi/ExceptionHandling/AbpApiExceptionFilterAttribute.cs, src/Abp.Web.Common/Web/Configuration/AbpWebCommonModuleConfiguration.cs, src/Abp.Web.Common/Web/Configuration/IAbpWebCommonModuleConfiguration.cs, src/Abp.Web.Common/Web/Results/Filters/IWrapResultFilter.cs, src/Abp.Web.Common/Web/Results/Filters/WrapResultFilterCollection.cs, src/Abp.Web.Mvc/Web/Mvc/Controllers/AbpController.cs, test/Abp.AspNetCore.Tests/App/AppModule.cs, test/Abp.AspNetCore.Tests/App/Controllers/WrapResultTestController.cs, test/Abp.AspNetCore.Tests/App/ResultWrapping/CustomWrapResultFilter.cs, test/Abp.AspNetCore.Tests/Tests/WrapResultTestController_Tests.cs
It implements WrapResultFilter which can be used for overriding wrapresult for controllers.(Might be usefell for controllers which we can not use attribute on or loaded from another assembly)
Example Usage:
Create a custom wrap result filter
```csharp
public class MyWrapResultFilter : IWrapResultFilter
{
public bool HasFilterForWrapOnSuccess(string url, out bool wrapOnSuccess)
{
if (url == "xxx")
{
wrapOnSuccess = true;
return true;
}
if (url == "xxxyyy")
{
wrapOnSuccess = false;
return true;
}
wrapOnSuccess = default;
return false;
}
public bool HasFilterForWrapOnError(string url, out bool wrapOnError)
{
if (url == "xxx")
{
wrapOnError = true;
return true;
}
if (url == "xxxyyy")
{
wrapOnError = false;
return true;
}
wrapOnError = default;
return false;
}
}
```
Add that filter to wrap …
=> implement WrapResultFilter

src/Abp/Localization/LocalizationSourceHelper.cs
It is a great help to have the log message tell you what language is missing a localization instead of just the key.
=> Localization exception message to include culture

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCacheExtensions.cs, src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCacheManager.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheReplacementModule.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheReplacement_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheTestModule.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCache_Test.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/PerRequestRedisCacheTestsBase.cs
Allow users to use [PerRequestRedisCache](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs) in most cache used places to improve redis performance. With that implementation multiple redis request in one http request will be prevent in that places. 
That pr implements replacement of `AbpPerRequestRedisCache` for `ICacheManager`
Usage:
* Import `Abp.AspNetCore.PerRequestRedisCache` package
* Go to your module's preinitialize and add following code parts
```csharp
public override void PreInitialize()
{
//...
Configuration.Caching.UseRedis(usePerRequestRedisCache: true);
}
```
See https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6275 for more information about …
=> Implement replacement of AbpPerRequestRedisCache for ICacheManager

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs
The **AbpPerRequestRedisCache** was based on code I made myself earlier and shared here: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5821
We have been using my implementation of the PerRequestRedisCache for over a year, and during that time we located some bugs in the original code that we fixed on our side but never shared here.
This pull request contains all the fixes we implemented on that class.
They are all related to removing keys from the cache or clearing the entire cache. 
Once you review the file changes you will notice they are very obvious mistakes, and the last one is related to this issue: https://github.com/aspnetzero/aspnet-zero-core/issues/3958
Please let me know if you have any comments about this PR
=> Fixed bugs at AbpPerRequestRedisCache

.github/workflows/build-and-test.yml, build/_build.csproj, global.json, src/Abp.MailKit/Abp.MailKit.csproj, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
Follows #6265 and #6309
1. Update Nuke.Common from 5.3.0 to 6.0.0-beta0012 to fix AppVeyor checks.
- Also fix plugin DLL path in Release mode in test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs.
2. Update .NET SDK version in .github/workflows/build-and-test.yml to fix GitHub Actions checks.
3. Also update:
- NuGet.CommandLine from 5.11.0 to 6.0.0
- MailKit from 3.0.0-preview1 to 3.0.0
=> Update Nuke.Common package for .NET 6

doc/WebSite/Entity-History.md
Resolves #5126
The behaviour was fixed in 44e14557ce4263c2e715151e09b503ae2a35c887 and #5864.
This PR also formats code as inline code instead of bold in EntityHistory.md.
=> Document the Audited attribute on Entity/Property for Entity History

src/Abp.ZeroCore.EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/Blog.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs
Fixes #6279 
1. Currently, it causes `NullReferenceException` since `property.PropertyInfo` is `null`  if mapped directly to a field.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.ipropertybase.propertyinfo?view=efcore-3.1#Microsoft_EntityFrameworkCore_Metadata_IPropertyBase_PropertyInfo
This PR handles EF property mapped directly to a field as not an audited property.
Notably, it is not possible to define attributes on a field.
2. This PR also fixes `isAuditedProperty` in `UpdateChangeSet` and properly handles foreign key shadow property.
Related test: `Should_Write_History_For_Audited_Property_Foreign_Key_Shadow`
=> Handle EF property mapped directly to a field for Entity History

doc/WebSite/Webhook-System.md, src/Abp/Webhooks/DefaultWebhookPublisher.cs, src/Abp/Webhooks/IWebhookPublisher.cs, src/Abp/Webhooks/WebhookHeader.cs, test/Abp.Zero.SampleApp.Tests/Webhooks/WebhookPublisher_Tests.cs
closes #6322
Example usage:
```csharp
await _webhookPublisher.PublishAsync(AppWebhookDefinitionNames.Users.Created, data, 
headers: new WebhookHeader()
{
UseOnlyGivenHeaders = false,
Headers = new Dictionary<string, string>()
{
{"Key1", "Value1"},
{"Key3", "Value3"}
}
};
);
```
You can add additional headers from using it. If subscription already has given header, publisher uses the one you give.  If the **UseOnlyGivenHeaders** parameter is true, webhook will only contain given headers. Otherwise given headers will be added to predefined headers in subscription(default it false).
=> add option to add header in webhook publish methods

src/Abp.EntityFramework.Common/Repositories/EfGenericRepositoryRegistrar.cs, src/Abp.EntityFramework.Common/Repositories/IEfGenericRepositoryRegistrar.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Configuration/AbpDbContextConfiguration.cs, test/Abp.ZeroCore.SampleApp/AbpZeroCoreSampleAppModule.cs, test/Abp.ZeroCore.SampleApp/Core/EntityHistory/CustomEntity.cs, test/Abp.ZeroCore.SampleApp/EntityFramework/SampleAppDbContext.cs, test/Abp.ZeroCore.Tests/Zero/Repository/Repository_Dynamic_Entity_Registration_Tests.cs
resolves #6272 
With this PR, it will be possible to register entities registered in OnModelCreating of a DbContext for generic IRepository<> as shown below;
```c#
var genericRepositoryRegistarar = IocManager.Resolve<EfGenericRepositoryRegistrar>();
genericRepositoryRegistarar.RegisterForEntity(
typeof(SampleAppDbContext),
typeof(CustomEntity),
IocManager,
EfCoreAutoRepositoryTypes.Default
);
```
=> create RegisterForEntity method for registering a single entity for generic repositories

doc/WebSite/OData-AspNetCore-Integration.md, src/Abp.AspNetCore.OData/AspNetCore/OData/ResultWrapping/AbpODataDontWrapResultFilter.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/AbpODataEntityControllerTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemoModule.cs
Based on #6199 and aspnetboilerplate/sample-odata#20.
Related: #5856
Let's provide `AbpODataDontWrapResultFilter` in the `Abp.AspNetCore.OData` library since it's a common requirement:
1. [https://stackoverflow.com/questions/70947461/how-to-control-response-wrapping-in-abp-on-a-per-route-basis](https://stackoverflow.com/q/70947461/8601760)
2. [https://stackoverflow.com/questions/49535921/abp-aspnetcore-odata-self-referencing-loop-when-accessing-odata-metadata](https://stackoverflow.com/q/49535921/8601760)
3. [https://stackoverflow.com/questions/47888802/disable-wrapping-of-controller-results](https://stackoverflow.com/q/47888802/8601760)
Notably, `/odata/$metadata` is broken if result wrapping is not disabled (see link 2 above).
Usage, in `PreInitialize` method of a module:
```c# …
```
=> Implement AbpODataDontWrapResultFilter

src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/HttpContextClientInfoProvider.cs
Implement GetComputerName of HttpContextClientInfoProvider, which is being used to populate the ClientName property of the AuditInfo Class
resolves #6399
=> Implement GetComputerName of HttpContextClientInfoProvider

src/Abp.ZeroCore/Authorization/AbpSignInManager.cs
Fixes #6175 
Based on [https://github.com/dotnet/aspnetcore/blob/84c0baa/src/Identity/Core/src/SignInManager.cs#L762-L766](https://github.com/dotnet/aspnetcore/blob/84c0baa9a57bd6448cd1bf78b64d2c1658bf5ef6/src/Identity/Core/src/SignInManager.cs#L762-L766),
which was changed in [dotnet/aspnetcore@c6a82ad](https://github.com/dotnet/aspnetcore/commit/c6a82ad19a0bdb80b7358dc843b66664bbf33f96), so this has been broken in ABP likely since ASP.NET Core 2.1.7.
=> Add security stamp claim for two factor client

src/Abp/AbpKernelModule.cs, src/Abp/Domain/Entities/Auditing/EntityAuditingHelper.cs, src/Abp/Domain/Uow/AbpDataFilters.cs, test/Abp.TestBase.SampleApplication.Tests/Auditing/AuditedEntity_Tests.cs
Similiar to #6028 I added filters to disable updates for LastModificationTime and DeletionTime.
I didn't add a filter for CreationTime because CreationTime is not nullable.
=> Extend UnitOfWorkAuditingConfiguration to disable LastModificationTime and DeletionTime

src/Abp.AspNetCore/AspNetCore/Mvc/Auditing/HttpContextClientInfoProvider.cs
After an upgrade to 7.2 my app was really slow. The reason is the implementation in #6400.
`remoteIpAdress` can be null, but null isn't a valid input for `Dns.GetHostEntry`.
My log was full with this error message:
```
INFO  2022-06-09 15:46:20,519 [63   ] osoft.EntityFrameworkCore.Infrastructure - Entity Framework Core 6.0.5 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.5' with options: None
WARN  2022-06-09 15:46:20,524 [63   ] c.Auditing.HttpContextClientInfoProvider - System.ArgumentNullException: Value cannot be null. (Parameter 'address')
at System.Net.Dns.GetHostEntry(IPAddress address)
at Abp.AspNetCore.Mvc.Auditing.HttpContextClientInfoProvider.GetComputerName()
```
=> Added null check for remoteIpAdress in HttpContextClientInfoProvider.GetComputerName

src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheOptions.cs, src/Abp.RedisCache/Runtime/Caching/Redis/RealTime/RedisOnlineClientStore.cs, src/Abp.RedisCache/Runtime/Caching/Redis/RedisCacheConfigurationExtensions.cs
resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6503
=> Implemented Redis online client store

doc/WebSite/Caching.md, src/Abp/Runtime/Caching/Configuration/CachingConfiguration.cs, src/Abp/Runtime/Caching/Configuration/ICachingConfiguration.cs, src/Abp/Runtime/Caching/Memory/AbpMemoryCache.cs, src/Abp/Runtime/Caching/Memory/AbpMemoryCacheManager.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/MemoryCacheOptions_Test.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/AbpAspNetCoreDemoModule.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6471
=> Introduced MemoryCacheOptions for ICachingConfiguration

src/Abp/Notifications/NotificationInfo.cs, src/Abp/Notifications/UserNotificationInfo.cs
=> Add max length to TargetNotifiers

doc/WebSite/SignalR-AspNetCore-Integration.md, src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr-client.js
=> Allow passing options to SignalR withUrl

.github/workflows/build-and-test.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/aspnetboilerplate/aspnetboilerplate/actions/runs/3091177002/jobs/5073449678#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- build-and-test.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying …
=> ci: add minimum GitHub token permissions for workflow

src/Abp.ZeroCore/Zero/Localization/SourceExt/AbpZero-pt-BR.xml
The Portuguese translation of the "userName" tag, in this context, is better understood as "login"
=> Fixed translation in pt-br for the DuplicateUserName tag. 

src/Abp.Zero.Ldap/Ldap/Authentication/LdapAuthenticationSource.cs, src/Abp.Zero.Ldap/Ldap/Configuration/ILdapSettings.cs, src/Abp.Zero.Ldap/Ldap/Configuration/LdapSettingNames.cs, src/Abp.Zero.Ldap/Ldap/Configuration/LdapSettings.cs
=> Add UseSsl LDAP setting to support LDAPS

src/Abp/DynamicEntityProperties/DynamicPropertyManager.cs, test/Abp.Zero.SampleApp.Tests/DynamicEntityProperties/DynamicPropertyManager_Tests.cs
=> Check if dynamic property exists during add operation

src/Abp.Zero.Common/Authorization/AbpLoginResultType.cs, src/Abp.ZeroCore/Authorization/Users/AbpLoginResult.cs
- This PR adds `FailedForOtherReason` to `AbpLoginResultType` and also allows to set `FailReason` of `AbpLoginResult` when result is `FailedForOtherReason`
resolves #6691
=> Added FailedForOtherReason login result type and custom fail reason message

src/Abp.AspNetCore/Json/DateOnlyJsonConverter.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/AbpAspNetCoreDemoCoreModule.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Application/ModelBindingAppService.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/ModelBindingAppServiceTests.cs, test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs
=> add dateonly json convertor

doc/WebSite/Notification-System.md, global.json, src/Abp.Zero.Common/Notifications/NotificationStore.cs, src/Abp/Notifications/DefaultNotificationDistributer.cs, src/Abp/Notifications/INotificationStore.cs, src/Abp/Notifications/INotificationSubscriptionManager.cs, src/Abp/Notifications/NotificationSubscriptionInfo.cs, src/Abp/Notifications/NotificationSubscriptionManager.cs, src/Abp/Notifications/NullNotificationStore.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/NotificationDistributer_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/NotificationStore_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Notifications/NotificationSubscription_Tests.cs
=> Allow users to subscribe specific notifiers

src/Abp.HtmlSanitizer/HtmlSanitizer/HtmlSanitizerHelper.cs
When passing null to the SanitizeObject method, it would cause `var classType = item.GetType()` to throw a NullReferenceException since `item` is null.
Passing null to the SanitizeObject method can occur, for example, by accident when iterating over an IEnumerable or IDictionary, since entries could be null.
To prevent code duplication, I've added a null check to the start of the SanitizeObject method.
=> Fixed a null reference exception in Abp.HtmlSanitizer.

doc/WebSite/Abp-Session.md
Small typo in `Abp-Session.md`. `is` -> `are`
=> typo: in Abp-Session.md

src/Abp.Web.Resources/Abp/Framework/scripts/libs/abp.signalr.d.ts
Currently, withUrlOptions  is defined as of type string, however, as this documentation from Microsoft shows, we could define quite a few properties there: https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-7.0&tabs=javascript#configure-additional-options
- Inside the .withUrl method it is expected to pass object as a second parameter:
`let connection = new signalR.HubConnectionBuilder().withUrl("/chathub", { `
`      // "Foo: Bar" will not be sent with WebSockets or Server-Sent Events requests`
`      headers: { "Foo": "Bar" },`
`       transport: signalR.HttpTransportType.LongPolling `
` })
.build();`
- Also inside the abp.signalr-client.js **start** method we are using the withUrlOptions  as object:
`abp.signalr.withUrlOptions.transport = transport;
` …
=> Changed the type of withUrlOptions from string to object to accommodate missing properties.

src/Abp/Events/Bus/EventBus.cs, test/Abp.Tests/Events/Bus/EventRegisterUnregisterTest.cs
resolves #6726 
resolves #6737 
Call ToList while getting event handlers during event trigger process. We decided not to use `lock` because of performance and it requires big refactoring on the existing code because we are using async/await in the current code block.
=> Call ToList while getting event handlers during event trigger process

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCache.cs
resolves #6744 
Now you can create your own implementation of AbpRedisCache and overwrite `ClearRedisCacheInternal` method to change behaviour of Clearing redis cache.
We will work on clustered Redis usage in below issue
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6820
=> Allow overwriting Redis cache clear methods

src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Hubs/OnlineClientHubBase.cs, src/Abp.AspNetCore.SignalR/AspNetCore/SignalR/Notifications/SignalRRealTimeNotifier.cs, src/Abp.RedisCache/Runtime/Caching/Redis/RealTime/RedisOnlineClientStore.cs, src/Abp.Web.SignalR/Web/SignalR/Hubs/AbpCommonHub.cs, src/Abp.Web.SignalR/Web/SignalR/Notifications/SignalRRealTimeNotifier.cs, src/Abp/RealTime/IOnlineClientManager.cs, src/Abp/RealTime/IOnlineClientStore.cs, src/Abp/RealTime/InMemoryOnlineClientStore.cs, src/Abp/RealTime/OnlineClientManager.cs, src/Abp/RealTime/OnlineClientManagerExtensions.cs, test/Abp.Tests/RealTime/InMemoryOnlineClientManager_Tests.cs, test/Abp.Tests/RealTime/InMemoryOnlineClientStore_Tests.cs
I changed all synchronous calls to asynchronous calls in interfaces/classes: 
* IOnlineClientStore
* IOnlineClientManager / OnlineClientManager
* OnlineClientManagerExtensions
* InMemoryOnlineClientStore
* RedisOnlineClientStore.cs
And in all places where they are called (including tests).
Removed:
* SignalRRealTimeNotifier.SendNotifications() method and depends: 
I also changed the logic of **IOnlineClientManager.GetAllByUserId**, 
namely optimized this by storing a separate hash set of users with references to the connection hash set in Redis.
Added GetAllByUserId / GetAllByUserIdAsync to IOnlineClientStore and RedisOnlineClientStore.
When using the latest version of a project, I noticed that the number of threads in the thread pool grows about x3 times the usual value since synchronous …
=> Async instead of sync methods in realtime classes

src/Abp/Domain/Uow/UnitOfWorkBase.cs
Hello, 
The problem arises when the filter does not have old value. When disposing a filter that is set with SetFilterParameter method the new parameter should be deleted because it does not exist in the first place. The logical correction should be to make the filters array intact exactly like when it was before calling the SetFilterParameter method.
=> DisposeAction should revert to initial state of the filters if the parameter does not have old value.

src/Abp/Domain/Entities/Caching/MultiTenancyEntityCache.cs
resolves #6850 
GetCacheItemFromDataSourceAsync method called in MultiTenancyEntityCache has been fixed.
=> GetCacheItemFromDataSourceAsync method called fixed.

src/Abp.Zero/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/AbpLoginManager.cs
Resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6862
SaveLoginAttempt fails due to exceeded max length of Client IP Address in UserLoginAttempt table. This PR fixes this issue by truncating string to max allowed length.
=> Honour column max length during UserLoginAttempt insertion

src/Abp.AspNetCore.PerRequestRedisCache/Runtime/Caching/Redis/AbpPerRequestRedisCache.cs, src/Abp.RedisCache.ProtoBuf/Runtime/Caching/Redis/AbpRedisCacheOptionsExtensions.cs, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCache.cs, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheKeyNormalizeArgs.cs, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheKeyNormalizer.cs, src/Abp.RedisCache/Runtime/Caching/Redis/AbpRedisCacheOptions.cs, src/Abp.RedisCache/Runtime/Caching/Redis/IAbpRedisCacheKeyNormalizer.cs, test/Abp.RedisCache.Tests/RedisCacheManager_Test.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCacheReplacement_Tests.cs, test/Abp.ZeroCore.Tests/Zero/Redis/PerRequestRedisCache/AbpPerRequestRedisCache_Test.cs, test/aspnet-core-demo/AbpAspNetCoreDemo.Tests/Tests/AbpODataDtoControllerPermissionTests.cs
Resolves #6877 
Normalize Key operation with KeyPrefix addition has been added to Redis Cache. Additionally, the ability to include tenant-specific keys can be activated in the options if desired.
=> Normalize Key added with KeyPrefix in Redis Cache and TenantKeyEnabled

doc/WebSite/Document-Index.md, doc/WebSite/Documents.md
Resolves [vs-internal/issues/3981](https://github.com/volosoft/vs-internal/issues/3981)
The "API Reference" title url has been replaced with the current url in the Documents.md and Documents-Index.md files located in the Website folder.
=> Changed `API Reference` title url

src/Abp.EntityFramework/EntityFramework/Repositories/EfRepositoryBaseOfTEntityAndTPrimaryKey.cs, src/Abp/Domain/Repositories/IRepositoryOfTEntityAndTPrimaryKey.cs
- Added GetAllAsync method to the IRepository interface. (#6922)
- Added GetAllIncludingAsync method to the IRepository interface (#6923)
- Implemented GetAllIncludingAsync in the EfRepositoryBase class, as it previously was not implemented, which meant that the AbpRepositoryBase class implementation was used, which just returns the result of GetAllAsync, which does not use the filters.
=> Added missing repository methods and implementation.

src/Abp.EntityFramework/EntityFramework/Linq/EfAsyncQueryableExecuter.cs, src/Abp.EntityFrameworkCore/EntityFrameworkCore/Linq/EfCoreAsyncQueryableExecuter.cs, src/Abp/Linq/IAsyncQueryableExecuter.cs, src/Abp/Linq/NullAsyncQueryableExecuter.cs, test/Abp.Zero.SampleApp.Tests/DynamicEntityProperties/DynamicEntityPropertiesTestModule.cs, test/Abp.Zero.SampleApp/Linq/FakeAsyncQueryableExecuter.cs
Resolves #6920 
ICancellationTokenProvider was implemented in the EfCoreAsyncQueryableExecuter and EfAsyncQueryableExecuter classes.
=> Added asynchronous cancel mode in EfCoreAsyncQueryableExecuter

src/Abp.EntityFrameworkCore/EntityFrameworkCore/Repositories/EfCoreRepositoryExtensions.cs, test/Abp.ZeroCore.Tests/Zero/Repository/AbpEntityFrameworkCoreEfPlusExtensions_Tests.cs
resolves #6843 
Introduced BatchDelete and BatchUpdate repository extension methods. These methods can be used instead of `Abp.EntityFrameworkCore.EFPlus`. We will keep Abp.EntityFrameworkCore.EFPlus for a while and then delete this package.
=> Add BatchDelete and BatchUpdate EF Core repository extension methods

src/Abp.Zero.Common/Localization/EmptyDictionary.cs, src/Abp.Zero.Common/Localization/IMultiTenantLocalizationDictionary.cs, src/Abp.Zero.Common/Localization/IMultiTenantLocalizationSource.cs, src/Abp.Zero.Common/Localization/MultiTenantLocalizationDictionary.cs, src/Abp.Zero.Common/Localization/MultiTenantLocalizationSource.cs, src/Abp/Localization/Dictionaries/DictionaryBasedLocalizationSource.cs, src/Abp/Localization/Dictionaries/ILocalizationDictionary.cs, src/Abp/Localization/Dictionaries/LocalizationDictionary.cs, src/Abp/Localization/Sources/ILocalizationSource.cs, src/Abp/Localization/Sources/NullLocalizationSource.cs, src/Abp/Localization/Sources/Resource/ResourceFileLocalizationSource.cs, test/Abp.Tests/Localization/ResourceFileLocalizationSource_Tests.cs, test/Abp.Tests/Localization/Test_DictionaryBasedLocalizationSource.cs
Hello,
Find the key to a localized string, this is needed when you try to import or convert back the localized strings to corresponding type or enum.
ResourceFileLocalizationSource does not provide any method to find key properly, so returning null.
=> Add TryGetKey method to ILocalizationDictionary

src/Abp.Zero/Authorization/AbpLoginManager.cs, src/Abp.ZeroCore/Authorization/AbpLoginManager.cs
Resolves #6999 
AbpLoginManager has been fixed to check whether the user is locked or not when logging in with External Login.
=> Added shouldLockout to UserLoginInfo override LoginAsync methods

doc/WebSite/Articles/Aspect-Oriented-Programming-using-Interceptors/index.html
Resolves #7006 
While rendering the document file, the characters greater than and less than and the name written between them are not visible. This problem has been corrected by using character reference.
=> Fixed small is big is big character not appearing

src/Abp.ZeroCore/Authorization/AbpLoginManager.cs
Resolves https://github.com/aspnetboilerplate/aspnetboilerplate/issues/7024
GetFailedPasswordValidationAsLoginResultAsync method was missing return on keyword. This problem was causing the user password and lock check not to be performed.
=> Fixed failed validation login result error

src/Abp.RedisCache/Runtime/Caching/Redis/DefaultRedisCacheSerializer.cs
Resolves #7040 
A converter has been added to deserialize the System.Type data type in RedisCacheSerializer.
=> Fixed System.Type conversion error during deserialization

src/Abp.HangFire.AspNetCore/Hangfire/HangfireBackgroundJobManager.cs, src/Abp.HangFire/Hangfire/HangfireBackgroundJobManager.cs
Resolves #7082 
The HangfireBackgroundJobManager class has been refactored to use HangfireBackgroundJob through dependency injection instead of utilizing it as a static class.
=> Replaced static HangfireBackgroundJob methods with DI-injected IBackgroundJobClient

doc/WebSite/Zero/Startup-Template-Core.md
Resolves #7097 
The startup-template document has been updated as gulp is now used instead of libman for client packages in the Mvc project.
=> Updated startup-template document for gulp info

src/Abp/Domain/Entities/Auditing/EntityAuditingHelper.cs
Resolves #7111 
In the SetModificationAuditProperties method of EntityAuditingHelper, setting LastModifierUserId to null if UserId is null has been removed because it is set based on unconditional userId. Here, LastModifierUserId filter control was given priority because when the LastModifierUserId filter was disabled, LastModifierUserId was set to null. Thus, when the filter is disabled, this property will not change.
=> Refactored LastModifierUserId handling in EntityAuditingHelper

test/aspnet-core-demo/AbpAspNetCoreDemo.Core/Application/ProductAppService.cs
Each task is run in a new scope using Task.Run.
A new IServiceScope is created for each task to ensure that each task gets its own DbContext instance. The IProductRepository is resolved from the new scope to ensure it uses the new DbContext instance.
fixes #7090
@dotnet-policy-service agree
=> In this code:

test/Abp.ZeroCore.Tests/Zero/AbpZeroTestBase.cs
=> Use UsingDbContextAsync instead of UsingDbContext in GetCurrentUserAsync

src/Abp/Domain/Entities/Auditing/EntityAuditingHelper.cs
Resolves #7058 
Modified SetModificationAuditProperties to include an early return if LastModifierUserId is already populated. This ensures the manually set value is preserved, bypassing the multi-tenancy logic that would previously nullify it.
=> Allow manual cross tenant LastModifierUserId assignment

src/Abp/Abp.csproj, src/Abp/SequentialGuidGenerator.cs
Starting from version 10.0, files from Microsoft.VisualStudio.Web.CodeGeneration.Design are being dumped into the output directory. These appear to be files that are not needed at runtime.
Additionally, the NuGet warning about problematic or deprecated libraries has disappeared.
=> remove Microsoft.VisualStudio.Web.CodeGeneration.Design's files
